---
title: "02-Spotplot VMH Sex DEGs under FDR10"
author: "Bernard Mulvey"
date: "2023-06-21"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(ggplot2)
library(data.table)
library(Biostrings)
library(gridExtra)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(scater)
library(ggspavis)
library(SpatialExperiment)
library(Polychrome)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

### Data loadup
```{r}
hyp2 <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_061323_HarmonyBSpc-q2VMH_rowname-key.RDS")

colnames(hyp2) <- colData(hyp2)$key
rownames(hyp2) <- rowData(hyp2)$gene_name

vmhde <- fread("analysis/data/H04-2cluster-consensus-VMH/pseudobulk-SEX-DE_Bspace-VMH-nonvmh-clusters.txt")

```

### extract significant (FDR<0.1) sex DEGs, and let's drop chrY genes at least
```{r}
vmhde2 <- vmhde[group_name=="VMH"&adj.P.Val<0.1&!(gene_name %in% c("ZFY","UTY","PRKY","DDX3Y","TTTY14","NLGN4Y","EIF1AY","TMSB4Y","USP9Y","PCDH11Y","RPS4Y1","KDM5D")),gene_name]

hyp2.plt <- hyp2[,hyp2$BSp_q2_consensus_vmh=="VMH"]

i <- 1
for (i in c(1:48)){
    curgene <- vmhde2[i]
    plt <- spatialLIBD::vis_grid_gene(hyp2.plt,geneid = curgene,return_plots = T,spatial=F,point_size = 1,auto_crop = T)
    ### adjust font sizes
    plt <- lapply(plt,FUN=function(x){x+
            theme(plot.title = element_text(size = 11,hjust=0.5), strip.text = element_text(size=10), legend.text = element_text(size=10), legend.title = element_text(size=10,hjust=0.5))
            })
    png(paste0("plots/H04-2cluster-consensus-VMH/02-VMH_sexDEGs_spotplots/",curgene,".png"),width=1000,height=800)
    do.call("grid.arrange",plt)
    dev.off()
}

rm(i,curgene,hyp2.plt,plt)
gc(full=T)
```


### Volcano plot for VMH and other
```{r}
pdf("plots/H04-2cluster-consensus-VMH/VMH Sex DE volcano.pdf",height=7,width=7)
ggplot(vmhde[group_name=="VMH"],aes(y=-log10(adj.P.Val),x=logFC))+
    geom_point()+
    geom_hline(yintercept = -log10(0.1),col="red",alpha=0.7)+
    geom_text(data = vmhde[group_name=="VMH"&abs(logFC)>1.5&adj.P.Val<0.05&gene_name %in% vmhde2],aes(x=ifelse(logFC<0,yes=logFC-2,no=logFC+2),y=-log10(adj.P.Val)+0.1,label=gene_name))+
    geom_text(aes(x=9,y=-log10(0.15),label="FDR<0.1"))+
    ylab("-log10 (FDR)")+
    xlab("logFC (M vs. F)")
dev.off()
    



```
