---
title: "03-Spotplot k2 VMH genes enriched by pseudobulk DE"
author: "Bernard Mulvey"
date: "2023-06-22"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(ggplot2)
library(data.table)
library(Biostrings)
library(gridExtra)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(scater)
library(ggspavis)
library(SpatialExperiment)
library(Polychrome)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

### Data loadup
```{r}
hyp2.vmh <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_061323_HarmonyBSpc-q2VMH_rowname-key.RDS")

colnames(hyp2.vmh) <- colData(hyp2.vmh)$key
rownames(hyp2.vmh) <- rowData(hyp2.vmh)$gene_name

vmhde <- fread("analysis/data/H04-2cluster-consensus-VMH/pseudobulk-VMH-other-DE.txt")
vmhde.sexcov <- fread("analysis/data/H04-2cluster-consensus-VMH/pseudobulk-VMH-other-DE_sexcovaried.txt")

```

### extract significant (FDR<10e-7) VMH-enriched DEGs (logFC>0), and let's drop chrY genes at least
```{r}
vmhdegs <- unique(c(
    vmhde[logFC>0&adj.P.Val<(10e-7)&!(gene_name %in% c("ZFY","UTY","PRKY","DDX3Y","TTTY14","NLGN4Y","EIF1AY","TMSB4Y","USP9Y","PCDH11Y","RPS4Y1","KDM5D")),gene_name],
    vmhde.sexcov[logFC>0&adj.P.Val<(10e-7)&!(gene_name %in% c("ZFY","UTY","PRKY","DDX3Y","TTTY14","NLGN4Y","EIF1AY","TMSB4Y","USP9Y","PCDH11Y","RPS4Y1","KDM5D")),gene_name]
    ))

hyp2.plt <- hyp2.vmh

i <- 1
for (i in c(1:length(vmhdegs))){
    curgene <- vmhdegs[i]
    colLabels(hyp2.plt) <- logcounts(hyp2.plt)[curgene,]
    plt <- plotSpots(hyp2.plt,annotate = "label",palette=viridis::viridis(n=1))
    png(paste0("plots/H04-2cluster-consensus-VMH/03-VMH_upreg_spotplots/",curgene,".png"),width=800,height=800)
    print(plt)
    dev.off()
}

rm(i,curgene,hyp2.plt,plt)
gc(full=T)
```


### Volcano plot for VMH and other
```{r}
pdf("plots/H04-2cluster-consensus-VMH/03-VMH Enrichment volcano.pdf",height=7,width=7)
ggplot(vmhde,aes(y=-log10(adj.P.Val),x=logFC))+
    geom_point()+
    geom_hline(yintercept = -log10(0.05),col="red",alpha=0.7)+
    geom_text(aes(x=3.25,y=-log10(0.125),label="FDR<0.1"))+
    ylab("-log10 (FDR)")+
    xlab("logFC (VMH(+) vs. Other(-))")+
    ylim(0,8)
dev.off()
    



```
