---
title: "04-Plot VMH-only nnSVGs"
author: "Bernard Mulvey"
date: "2023-06-23"
output: html_document
---

```{r setup, include=FALSE}
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(SpatialExperiment)
library(ggspavis)
library(scater) # addPerCellQC
library(BiocParallel)
library(scran)
library(parallel)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

Load up data
```{r}
hyp2.vmh <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_061323_HarmonyBSpc-q2VMH_rowname-key.RDS")

rownames(rowData(hyp2.vmh)) <- rowData(hyp2.vmh)$gene_name
hyp2.vmh <- hyp2.vmh[,which(hyp2.vmh$BSp_q2_consensus_vmh=="VMH")]

vmhsvg <- fread("analysis/data/H04-2cluster-consensus-VMH/meangeneranks_nnSVG_samplewise_n3s0.5_VMHspotsonly.txt")

### subset to genes that were ranked in at least 3 samples (i.e. min # of samples in the smallest group by sex (males))
vmhsvg <- vmhsvg[n_naSamps<=5]

### anddddd drop MT genes for now
vmhsvg <- vmhsvg[!(gene_name %in% grep(gene_name,pattern="^MT-",value=T))]
```


```{r}










```
