---
title: "02-Markers for 2cluster Consensus VMH"
author: "Bernard Mulvey"
date: "2023-06-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(scater)
library(scran)
library(BiocParallel)
library(parallel)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```


Load SPE with vmh already annotated
```{r}
hyp2.vmh <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_061323_HarmonyBSpc-q2VMH_rowname-key.RDS") 

# change/ensure colnames/colData's rownames == colData()$keys
colnames(hyp2.vmh) <- colData(hyp2.vmh)$key
```

```{r}
colLabels(hyp2.vmh) <- factor(hyp2.vmh$BSp_q2_consensus_vmh)
multistat <- scoreMarkers(hyp2.vmh,hyp2.vmh$label,full.stats=T)

bpparam=MulticoreParam(2)
register(bpparam)

## why the fuck is this producing columns named "VMH"? Didn't have that problem before. happens without d.t., without parallelizing, etc. maybe an issue in DataFrame? fixed fored now with setnames in the following apply:
vmh.markers <- bplapply(multistat,BPPARAM = bpparam, FUN=function(x){
        y <- as.data.table(x,keep.rownames=T)
        y <- y[rank.logFC.cohen<=2500|rank.AUC<=2500|rank.logFC.detected<=2500]
        ## fix col name changes
        setnames(y,c(2:ncol(y)),colnames(x)) 
        return(y)
})

saveRDS(vmh.markers,"analysis/data/H04-2cluster-consensus-VMH/2cluster-consensusVMH_scoremarkers_out.RDS")
```


### Save a table of key stats for top genes
```{r}
i<-1
for (i in c(1:length(vmh.markers))){
    tmp <- as.data.table(vmh.markers[[i]],keep.rownames=T)
    tmp[,cluster:=names(vmh.markers)[i]]
    setnames(tmp,"rn","ens")
    if(i==1){
        vmh.markers.plt <- tmp
    }
    else{
        vmh.markers.plt <- rbind(vmh.markers.plt,tmp)
    }
    rm(tmp)
}
rm(i)

### add gene info
genedat <- as.data.table(rowData(hyp2.vmh),keep.rownames=T)
vmh.markers.plt <- merge.data.table(vmh.markers.plt,genedat[,.(rn,gene_name)],by.x="ens",by.y="rn")

# reorder columns for easier spreadsheet-style overview
neword <- c("cluster","gene_name",grep(names(vmh.markers.plt),pattern="rank",value=T),grep(names(vmh.markers.plt),pattern="self",value=T),grep(names(vmh.markers.plt),pattern="other",value=T))
neword <- c(neword,names(vmh.markers.plt)[which(!(names(vmh.markers.plt) %in% neword))])

vmh.markers.plt <- vmh.markers.plt[,..neword]

write.table(vmh.markers.plt,"local_results_ref/top_markers_fullstats_2clustvmh.txt",sep='\t',quote=F,row.names=F,col.names=T)

rm(multistat,vmh.markers,neword,bpparam,genedat)
```

Intersect these to the HypoMap mouse markers and get mean rank per human cluster per hypomap type
```{r}
hmap <- fread("analysis/ref/Hypomap multilevel cell type hierarchy marker genes Steuernagel 22 nat metab.txt")
hmap[,gene:=toupper(gene)]

vmh.hmap <- merge.data.table(vmh.markers.plt[cluster=="VMH"],hmap,by.x="gene_name",by.y="gene")

colnames(vmh.hmap)

### get mean human analysis marker rank for genes that are also markers of any one cluster in hypomap (lower --> stronger match). also get number of markers intersecting for each
fcco.hmap <- vmh.hmap[,mean(rank.logFC.cohen),by=c("cluster","cluster_name")]
fcco.hmap2 <- vmh.hmap[,.N,by=c("cluster","cluster_name")]
fcco.hmap <- merge.data.table(fcco.hmap,fcco.hmap2,by=c("cluster","cluster_name"))

auc.hmap <- vmh.hmap[,mean(rank.AUC),by=c("cluster","cluster_name")]
auc.hmap2 <- vmh.hmap[,.N,by=c("cluster","cluster_name")]
auc.hmap <- merge.data.table(auc.hmap,auc.hmap2,by=c("cluster","cluster_name"))

fcd.hmap <- vmh.hmap[,mean(rank.logFC.detected),by=c("cluster","cluster_name")]
fcd.hmap2 <- vmh.hmap[,.N,by=c("cluster","cluster_name")]
fcd.hmap <- merge.data.table(fcd.hmap,fcd.hmap2,by=c("cluster","cluster_name"))

hmaprankints <- list(fcco.hmap,auc.hmap,fcd.hmap)
names(hmaprankints) <- c("Mean_rank.logFC.cohen_perHypoMapClust","Mean_rank.logFC.cohen_perHypoMapClust")

hmaprankints <- lapply(hmaprankints,FUN=function(x){
    setnames(x,"cluster_name","hypomap_cluster")
})

saveRDS(hmaprankints,"analysis/data/H04-2cluster-consensus-VMH/mean_ranks_FCcohen-FCdetec-AUC_perVMH2clust-markers_perHypomap-markers.RDS")

rm(vmh.markers.plt,hmap,hmaprankints,fcd.hmap,fcd.hmap2,fcco.hmap,fcco.hmap2,auc.hmap,auc.hmap2)
```
