---
title: "02-plot BayesSpace q2 hvg1020 svg1020 spotplots"
author: "Bernard Mulvey"
date: "2023-06-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(ggplot2)
library(data.table)
library(Biostrings)
library(gridExtra)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(ggspavis)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

loadup
```{r}
hyp2 <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_D07-075_B1 crop 070223.RDS") 

# change colnames/colData's rownames to keys
colnames(hyp2) <- colData(hyp2)$key
#

q2s <- list.files("analysis/data/spe_070123/H02-clustering/03b-BSpace_mnn30_q2",pattern=".txt",full.names = T)

q2list <- lapply(q2s,FUN=function(x){
    x <- fread(x)
    y <- as.data.frame(x)
    rownames(y) <- y$rn
    if(sum(rownames(y)==colnames(hyp2))!=ncol(hyp2)){
        y <- y[colnames(hyp2),]
    }
    y
})
names(q2list) <- gsub(q2s,pattern="^.*BSpace_mnn30_q2.*\\/(.*)\\.txt$",replacement="\\1")
rm(q2s)

```

plot
```{r}
i<-1
for (i in c(1:4)){
    colLabels(hyp2) <- factor(q2list[[i]]$label)
    plt <- spatialLIBD::vis_grid_clus(hyp2,clustervar = "label",pdf_file = NULL,spatial=F,point_size = 1,auto_crop = T,return_plots = T)
    ### adjust font sizes
    plt <- lapply(plt,FUN=function(x){x+
            theme(plot.title = element_text(size = 11,hjust=0.5), strip.text = element_text(size=10), legend.text = element_text(size=10), legend.title = element_text(size=10,hjust=0.5))
            })
    #
    png(paste0("plots/spe_070123/H04-2cluster-consensus-VMH/01-bayesspace_q2_HVGorSVG_spotplots/",names(q2list)[i],".png"),width=1000,height=800)
    do.call("grid.arrange",plt)
    dev.off()
}




```
