---
title: "01-One-vs-all marker gene identification"
author: "Bernie Mulvey"
date: "2023-06-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(ggplot2)
library(data.table)
library(Biostrings)
library(gridExtra)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(spatialLIBD)
library(scater) # addPerCellQC
library(BiocParallel)
library(scran)
library(parallel)
# library(scCustomize)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

load required files
```{r}
hyp2 <- readRDS("processed-data/03-QC_filters/hypN10_umi210_gene126_chrm50_spotsweeped_lognorm_rotsNmirrors_071924.RDS")

## this retrieves clustering results from both the 10k-iteration-pass bayesspace runs AND the subset that were run at 60k iterations
bscl <- list.files("processed-data/06-BayesSpace",pattern=".txt",recursive = T,full.names = T)

bscls <- lapply(bscl,FUN=fread)
names(bscls) <- bscl
# replace file paths with informative short labels
names(bscls) <- gsub(names(bscls),pattern="^.*9-15-20-31_out\\/BSpace_(.*)\\.txt$",replacement="\\1")
names(bscls) <- gsub(names(bscls),pattern="^.*60kiter.*\\/BSpace_(.*)\\.txt$",replacement=paste0("\\1","_60kiter"))

## add one additional clustering result where we collapse the VMH and ARC domains into one cluster each. do this for the primary clustering of interest -- bayesspace60kiter k15 harmony-lambda=NA with nnsvg10. we don't really need to do this over and over since the collective VMH or ARC spots will be ~the same regardless of how many subdivisions of it we made via different k values
## VMH: 11,12; ARC 3,5
collapse <- copy(bscls[["k15_HARMONYlmbna_nnsvg10_60kiter"]])
setnames(collapse,2,"cl")
collapse[,cl:=as.character(cl)]
collapse[cl %in% c("11","12"),cl:="VMH"]
collapse[cl %in% c("3","5"),cl:="ARC"]

bscls[["k15_HARMONYlmbna_nnsvg10_60kiter_collapsed"]] <- collapse


```

```{r}
# extract gene annotation table to join back to results
tmprowdat <- as.data.table(rowData(hyp2))

## iterate through clustering results: assign current clustering result to the hyp2$label column, identify markers within those assignments, return marker test outputs, proceed to next assignment set 

# parallelize within individual calls to scran, otherwise we're cloning the whole spe over and over
bpparam <- MulticoreParam(workers=8)
register(bpparam)

i<-1
bs.markers <- list()
for (i in c(1:length(bscls))){
    y <- bscls[[i]]
    y <- as.data.frame(y)
    rownames(y) <- y$rn
    # safeguard against reordered rows
    y <- y[rownames(colData(hyp2)),]
    colnames(y)[2] <- "cl"
    y$cl <- paste0("X",y$cl)
    # row names as gene symbols for sanity
    colLabels(hyp2) <- as.factor(y$cl)
    rm(y)
    gc(full=T)
    
    bs.markers[[i]] <- scoreMarkers(hyp2,colLabels(hyp2),BPPARAM=bpparam)
    names(bs.markers)[i] <- names(bscls)[i]
}

```

### collapse to top 100 markers (for each metric) per measure and clusters per clustering run, then to one giganto table
```{r}
i<-1
for (i in c(1:length(bs.markers))){
    k<-1
    for (k in c(1:length(bs.markers[[i]]))){
        tmp <- as.data.frame(bs.markers[[i]]@listData[[k]])
        # gene ids are only in the rownames so hang onto those when converting to d.t.
        tmp <- as.data.table(tmp,keep.rownames=T)
        # top 100 by rank per metric
        tmp <- tmp[rank.logFC.cohen<=100|rank.AUC<=100|rank.logFC.detected<=100]
        # clustering info
        tmp[,cluster_set:=names(bs.markers)[i]]
        tmp[,cluster:=names(bs.markers[[i]])[k]]
        # add information from rowData so we have gene symbols
        tmp <- merge.data.table(tmp,tmprowdat[,.(gene_id,gene_name)],by.x="rn",by.y="gene_id")
        if(i==1&k==1){
            bs.markers.tab <- tmp
        }
        else{
            bs.markers.tab <- rbind(bs.markers.tab,tmp)
        }
        rm(tmp)
    }
    rm(k)
}
rm(i)

## put clustering info, gene info, rank columns first
setnames(bs.markers.tab,"rn","gene_id")
bmtnamesout <- c("cluster_set","cluster","gene_id","gene_name",colnames(bs.markers.tab)[!colnames(bs.markers.tab)%in%c("cluster_set","cluster","gene_id","gene_name")])
bs.markers.tab <- bs.markers.tab[,..bmtnamesout]

saveRDS(bs.markers.tab,"data/07-Marker_genes/01a-BSpace_allruns_top100_1vsAll-markers_perdomain_perrun.RDS")

# clean up to free memory for spatiallibd below
rm(bs.markers.tab,bs.markers,tmprowdat,i,bmtnamesout,bpparam)
gc(full=T)
```

### get additional marker stats using spatialLIBD::registration_wrapper (return "enrichment" analyses)
```{r}
# we can't use biocparallel in this function, so bplapply it across just a couple-three cores to avoid overloading the machine

bpparam <- MulticoreParam(workers=3)
register(bpparam)

slibdenrichments <- bplapply(bscls,BPPARAM=bpparam,function(x){
    y <- as.data.frame(x)
    rownames(y) <- y$rn
    # safeguard against reordered rows
    y <- y[colnames(hyp2),]
    colnames(y)[2] <- "cl"
    y$cl <- paste0("X",y$cl)
    # conditional operation for the collapsed-clusters analysis
    if(length(grep(y$cl,pattern="VMH",value=T))>0){
        intlevels <- gsub(unique(y$cl),pattern="X([[:digit:]]{1,2})",replacement="\\1")
        intlevels <- as.numeric(intlevels)
        intlevels <- intlevels[!is.na(intlevels)]
        colLabels(hyp2) <- factor(y$cl,levels=c("XVMH","XARC",paste0("X",intlevels)))
        rm(y)
        gc(full=T)
    }
    else{
        colLabels(hyp2) <- factor(y$cl,levels=paste0("X",c(1:length(unique(y$cl)))))
        rm(y)
        gc(full=T)
    }
    tmp <- registration_wrapper(hyp2,"label","sample_id",gene_ensembl="gene_id",gene_name="gene_name",min_ncells = 10)
    z <- as.data.table(tmp[["enrichment"]])
    return(z)
})
names(slibdenrichments) <- names(bscls)
rm(bpparam)
gc(full=T)


# save full outputs for each clustering run
saveRDS(slibdenrichments,"data/07-Marker_genes/01b-BSpace_allruns_spatialLIBD-regwrap-enrichment_full.RDS")

```
