---
title: "01-Plot Harmony-Walktrap Marker Genes"
author: "Bernie Mulvey"
date: "2023-05-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(ggplot2)
library(data.table)
library(Biostrings)
library(gridExtra)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(ggspavis)
library(scater) # addPerCellQC
# library(nnSVG)
library(BiocParallel)
library(scran)
library(parallel)
library(Polychrome)
# library(fasthplus)
library(scCustomize)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

# load required objs
```{r}
walktraps <- readRDS("analysis/data/H02-clustering/sampleBlock-hvg10-20_harmonyBrnumBlock-walktrap-SNNk5-10-15.RDS")

hyp2 <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_053123.RDS")

walktrap.markers <- readRDS("analysis/data/H03-marker_genes/sharmony_walktrapk5-15_markergenes.RDS")

```


### Extract top FDR gene(s) per cluster per cluster set
```{r}

i<-1
for (i in c(1:length(walktrap.markers))){
    k<-1
    for (k in c(1:length(walktrap.markers[[i]]@listData))){
        tmp <- walktrap.markers[[i]]@listData[[k]]
        tmp <- rownames(tmp[which(tmp$FDR==min(tmp$FDR)),])
        tmp2 <- rep(names(walktrap.markers)[i],times=length(tmp))
        tmp3 <- rep(names(walktrap.markers[[i]]@listData)[k],times=length(tmp))
        tmpres <- cbind(tmp,tmp2,tmp3)
        colnames(tmpres) <- c("gene","cluster_set","cluster")
        if(i==1&k==1){
            walktrap.markers.plt <- tmpres
        }
        else{
            walktrap.markers.plt <- rbind(walktrap.markers.plt,tmpres)
        }
        rm(tmp,tmp2,tmp3,tmpres)
    }
    rm(k)
}
rm(i)

walktrap.markers.plt <- as.data.table(as.data.frame(walktrap.markers.plt))
write.table(walktrap.markers.plt,"analysis/data/H03-marker_genes/topFDR_markers_perclust_perHarmonyClusterSet.txt",sep='\t',quote=F,row.names=F,col.names=T)
```

## need to chew over how to look at this data efficiently.
# marker names are gene symbols so rename rows accordingly
```{r}
rownames(hyp2) <- rowData(hyp2)$gene_name







```
