---
title: "01-scCoco query of mouse CCF regions for ABA-ISH expression of domain markers"
author: "Bernard Mulvey"
date: "2024-07-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(scCoco)
library(cocoframer)
require(colorout)
library(stringr)
library(orthogene)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc
library(parallelly)
options(parallelly.supportsMulticore.disableOn="")
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost="localhost")
```

```{r}
hypmark <- readRDS("processed-data/07-Marker_genes/01b-BSpace_allruns_spatialLIBD-regwrap-enrichment_full.RDS")

hypmark <- hypmark[grep(names(hypmark),pattern="HARMONYlmbna_nnsvg10_60kiter",value=T)]

## retrieve top 150 markers for each cluster from these four clustering runs -- the query space is allen atlas ISH which only covers a few thousand genes, and we want to map to regions with at least 50 of our genes assayed

markerqueries <- list()
i<-1
for (i in c(1:length(hypmark))){
    markerqueries[[i]] <- list()
    tmp <- copy(hypmark[[i]])
    msorth <- as.data.table(orthogene::convert_orthologs(gene_df = tmp,gene_input = "ensembl",gene_output = "columns",input_species = "human",output_species = "mouse",non121_strategy = "drop_both_species",drop_nonorths = TRUE))
    setnames(msorth,c("ens","mousesymbol"))
    tmp <- merge.data.table(tmp,msorth,by.x="ensembl",by.y="ens")
    spdoms <- grep(names(tmp),pattern="t_stat",value=T)
    spdoms <- gsub(spdoms,pattern="t_stat_(.*)",replacement="\\1")
    j <- 1
    for (j in c(1:length(spdoms))){
        setorderv(tmp,paste0("t_stat_",spdoms[j]),-1)
        # convert symbol to mouse symbol
        g <- tmp[1:150,mousesymbol]
        markerqueries[[i]][[j]] <- g
        names(markerqueries[[i]])[j] <- paste0(names(hypmark)[i],"_",spdoms[j])
        rm(g)
    }
    names(markerqueries)[i] <- names(hypmark)[i]
    rm(j,tmp,spdoms,msorth)
}
rm(i)
gc(full=T)

### fix names that have "XX" or "XARC" or "XVMH"
markerqueries <- lapply(markerqueries,function(x){
    names(x)<-gsub(names(x),pattern="XX",replacement="X")
    names(x)<-gsub(names(x),pattern="XVMH",replacement="VMH")
    names(x)<-gsub(names(x),pattern="XARC",replacement="ARC")
    return(x)
})

### swap in VMH/ARC identifiers for clusters in the k15 single cluster and k20, k31
names(markerqueries[[1]]) <- gsub (names(markerqueries[[1]]),pattern="X4",replacement="ARC.1")
names(markerqueries[[1]]) <- gsub (names(markerqueries[[1]]),pattern="X6",replacement="ARC.2")
names(markerqueries[[1]]) <- gsub (names(markerqueries[[1]]),pattern="X7",replacement="VMH.1")
names(markerqueries[[1]]) <- gsub (names(markerqueries[[1]]),pattern="X12",replacement="VMH.2")

### add the k20/k31 ARC and VMH cluster identifiers as used elsewhere
names(markerqueries[[2]]) <- gsub (names(markerqueries[[2]]),pattern="X2$",replacement="VMH20.1")
names(markerqueries[[2]]) <- gsub (names(markerqueries[[2]]),pattern="X3",replacement="VMH20.2")
names(markerqueries[[2]]) <- gsub (names(markerqueries[[2]]),pattern="X1$",replacement="ARC20.1")
names(markerqueries[[2]]) <- gsub (names(markerqueries[[2]]),pattern="X4",replacement="ARC20.2")

names(markerqueries[[3]]) <- gsub (names(markerqueries[[3]]),pattern="X6",replacement="VMH31.1")
names(markerqueries[[3]]) <- gsub (names(markerqueries[[3]]),pattern="X21",replacement="VMH31.2")
names(markerqueries[[3]]) <- gsub (names(markerqueries[[3]]),pattern="X25",replacement="VMH31.3")
names(markerqueries[[3]]) <- gsub (names(markerqueries[[3]]),pattern="X26",replacement="VMH31.4")
names(markerqueries[[3]]) <- gsub (names(markerqueries[[3]]),pattern="X31",replacement="VMH31.5")
names(markerqueries[[3]]) <- gsub (names(markerqueries[[3]]),pattern="X2$",replacement="ARC31.1")
names(markerqueries[[3]]) <- gsub (names(markerqueries[[3]]),pattern="X4",replacement="ARC31.2")
names(markerqueries[[3]]) <- gsub (names(markerqueries[[3]]),pattern="X11",replacement="ARC31.3")
names(markerqueries[[3]]) <- gsub (names(markerqueries[[3]]),pattern="X22",replacement="ARC31.4")
```

### run as iterative loop, timeouts tend to happen so simpler to get partial results back and restart loop midway

```{r}
### pull down some of this info locally to minimize queries during the actual run
test <- aba_ids(genes=unique(unlist(markerqueries)))
### CANNOT COMPLETE TESTS FOR A GIVEN CLUSTER SET DUE TO TIMEOUTS ###
### first attempt got through cluster set 1, resetting i to 2 ...

## the timeouts always appear to be with the step for getting CCF annotations, which per the sccoco docs are using cocoframer::get_mba_ontology() and passing that to cocoframer::flatten mba ontology. since get mba ontology targets the same file every time, we can download the former, run flatten on the latter, and then provide it to sccoco as a "cached version" using its mba_ontology_flatten argument. i have downloaded this file and stored it in processed data as 01a.
## manually run the get_mba_ontology step, then pass that into theflatten step. save the flatten output to tsv to pass to scoco.
temp <- tempfile()
download.file("http://api.brain-map.org/api/v2/structure_graph_download/1.json",temp)
raw_ontology <- jsonlite::fromJSON(temp)[["msg"]]
# use the cocoframer flatten mba ontology and save this output as tsv
ontout <- cocoframer::flatten_mba_ontology(raw_ontology)

fwrite(ontout,"processed-data/10-Spatial Registration/01a-ABA_msbrn_ontolflatten_for_sccoco.tsv",sep='\t',quote=F)

# cocoqueryres <- list()
i<-2
for(i in c(2:length(markerqueries))){
    cocoqueryres[[i]] <- scCoco::findRegions_genesets(gene_set = markerqueries[[i]],min_ids = 50,target_structure_id=1097,mba_ontology_flatten="processed-data/10-Spatial Registration/01a_ABA_msbrn_ontolflatten_for_sccoco.tsv")
    names(cocoqueryres)[i] <- names(markerqueries)[i]
}
```

### save
```{r}
saveRDS(cocoqueryres,"processed-data/10-Spatial Registration/01-scCoco query of top 150 markers per k15-20-31-collapsedK15 domain in ABA ms hyp CCF areas.RDS")
```

### session info
```{r}
sessionInfo()
sessioninfo::session_info()
```
