---
title: "01-Plot clusters on dimensionality reductions"
author: "Bernard Mulvey"
date: "2024-07-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")

## change write.table to output a TSV without quotes or rownames by default
library(default)
default(write.table) <- list(row.names=F,col.names=T,sep='\t',quote=F)

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc
library(parallelly)
options(parallelly.supportsMulticore.disableOn="")
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost="localhost")

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

### load reduced dim slot with the PCA, UMAP, harmony dimreds, and mnn dimreds for the feature sets. load bayesspace cluster assignments.
```{r}
hyp2dimreds <- readRDS("processed-data/04-feature_selection/02-hypfiltered_4featureset-pca-umap-harmonydefault-harmonylambdanull-mnn30_reducedDim_slot.RDS")

bs_clusts <- list.files("processed-data/06-BayesSpace/01-bayesspace60kiter_k15-20-31_out",pattern=".txt",full.names=T,recursive = F)
```

Plot on feature-set-matched dimreds

```{r}
i <- 1
for (i in c(1:length(bs_clusts))) {
    # get feature set (hvg20, svg10, svg20)
    curfeats <- gsub(bs_clusts[i],pattern="^.*k15-20-31_out/BSpace_.*_([[:alnum:]]{5,8})\\.txt$",replacement="\\1")
    
    # get batch correction method short name
    curbatcor <- gsub(bs_clusts[i],pattern="^.*k15-20-31_out/BSpace_k.._(.*)_[[:alnum:]]{5,8}\\.txt$",replacement="\\1")
    
    # get corresponding dimred slots (and some that don't correspond)
    curdimrs <- hyp2dimreds[grep(curfeats,names(hyp2dimreds))]
    # subset to do those that do correspond (PCA, plain UMAP, and the batch method)
    keepdimrs <- c(paste0(c("PCA_","UMAP_"),curfeats),paste0(curbatcor,"_",curfeats))
    keepdimrs <- unlist(lapply(keepdimrs,FUN=function(x){grep(names(curdimrs),pattern=x,value=T)}))
    
    curdimrs <- curdimrs[keepdimrs]
    
    ## read in cluster assignments
    curclusts <- fread(bs_clusts[i])
    setnames(curclusts,2,"cl")
    curclusts[,cl:=paste0("X",cl)]
    
    ####################
    ## LEFT OFF HERE ###
    ####################
    
    ### since clustering result files were saved with their parent dimred in the output file name, we can use the cluster file name to match/recreate the dimreds to plot onto. also grab the specified k value from filename for reference.
    
    bsk <- gsub(bs_clusts[i],pattern="^.*_out/BSpa.*_k(.*)_.*_.*\\.txt",replacement="\\1")
    drandfeats <- gsub(bs_clusts[i],pattern="^.*_out/BSpa.*_k.*_(.*_.*)\\.txt",replacement="\\1")
    feats <- gsub(drandfeats,pattern="^.*_(.*)$",replacement="\\1")
    
    # plot on the feature set's uncorrected dimreds, and that feature set's corresponding batch correction method's dimreds
    plotdrs <- c(paste0(c("PCA_","UMAP_"),feats),drandfeats)
    
    # for MNN dimreds, also include the corresponding UMAP-of-MNN
    if(length(grep(drandfeats,pattern="mnn30",value=T))>0){plotdrs <- plotdrs <- c(plotdrs,paste0(drandfeats,"_UMAP"))}
    
    j <- 1
    for (j in c(1:length(plotdrs))){
        if(length(grep(plotdrs[j],pattern="UMAP",value=T))>0){
            zq <- rbind(c(1,2))
        }
        else{
            zq <- rbind(c(1,2),c(1,3),c(2,3))
        }
    # iterate thru dimension pairs
        m <- 1
        for (m in c(1:nrow(zq))){
            z <- zq[m,1]
            q <- zq[m,2]
            pltdat <- cbind(reducedDims(hyp2)[[plotdrs[j]]][,c(z,q)],as.character(hyp2$label))
            
            pltdat <- as.data.table(pltdat)
            setnames(pltdat,c(paste0(plotdrs[j],paste0("_Dim",z)),paste0(plotdrs[j],paste0("_Dim",q)),paste0(drandfeats,"_k",bsk)))
            xvar <- names(pltdat)[1]
            yvar <- names(pltdat)[2]
            colvar <- names(pltdat)[3]
        
            set(pltdat,j=xvar,value=as.numeric(pltdat[,get(xvar)]))
            set(pltdat,j=yvar,value=as.numeric(pltdat[,get(yvar)]))
            set(pltdat,j=colvar,value=factor(pltdat[,get(colvar)],levels=paste0("X",c(1:length(unique(pltdat[,get(colvar)]))))))
        
            plt <- ggplot(pltdat,aes(x=.data[[xvar]],y=.data[[yvar]],col=.data[[colvar]]))+
                geom_point()+
                ggtitle(paste0(plotdrs[j]," dims ",z, " and ",
                               q,"\n","BayesSpace k = ",bsk))
        
            pdf(paste0("plots/06-BayesSpace/01-Clusters on Dim Reducs/",drandfeats,"-Bspc-k",bsk,"_plotted-on_",plotdrs[j],"dims",q,"and",z,".pdf"),width = 10,height = 8)
            print(plt)
            dev.off()
            rm(z,q,pltdat,xvar,yvar)
        }
    }
    rm(drandfeats,feats,bsk)
}

```

