---
title: "sanity check - leave one out DE"
author: "Bernard Mulvey"
date: "2023-11-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(scater)
library(scran)
library(edgeR)
library(limma)

library(gridExtra)
library(magrittr)

```

load SPE, add bayesspace clusters
```{r}
hyp2.vmh <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_D07-075_B1 crop 070223.RDS") 

# change/ensure colnames/colData's rownames == colData()$keys
colnames(hyp2.vmh) <- colData(hyp2.vmh)$key

## add demographics
demos <- fread("raw-data/demos.txt")
tmpcd <- as.data.table(colData(hyp2.vmh),keep.rownames=T)
tmpcd <- merge.data.table(tmpcd,demos,by.x="brnum",by.y="BrNum")
tmpcd <- as.data.frame(tmpcd)
rownames(tmpcd) <- tmpcd$rn
tmpcd <- tmpcd[colnames(hyp2.vmh),]

colData(hyp2.vmh) <- DataFrame(tmpcd) 
stopifnot(identical(colnames(hyp2.vmh),rownames(colData(hyp2.vmh))))

bscl <- fread("analysis/data/spe_053123/H02-clustering/03-bs_harmony_hvg1020_nnsvg1020_9-15-20-31_out/BSpace_Harmony_nnsvg10pctile_15.txt")
setnames(bscl,2,"clus")
bscl <- DataFrame(bscl)
rownames(bscl) <- bscl$rn
bscl <- bscl[colnames(hyp2.vmh),]
bscl$clus <- paste0("X",bscl$clus)
colLabels(hyp2.vmh) <- as.factor(bscl$clus)
rm(bscl)

### extract rowData so we can append gene symbols at the end
gdat <- as.data.table(rowData(hyp2.vmh),keep.rownames=T)

unique(hyp2.vmh$brnum)
## drop 5993
hyp2.vmh <- hyp2.vmh[,hyp2.vmh$brnum!="Br5993"]
```

### using dreamlet
```{r}
library(BiocParallel)
sbp <- MulticoreParam(8)

### and for random effect model
ag <- dreamlet::aggregateToPseudoBulk(hyp2.vmh,sample_id="sample_id",cluster_id = "label",BPPARAM = sbp)

dl.rf <- dreamlet::processAssays(ag,min.cells = 10,min.count = 10,min.samples = 4,min.prop = 0.4,normalize.method = "TMM",useCountsWeights = T,BPPARAM = sbp,formula = ~Sex+(1|brnum))

dl.rf <- dreamlet::dreamlet(dl.rf,formula = ~Sex+(1|brnum),BPPARAM = sbp)

dl.rf.res <- dreamlet::topTable(dl.rf,coef="SexM",number=Inf,adjust.method ="BH")

dl.rf.res <- as.data.table(dl.rf.res,keep.rownames=T)

# saveRDS(dl.rf.res,"~/Desktop/drop5993.RDS")
```

```{r}
fullRFres <- readRDS("analysis/data/spe_053123/H07-Outside Dataset Analyses and Comparisons/spatialHYP_dreamletSexDE_brnum-as-random-effect-inDEmodel.RDS")

fullRFres <- as.data.table(fullRFres)

setnames(fullRFres,c(4:10),paste0(names(fullRFres)[4:10],"_full"))

compareres <- merge.data.table(fullRFres[,.(ID,assay,P.Value_full,adj.P.Val_full,logFC_full)],dl.rf.res[,.(ID,assay,P.Value,adj.P.Val,logFC)],by=c("ID","assay"))

```

```{r}
i<-1
for (i in c(1:15)){
  curdom <- paste0("X",i)
  curdat <- copy(dl.rf.res)[assay==curdom]
  setorder(curdat,-logFC)
  write.table(curdat[,.(ID,logFC)],paste0("~/Desktop/sanitygsea/",curdom,".rnk"),sep='\t',quote=F,row.names=F,col.names=F)
  rm(curdom,curdat)
}
```

```{r}
i <- 5
for (i in c(5,6,8,9,13)){
    clus <- paste0("x",i)
    mup <- list.files(
                           paste0(
                           "~/Desktop/sanitygsea/", clus, "_drop5993.GseaPreranked/"),pattern="gsea_report_for_na_pos.*\\.tsv",full.names=T)
    fup <- list.files(
                      paste0(
                      "~/Desktop/sanitygsea/", clus, "_drop5993.GseaPreranked/"),pattern="gsea_report_for_na_neg.*\\.tsv",full.names = T)


    mup <- fread(mup)
    fup <- fread(fup)
    mup <- mup[,c(1,4:11)]
    fup <- fup[,c(1,4:11)]
    mup[,spdomain:=clus]
    fup[,spdomain:=clus]
    mup[,direction:="male_up"]
    fup[,direction:="female_up"]
    setnames(mup,c(5:9),c("P.Value","FDR_qval","FWER_pval","rankAtMax","leading_edge"))
    setnames(fup,c(5:9),c("P.Value","FDR_qval","FWER_pval","rankAtMax","leading_edge"))
    
    
    # join
    if (i==5){sanitygse <- rbind(mup,fup)}
    else{sanitygse <- rbind(sanitygse,mup,fup)}
    setorder(sanitygse,NES)
    
    
    rm(mup,fup,clus)
}
rm(i)

maxhitlist.sanity <- list()
i <- 5
for (i in c(5,6,8,9,13)){
    clus <- paste0("x",i)
    tmpm <- sanitygse[spdomain==clus&direction=="male_up"&NES>0]
    tmpf <- sanitygse[spdomain==clus&direction=="female_up"&NES<0]
    tmpm <- tmpm[NAME %in% grep(NAME,pattern="MANNO_|FAN_|TRAVAGLINI|DURANTE|DESCARTES|RUBENSTEIN|CUI_|AIZARANI_|GAO_",value=T,invert=T)]
    tmpf <- tmpf[NAME %in% grep(NAME,pattern="MANNO_|DURANTE|DESCARTES|RUBENSTEINMANNO_|FAN_|TRAVAGLINI|DURANTE|DESCARTES|RUBENSTEIN|CUI_|AIZARANI_|GAO_",value=T,invert=T)]
    tmpf[,NES:=-1*NES]
    
    tmp <- rbind(tmpf,tmpm)
    setorder(tmp,-NES)
    maxhitlist.sanity[[length(maxhitlist.sanity)+1]] <- rbind(unique(tmp)[direction=="male_up"][c(1:20)],unique(tmp)[direction=="female_up"][c(1:20)])
    names(maxhitlist.sanity)[length(maxhitlist.sanity)] <- clus
    rm(tmp,clus)
}
```

