---
title: "scCoco-Query mouse CCF regions for ISH expression of marker gene sets"
author: "Bernard Mulvey"
date: "2023-11-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
require(colorout)
library(scCoco)
library(BiocParallel)
source("~/.R/calc_tau_for_cellOrTissueSpecificity_metric.R")
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(scCoco)

## change write.table to output a TSV without quotes or rownames by default
library(default)
default(write.table) <- list(row.names=F,col.names=T,sep='\t',quote=F)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

#### scCoco testing as our data to plot, during course downtime ####
testing just for a couple VMH clusters::
```{r}
hypmark <- readRDS("~/Desktop/KM Lab/local_hthspatial/EDA and Preliminary Dataset/data/spe_053123/H03-marker_genes/04-BSpace_HVG1020-SVG1020_q9-15-20-31_sLIBD-regwrapper-enrichment-res.RDS")

hypmark <- hypmark[[9]]

setorderv(hypmark,"logFC_X5",-1)
geneset <- hypmark[1:100,gene]
geneset2 <- setorderv(hypmark,"logFC_X6",-1)
geneset2 <- hypmark[1:100,gene]
geneset <- stringr::str_to_title(geneset)
geneset2 <- stringr::str_to_title(geneset2)

sets <- list(geneset,geneset2)
names(sets) <- c("X5","X6")

# brain-wide
test <- scCoco::findRegions_genesets(gene_set = sets)
# query hypothal only
test2 <- scCoco::findRegions_genesets(gene_set=sets,target_structure_id=1097)
```

```{r}
sbp <- MulticoreParam(8)

### systematically examine all markers in hyp
clusts <- paste0("X",c(1:15))
msabaquerytophundo <- bplapply(clusts,BPPARAM=sbp,FUN=function(x){
  tmp <- copy(hypmark)
  setorderv(tmp,paste0("logFC_",x),-1)
  g <- stringr::str_to_title(tmp[1:150,gene])
  return(g)
})
names(msabaquerytophundo) <- clusts

hypmkaba <- scCoco::findRegions_genesets(msabaquerytophundo,min_ids = 50,structure_id=1097)
saveRDS(hypmkaba,"~/Desktop/KM Lab/local_hthspatial/EDA and Preliminary Dataset/EDA/scCoco query for ISH concordance in mouse ABA-CCF framework-top 150 hyp marker genes by logFC.RDS")
```