---
title: "02-Plot top nnSVG, HVG genes and misc expected markers, NO batch correction, and misc expected markers "
author: "Bernie Mulvey"
date: "2023-05-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(ggplot2)
library(data.table)
library(Biostrings)
library(gridExtra)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(ggspavis)
library(scater) # addPerCellQC
# library(nnSVG)
library(BiocParallel)
library(scran)
library(parallel)
library(Polychrome)
# library(fasthplus)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

### load filtered sge and feature sets
```{r}
hyp2 <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm.RDS")
hyp2.vgs.list <- readRDS("analysis/data/01-feature_selection/nnSVG_HVG_and_combo_featurelists.RDS")

genesofinterest <- c("NR5A1","ESR1","BDNF","XIST","OXT","HCRT","NPY","AGRP","POMC","CARPT","AVP","GRHR","PENK","VIP","SIM1","TBX3","RGS16")
goi.ens <- rownames(hyp2)[which(rowData(hyp2)$gene_name %in% genesofinterest)]
hyp2.vgs.list[[8]] <- goi.ens
names(hyp2.vgs.list)[8] <- "apriori"
rm(goi.ens,genesofinterest)
# lists 1 and 2 are the same at the top end -- list 2 just runs 1800 genes further down the rank list

### NOT WORKING ###
# Error in `combine_vars()`:
# ! At least one layer must contain all faceting variables: `sample_id`
# ✖ Plot is missing `sample_id`
# ✖ Layer 1 is missing `sample_id`
i<-2
for (i in c(2,3,8)){
    k<-1
    if (i<=7){
        genes <- hyp2.vgs.list[[i]][1:20]
    }
    else{genes<-hyp2.vgs.list[[i]]}
    for (k in c(1:length(genes))){
        genesymb <- rowData(hyp2)[paste0(genes[k]),"gene_name"]
        colLabels(hyp2) <- logcounts(hyp2)[genes[k],]
        plt <- plotSpots(hyp2,annotate="label")+
            ggtitle(paste0(names(hyp2.vgs.list)[i],"_gene number_",k,"-",genesymb))
        pdf(paste0("plots/01-feature_selection/",names(hyp2.vgs.list)[i],"_gene number_",k,"-",genesymb,".pdf"),width=10,height=10)
        print(plt)
        dev.off()
        rm(genesymb,plt)
    }
    rm(k,genes)
}



```
