---
title: "02-BSpace hvg, svg q9-15-20-31 clusterings marker genes"
author: "Bernie Mulvey"
date: "2023-06-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(ggplot2)
library(data.table)
library(Biostrings)
library(gridExtra)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(ggspavis)
library(scater) # addPerCellQC
library(BiocParallel)
library(scran)
library(parallel)
# library(scCustomize)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

load required files
```{r}
hyp2 <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_053123.RDS")
rownames(colData(hyp2)) <- colData(hyp2)$key

bscl <- list.files("analysis/data/H02-clustering/bs_harmony_hvg1020_nnsvg1020_9-15-20-31_out",pattern=".txt",full.names = T)

bscls <- lapply(bscl,FUN=fread)
names(bscls) <- gsub(bscl,pattern="^.*9-15-20-31_out\\/BSpace_Harmony_(.*)\\.txt$",replacement="\\1")
```

## Use scran::scoreMarkers(...,full.stats=T) to get results compatabile w finding markers to separate highly related clusters e.g. nnsvg10_31 clusters 4 5 11 17
## following OSCA: http://bioconductor.org/books/3.17/OSCA.basic/marker-detection.html#obtaining-the-full-effects


```{r}
bpparam <- MulticoreParam(workers=8)
register(bpparam)
bs.markers <- bplapply(bscls,BPPARAM=bpparam,FUN=function(x){
    y <- as.data.frame(x)
    rownames(y) <- y$rn
    # safeguard against reordered rows
    if((sum(rownames(colData(hyp2))==rownames(y)))!=ncol(hyp2)){
        y <- y[rownames(colData(hyp2)),]
    }
    # row names as gene symbols for sanity
    rownames(hyp2) <- rowData(hyp2)$gene_name
    colLabels(hyp2) <- factor(y[,2])
    rm(y)
    gc(full=T)
    
    multistat <- scoreMarkers(hyp2,colLabels(hyp2),full.stats=T)
})
names(bs.markers) <- names(bscls)

saveRDS(bs.markers,"analysis/data/H03-marker_genes/BSpace_HVG1020-SVG1020_q9-15-20-31_findmarkers_out.RDS")

```

