---
title: "SF-all_xARCxVMH_cluster_sexDEvolcanos"
output: html_document
date: "2024-11-09"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(ggplot2)
library(gridExtra)
library(ggtext)


## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
##

## ggplot defaults
theme_set(theme_bw()+theme(axis.text.x = element_text(size = 9), axis.title.x = element_text(size = 8), axis.text.y = element_text(size = 8), axis.title.y = element_text(size =9), plot.title = element_markdown(size = 11,hjust=0.5), strip.text = element_text(size=11), legend.text = element_text(size=8), legend.title = element_text(size=9,hjust=0.5)))

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace("datasets")
```

```{r}
# de tables
vxen <- fread("xenium_HYP/processed-data/08_VMH-ARC cell type sex DE within domains/02b-4ARCtypesmoothed_withinVMH_celltypeSexDE.txt")
axen <- fread("xenium_HYP/processed-data/08_VMH-ARC cell type sex DE within domains/02a-4ARCtypesmoothed_withinARC_celltypeSexDE.txt")

# cluster id-formal id lookup table
clust <- fread("manuscript_plot_code/xARCxVMH_cluster_detailedlabs_andplotformatnames.txt")
stopifnot(nrow(clust)==length(unique(c(axen[cluster_id %in% clust$cluster_id,cluster_id],vxen[cluster_id %in% clust$cluster_id,cluster_id]))))

# add manuscript cluster labels
vxen <- merge.data.table(vxen,clust[subclus_domain=="VMH"],by="cluster_id")
axen <- merge.data.table(axen,clust[subclus_domain=="ARC"],by="cluster_id")
detab <- rbind(vxen,axen)

detab[,plotclusname2:=paste0("x",subclus_domain," ",plotclusname)]
detab[,plotclusname2:=gsub(plotclusname2,pattern="xVMH xVMH",replacement="xVMH")]

## cluster palette
pals <- readRDS("manuscript_plot_code/domain_and_xencluster_palettes_CHECKPALNAMESBEFOREUS.RDS")
vpal <- pals$XenVMH
apal <- pals$XenARC
jtpal <- c(vpal,apal)

names(jtpal) <- unique(detab[,.(plotclusname,plotclusname2)])[match(names(jtpal),plotclusname),plotclusname2]

detab[,plotclusname2:=factor(plotclusname2,levels=c(unique(detab[subclus_domain=="VMH",plotclusname2]),unique(detab[subclus_domain=="ARC",plotclusname2])))]
```

## volcano plots
```{r}
plts <- lapply(levels(detab$plotclusname2),function(clus){
    # determine FDR 0.05 equivalent p-value
    curde <- detab[plotclusname2==clus]
    if(nrow(curde[FDR<0.05])==0){
        p_fdr05 <- 0.05*(min(curde$P.Value)/min(curde$FDR))
    } else{
        p_fdr05 <- median(c(min(curde[FDR>0.05,P.Value]), max(curde[FDR<0.05,P.Value])))
    }
    p <- ggplot(curde,aes(x=logFC_MvF,y=-log10(P.Value),col=plotclusname2))+
        geom_point(alpha=0.7,size=0.5)+
        geom_hline(yintercept=-log10(0.05),linetype=2,color="black",linewidth=0.5)+
        geom_hline(yintercept=-log10(p_fdr05),linetype=2,color="red",linewidth=0.5)+
        theme()+
        labs(title=clus,x="log2FC M:F\n( >0 --> Higher in Male)",y="-log10(P-value)")+
        scale_color_manual(values=jtpal)+
        scale_x_continuous(limits=c(-max(abs(curde$logFC)),max(abs(curde$logFC))))+
        theme(plot.title = element_markdown(size = 11,hjust=0.5),legend.position="none")
})

pdf("manuscript_plots/Supplemental/SF-all_xARCxVMH_cluster_sexDEvolcanos.pdf",width=8.5,height=11)
do.call("grid.arrange",c(plts,nrow=3))
dev.off()














```