---
title: "SF-ESR1-KISS1-TAC3_coloc_br1225smfishanalysis"
author: "Bernie Mulvey"
date: "2024-11-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(ggplot2)
library(ggtext)
library(readxl)
## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
##

## ggplot defaults
theme_set(theme_bw()+theme(axis.text.x = element_text(size = 9), axis.title.x = element_text(size = 8), axis.text.y = element_text(size = 8), axis.title.y = element_text(size =9), plot.title = element_markdown(size = 11,hjust=0.5), strip.text = element_text(size=11), legend.text = element_text(size=8), legend.title = element_text(size=9,hjust=0.5)))

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace("datasets")
```

```{r}
cellq <- read_xlsx("Br1225_ESR1-TAC3-KISS1_smfish_analysis/processed-data/04-HYP1225_selected_Three_Clusters.xlsx")
cellq <- as.data.table(cellq)
setnames(cellq,2,"n")

cellq[,phenotype:=gsub(phenotype,pattern="520",replacement="*KISS1*")]
cellq[,phenotype:=gsub(phenotype,pattern="570",replacement="*ESR1*")]
cellq[,phenotype:=gsub(phenotype,pattern="690",replacement="*TAC3*")]
cellq[,phenotype:=gsub(phenotype,pattern="\\+",replacement="\\+ ")]
cellq[,phenotype:=gsub(phenotype,pattern="\\-",replacement="\\- ")]
cellq[,phenotype:=gsub(phenotype,pattern=" $",replacement="")]

# don't show triple negatives
cellq <- cellq[phenotype!="*KISS1*- *ESR1*- *TAC3*-"]

cellq[,prop:=n/sum(n)]


## show KISS1+ESR1+TAC3+ and KISS- ESR1+ TAC3+ at the top
levs <- c(unique(cellq[!(unique(cellq$phenotype) %in% c("*KISS1*+ *ESR1*+ *TAC3*+","*KISS1*- *ESR1*+ *TAC3*+")),phenotype]),"*KISS1*- *ESR1*+ *TAC3*+","*KISS1*+ *ESR1*+ *TAC3*+")
cellq[,Phenotype:=factor(phenotype,levels=levs)]

pdf("manuscript_plots/Supplemental/SF-ESR-KISS-TAC_20xsmfish_and_cellquants/ESR-KISS-TAC_smfish_cellquants.pdf",width=4,height=5)
ggplot(cellq,aes(x=prop,y=Phenotype))+
    geom_col(position="dodge")+
    labs(fill="Replicate",x="Proportion of Cells",y="smFISH Cell Phenotype")+
    theme(axis.text.y=element_markdown(size=8),axis.title.y=element_text(size=9),axis.text.x=element_text(size=8),axis.title.x=element_text(size=9))
dev.off()







```