---
title: "SF-possible tanycytes"
output: html_document
date: "2024-11-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())
library(data.table) # Preferred data manipulation package
library(ggplot2) # Dependency for several plotting functions
library(ggtext) # more character types in ggplots
library(ggrastr) # avoid making raster images one can't even open
library(SpatialExperiment) # Visium data framework
library(SpatialFeatureExperiment) # Xenium data framework
library(spatialLIBD) # one option for plotting cluster assignments, but breaks when the in-tissue portion of a visium area is very un-square.
library(escheR) # alternative spotplotting function, at least for visium
library(viridis) # palettes
library(Polychrome) # better palettes
library(ggstance) # for y axis dodge
require(colorout) # Utility for RStudio
library(sf) # define the polygonal boundaries of xenium domains
ColorOut()

## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
##

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc. seemed to need this a couple times, but otherwise havent so its here as a preventative measure. part of this is adding the line 
# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
# to Renviron.site. see e.g. top response on https://stackoverflow.com/questions/73638290/python-on-mac-is-it-safe-to-set-objc-disable-initialize-fork-safety-yes-globall 
library(parallelly)
options(parallelly.supportsMulticore.disableOn="")
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost="localhost")


## ggplot defaults
theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace("datasets")
```

```{r}
hypx <- readRDS("xenium_HYP/processed-data/05_Banksy_M0lam0_res2_multisamp/01-sfe-in_staggered-coords_genetarg-only_NONlog-norm.RDS")

bksmooth <- fread("xenium_HYP/processed-data/07_Domains-subdomains_by_knnSmoothing_Banksytypes/03b-ARCVMHdomains_2stepsmooth_VMH-k10-0.2-VMH-k200-0.2_ARC-k50-0.1_ARC-k500-0.5.txt") ## xenium domain assignments after smoothing, by xenium cell

## but drop discarded cell clusters, too
bkcl <- fread("xenium_HYP/processed-data/05_Banksy_M0lam0_res2_multisamp/01-BanksyClusts_M0lam0_leiden_multisamp.txt")
setnames(bkcl,2,"cl")

bkanno <- fread("xenium_HYP/processed-data/05_Banksy_M0lam0_res2_multisamp/02-M0l0kg6_topClusMarkers_celltypes_annotated.txt")

## drop sample-specific clusters, append cluster annotations 
bkanno <- unique(bkanno[,.(clus,bjm_annot)])
bkanno <- bkanno[bjm_annot!="DISCARD"&bjm_annot!="VMH_4_DISCARD"]

## convert ARC_1..etc to more descriptive cluster IDs defined based on ARC/VMH specific cluster marker analyses
arcvmhanno <- fread("manuscript_plot_code/xARCxVMH_cluster_detailedlabs_andplotformatnames.txt")

## append these to the other annots and replace bjm_annot with the ARC/VMH cell type labels where applicable
bkanno <- merge.data.table(bkanno,arcvmhanno,by="bjm_annot",all.x=T)
bkanno[!is.na(plotclusname),bjm_annot:=plotclusname]

## this drops rows that were assigned one of the discarded types (ie no longer in the cell type annotations)
bkcl <- merge.data.table(bkcl,bkanno,by.x="cl",by.y="clus")
## and now we can drop excluded clusters from xenium spe
hypx <- hypx[,colnames(hypx) %in% bkcl$rn]

## append cluster annots to xenium spe
bkcl <- DataFrame(bkcl,row.names=bkcl$rn)[colnames(hypx),]
bkcl$rn <- NULL
hypx$banksyclus <- bkcl$bjm_annot

## assign the domain labels to the xenium cells
bksmooth[dualVMHARC4=="other",dualVMHARC4:="Other"]
bksmooth <- DataFrame(bksmooth,row.names=bksmooth$rn)[colnames(hypx),]
hypx$dom <- bksmooth$dualVMHARC4

## load manuscript sample ids
mscriptids <- fread("standardized_sampleids_for_plotting.txt")
```

## custom domain palette for this supp fig:

```{r}
pal <- c("#343434","#979797","#ff7f0e","#1f77b4","#2ca02c","#cdcdcd")
names(pal) <- c("VMH","ARC",paste0("Tanycyte_",1:3),"Other")

samps <- unique(hypx$sample_id)
samps <- lapply(samps,FUN=function(s){hypx[,hypx$sample_id==s]})
rm(hypx)
gc()

sizescale <- c(0.1,0.2,0.175,0.3,0.3,0.3)
names(sizescale) <- c("Other","VMH","ARC",paste0("Tanycyte_",1:3))
library(parallel)
plts <- mclapply(samps,mc.cores=8,FUN=function(s){
    tmpdat <- cbind(as.data.table(colData(s)),as.data.table(spatialCoords(s)))
    tmpdat[dom %in% c("VMH","ARC"),banksyclus:=dom]
    tmpdat[!(banksyclus %in% names(pal)),banksyclus:="Other"]
    mid <- mscriptids[sample_id==unique(tmpdat$sample_id),manuscript_id]
    p <- ggplot(tmpdat,aes(x=sdimx,y=sdimy,col=banksyclus,size=banksyclus))+
        scale_color_manual(values=pal)+
        guides(color=guide_legend(override.aes = list(size=3)),size="none")+
        theme(axis.text.x=element_blank(),
              axis.text.y=element_blank(),
              axis.title.x=element_blank(),
              axis.title.y=element_blank(),
              plot.title = element_text(size=8),
              axis.ticks=element_blank(),
              panel.grid=element_blank())+
        ggtitle(mid)+
        scale_size_manual(values=sizescale)+
        rasterize(geom_point(stroke = 0),layers="Point",dpi=900,dev="cairo_png")

   
    return(p)
})


## grab legend from one plot to save separately
# helper function to extract a legend and pipe back to a diff plot: from https://statisticsglobe.com/add-common-legend-to-combined-ggplot2-plots-in-r/#example-2-add-shared-legend-to-ggplot2-plots-using-gridextra-package 
extract_legend <- function(my_ggp) {
  step1 <- ggplot_gtable(ggplot_build(my_ggp))
  step2 <- which(sapply(step1$grobs, function(x) x$name) == "guide-box")
  step3 <- step1$grobs[[step2]]
  return(step3)
}

leg <- extract_legend(plts[[1]])
dev.off()

# save legend to drop in with illustrator
pdf("manuscript_plots/Supplemental/SF-PutativeTanycyteslegend.pdf")
do.call("grid.arrange",list(arrangeGrob(leg)))
dev.off()
####

## remove legend from plots
plts <- lapply(plts,FUN=function(p){
    q <- p+guides(color="none",size="none")
    return(q)
})

## save cell type plots, annotate areas of possible tanycytes 
pdf("manuscript_plots/Supplemental/SF-PutativeTanycytes.pdf",height=11,width=8)
do.call("grid.arrange",plts)
dev.off()



```
