---
title: "SF-vVMH_vARC_marker_msigdbGSEA"
output: html_document
date: "2024-10-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table) # Preferred data manipulation package
library(ggplot2) # Dependency for several plotting functions
library(viridis) # palettes

## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
##


## ggplot defaults
theme_set(theme_bw()+theme(axis.text.x = element_text(size = 10), axis.title.x = element_text(size = 11), axis.text.y = element_text(size = 10), axis.title.y = element_text(size =11), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=10), legend.text = element_text(size=9), legend.title = element_text(size=10,hjust=0.5)))

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace("datasets")
```

Visium marker GSEA for VMH, ARC
### msigdb GSEA for arc and vmh ###
```{r}
pal <- readRDS("manuscript_plot_code/domain_and_xencluster_palettes_CHECKPALNAMESBEFOREUS.RDS")
pal <- pal[[1]][c("VMH","ARC")]


mkres <- readRDS("spatial_HYP/processed-data/11-GSEA/01a-Marker msigdb_1,2,3,5,6,8 GSEA svg10-hmnyLmdaNA_BS60k-k15-k20-k31-k15clpsd.RDS")

mkres <- mkres[c("k15_HARMONYlmbna_nnsvg10_60kiter_collapsed_XARC","k15_HARMONYlmbna_nnsvg10_60kiter_collapsed_XVMH")]
mkres <- lapply(mkres,FUN=function(x){
x[,spdom:=gsub(spdom,pattern="k15_HARMONYlmbna_nnsvg10_60kiter_collapsed_X(.*)",replacement="\\1")]})

pltdat <- mkres[["k15_HARMONYlmbna_nnsvg10_60kiter_collapsed_XVMH"]][pathway %in% c(
   "GOCC_GLUTAMATERGIC_SYNAPSE",
   "GOCC_GABA_ERGIC_SYNAPSE",
   "HP_HYPERACTIVITY",
   "HP_ABNORMAL_AGGRESSIVE_IMPULSIVE_OR_VIOLENT_BEHAVIOR",
   "GOBP_FEEDING_BEHAVIOR",
   "WP_KISSPEPTINKISSPEPTIN_RECEPTOR_SYSTEM_IN_THE_OVARY",
   "KEGG_LONG_TERM_POTENTIATION",
   "GOMF_HORMONE_ACTIVITY",
   "GOBP_AXONEME_ASSEMBLY",
   "GOCC_CILIARY_PLASM",
   "GOBP_MOTILE_CILIUM_ASSEMBLY",
   "GOCC_CILIARY_TRANSITION_ZONE",
   "HP_ABSENCE_OF_SECONDARY_SEX_CHARACTERISTICS",
   "GOBP_REGULATION_OF_INSULIN_SECRETION",
   "GOBP_NEUROPEPTIDE_SIGNALING_PATHWAY")]
pltdat <- rbind(pltdat,mkres[["k15_HARMONYlmbna_nnsvg10_60kiter_collapsed_XARC"]][pathway %in% c(
   #"GOCC_GLUTAMATERGIC_SYNAPSE",
   "GOCC_GABA_ERGIC_SYNAPSE",
   "HP_HYPERACTIVITY",
   "HP_ABNORMAL_AGGRESSIVE_IMPULSIVE_OR_VIOLENT_BEHAVIOR",
   "GOBP_FEEDING_BEHAVIOR",
   "WP_KISSPEPTINKISSPEPTIN_RECEPTOR_SYSTEM_IN_THE_OVARY",
   "KEGG_LONG_TERM_POTENTIATION",
   "GOMF_HORMONE_ACTIVITY",
   "GOBP_AXONEME_ASSEMBLY",
   "GOCC_CILIARY_PLASM",
   "GOBP_MOTILE_CILIUM_ASSEMBLY",
   "GOCC_CILIARY_TRANSITION_ZONE",
   "HP_ABSENCE_OF_SECONDARY_SEX_CHARACTERISTICS",
   "GOBP_REGULATION_OF_INSULIN_SECRETION",
   "GOBP_NEUROPEPTIDE_SIGNALING_PATHWAY")])

### simplify terms and make separate column for data source to color by
pltdat[,genesource:=gsub(pathway,pattern="^(GOCC)_.*$",replacement="GO CC")]
pltdat[,genesource:=gsub(genesource,pattern="^(GOBP)_.*$",replacement="GO BP")]
pltdat[,genesource:=gsub(genesource,pattern="^(GOMF)_.*$",replacement="GO MF")]
pltdat[,genesource:=gsub(genesource,pattern="^(HP)_.*$",replacement="Human Phenotypes")]
pltdat[,genesource:=gsub(genesource,pattern="^(WP)_.*$",replacement="Wikipathways")]
pltdat[,genesource:=gsub(genesource,pattern="^(KEGG)_.*$",replacement="KEGG Pathways")]

### Simplify terms themselves
# pltdat[pathway=="GOCC_GLUTAMATERGIC_SYNAPSE",pathway:="Glutamatergic\nsynapse"]
pltdat[pathway=="GOCC_GABA_ERGIC_SYNAPSE",pathway:="GABAergic synapse"]
pltdat[pathway=="HP_HYPERACTIVITY",pathway:="Hyperactivity"]
pltdat[pathway=="HP_ABNORMAL_AGGRESSIVE_IMPULSIVE_OR_VIOLENT_BEHAVIOR",pathway:="Aggressive/impulsive\nbehavior"]
pltdat[pathway=="GOBP_FEEDING_BEHAVIOR",pathway:="Feeding behavior"]
pltdat[pathway=="WP_KISSPEPTINKISSPEPTIN_RECEPTOR_SYSTEM_IN_THE_OVARY",pathway:="Kisspeptin receptor\nsystem (ovarian)"]
pltdat[pathway=="KEGG_LONG_TERM_POTENTIATION",pathway:="Long-term\npotentiation"]
pltdat[pathway=="GOMF_HORMONE_ACTIVITY",pathway:="Hormone activity"]
pltdat[pathway=="GOBP_AXONEME_ASSEMBLY",pathway:="Axoneme assembly"]
pltdat[pathway=="GOCC_CILIARY_PLASM",pathway:="Ciliary membrane"]
pltdat[pathway=="GOBP_MOTILE_CILIUM_ASSEMBLY",pathway:="Cilium assembly"]
pltdat[pathway=="GOCC_CILIARY_TRANSITION_ZONE",pathway:="Ciliary transition zone"]
pltdat[pathway=="HP_ABSENCE_OF_SECONDARY_SEX_CHARACTERISTICS",pathway:="Secondary sex\ncharacteristics"]
pltdat[pathway=="GOBP_REGULATION_OF_INSULIN_SECRETION",pathway:="Insulin secretion\nregulation"]
pltdat[pathway=="GOBP_NEUROPEPTIDE_SIGNALING_PATHWAY",pathway:="Neuropeptide signaling"]

### q: omg Github copilot just paid for itself thank you!!
# a: you're welcome

### make domain a factor so we can match it to prior color schemes
pltdat[,spdom:=paste0("v",spdom)]
pltdat$spdom <- factor(pltdat$spdom,levels=c("vVMH","vARC"))
pltdat$spdom

### make enrichments a factor so they're grouped by source on the y axis
pltdat$pathway <- factor(pltdat$pathway,levels=rev(c("Long-term\npotentiation","Neuropeptide signaling","GABAergic synapse","Insulin secretion\nregulation","Hormone activity","Kisspeptin receptor\nsystem (ovarian)","Axoneme assembly","Ciliary membrane","Cilium assembly","Ciliary transition zone","Hyperactivity","Aggressive/impulsive\nbehavior","Feeding behavior","Secondary sex\ncharacteristics")))

pltdat[,log10fdr:=-log10(padj)]

### plot:
names(pal) <- paste0("v",names(pal))

p <- ggplot(pltdat,aes(y=pathway,x=log10fdr))+
    geom_point(aes(col=spdom,size=NES))+#,position = position_dodge2v(preserve = "single",height=0.75))+
    ylab("Term")+
    # scale_color_manual(values=wc2cols)+
    xlab("-log10 (FDR)")+
    #xlim(0,30)+
    scale_size_continuous(range = c(0.75,3.5),transform = "exp")+
    scale_color_manual(values=c("#8c63cf","#5dd959"),na.value = NA)+
    labs(col="Domain")+
    geom_vline(xintercept=-log10(0.05),linetype="dashed",linewidth=0.5)+
    guides(col=guide_legend(byrow=T))+
    # # ^ necess. to get spacing to work in theme
    guides(col=guide_legend(override.aes=list(size=2.5)))+
    # ^ make legend points bigger
    theme(
        axis.text.y = element_text(size = 8, margin = margin(0, 0, 0, -0.15, "in")),
        axis.title.x = element_text(size = 9),
        axis.title.y = element_text(size = 9, margin = margin(0, 0, 0, 0.2, unit = "in")),
        axis.text.x = element_text(size = 8),
        legend.text = element_text(size = 8, hjust = 0.5),
        legend.title = element_text(size = 9, hjust = 0.5),
        legend.spacing.y = ggplot2::unit(0.075, "in"),
        plot.margin = margin(0.05, 0.01, 0, -0.1, unit = "in"),
        legend.position = "bottom",
        legend.direction = "vertical",
        legend.box.margin = margin(0, -0.3, 0, 0, unit = "in"),
        legend.spacing.x = ggplot2::unit(0.05, "in"),
        legend.box.background = element_blank(),
        legend.margin= margin(0,0.25,0,0,"in"),
        legend.key = element_blank(),
        panel.background = element_blank(),
    )


## this makes a weird second border with scales we don't want, and a second set of x axis tick labels along the top of the plot, so requires a little fixing in illustrator after the fact. but it'll do.
pdf("manuscript_plots/Supplemental/SF-msigdb_marker_GSEA.pdf",height=6,width=7)
p
dev.off()
```