---
title: "SF-Xenium-Visium domains side by side"
output: html_document
date: "2024-11-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(SpatialFeatureExperiment)
library(ggrastr)
library(escheR)

## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
##

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc. seemed to need this a couple times, but otherwise havent so its here as a preventative measure. part of this is adding the line 
# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
# to Renviron.site. see e.g. top response on https://stackoverflow.com/questions/73638290/python-on-mac-is-it-safe-to-set-objc-disable-initialize-fork-safety-yes-globall 
library(parallelly)
options(parallelly.supportsMulticore.disableOn="")
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost="localhost")
library(parallel)

## ggplot defaults
theme_update(theme_bw()+theme(axis.text.x = element_text(size = 5), axis.title.x = element_text(size = 5), axis.text.y = element_text(size = 4), axis.title.y = element_text(size =4), plot.title = element_text(size = 10,hjust=0.5), strip.text = element_text(size=4), legend.text = element_text(size=11), legend.title = element_text(size=10,hjust=0.5)))
```

### XENIUM setup ###
```{r}
## manuscript sample ids
mscriptsampleids <- fread("standardized_sampleids_for_plotting.txt")

hypx <- readRDS("xenium_HYP/processed-data/05_Banksy_M0lam0_res2_multisamp/01-sfe-in_staggered-coords_genetarg-only_NONlog-norm.RDS")

bksmooth <- fread("xenium_HYP/processed-data/07_Domains-subdomains_by_knnSmoothing_Banksytypes/03b-ARCVMHdomains_2stepsmooth_VMH-k10-0.2-VMH-k200-0.2_ARC-k50-0.1_ARC-k500-0.5.txt") ## xenium domain assignments after smoothing, by xenium cell

## but drop discarded cell clusters, too
bkcl <- fread("xenium_HYP/processed-data/05_Banksy_M0lam0_res2_multisamp/01-BanksyClusts_M0lam0_leiden_multisamp.txt")
setnames(bkcl,2,"cl")

bkanno <- fread("xenium_HYP/processed-data/05_Banksy_M0lam0_res2_multisamp/02-M0l0kg6_topClusMarkers_celltypes_annotated.txt")

## drop sample-specific clusters, append cluster annotations 
bkanno <- unique(bkanno[,.(clus,bjm_annot)])
bkanno <- bkanno[bjm_annot!="DISCARD"&bjm_annot!="VMH_4_DISCARD"]

## this drops rows that were assigned one of the discarded types (ie no longer in the cell type annotations)
bkcl <- merge.data.table(bkcl,bkanno,by.x="cl",by.y="clus")
## and now we can drop excluded clusters from xenium spe
hypx <- hypx[,colnames(hypx) %in% bkcl$rn]

## append cluster annots to xenium spe
bkcl <- DataFrame(bkcl,row.names=bkcl$rn)[colnames(hypx),]
bkcl$rn <- NULL
hypx$banksyclus <- bkcl$bjm_annot

## assign the domain labels to the xenium cells
bksmooth[dualVMHARC4=="other",dualVMHARC4:="Other"]
bksmooth <- DataFrame(bksmooth,row.names=bksmooth$rn)[colnames(hypx),]
hypx$dom <- bksmooth$dualVMHARC4

hypx$dom <- factor(hypx$dom,levels=c("VMH","ARC","Other"))
```


```{r}
pals <- readRDS("manuscript_plot_code/domain_and_xencluster_palettes_CHECKPALNAMESBEFOREUS.RDS")

pal <- pals[[1]]
```


## plot domains in each sample
helper function to extract a legend and pipe back to a diff plot: from https://statisticsglobe.com/add-common-legend-to-combined-ggplot2-plots-in-r/#example-2-add-shared-legend-to-ggplot2-plots-using-gridextra-package 
```{r}
extract_legend <- function(my_ggp) {
  step1 <- ggplot_gtable(ggplot_build(my_ggp))
  step2 <- which(sapply(step1$grobs, function(x) x$name) == "guide-box")
  step3 <- step1$grobs[[step2]]
  return(step3)
}
```

### VMH
```{r}
pltspe <- hypx[,hypx$sample_id=="X86_reg1"]

tmplegplt <- make_escheR(object = pltspe,y_reverse=FALSE)
tmplegplt <- tmplegplt |> add_ground("dom",size=0.15,point_size = 0.15)

tmplegplt <- tmplegplt+
    scale_color_manual(values=pal)+
    guides(color=guide_legend(override.aes = list(size=1)))+
    ggtitle(mscriptsampleids[sample_id=="X86_reg1",manuscript_id])+
    labs(color="Xenium\nDomain")+
    theme(axis.text.x=element_blank(),
          legend.title = element_text(size=9,hjust=0.5),
          legend.text=element_text(size=8),
              axis.text.y=element_blank(),
              axis.title.y=element_blank(),
              axis.title.x=element_blank(),
              axis.ticks = element_blank(),
              legend.background = element_blank(),
              plot.title=element_text(size=10,hjust=0.5),
              legend.box=element_blank(),
              panel.grid = element_blank(),
              #legend.margin=margin(0,0,0,-0.15,unit="in"),
              #plot.margin = margin(0.01,0.02,0,0,unit="in"),
              strip.background = element_blank(),
              )

tmplegplt <- rasterize(tmplegplt,layers="Point",res=450,dev="cairo_png")

leg.tmp <- extract_legend(tmplegplt)
dev.off()
rm(tmplegplt,pltspe)
###

## actual plots
samps <- lapply(unique(hypx$sample_id),FUN=function(x){hypx[,hypx$sample_id==x]})
names(samps) <- unique(hypx$sample_id)
rm(hypx)
gc(full=T)

setDTthreads(1,restore_after_fork = FALSE)
allplts <- mclapply(samps,mc.preschedule = FALSE,mc.cores=4,FUN=function(s){

  p <- make_escheR(object = s,y_reverse=FALSE)
  p <- p |> add_ground("dom",size=0.15,point_size = 0.15)

  p <- p+scale_color_manual(values=pal)+
      guides(color="none")+
      ggtitle(mscriptsampleids[sample_id==unique(s$sample_id),manuscript_id])+
      theme(axis.text.x=element_blank(),
            
            legend.title = element_text(size=9,hjust=0.5),
            legend.text=element_text(size=8),
            axis.text.y=element_blank(),
            axis.title.y=element_blank(),
            axis.title.x=element_blank(),
            axis.ticks = element_blank(),
            legend.background = element_blank(),
            plot.title=element_text(size=10,hjust=0.5),
            legend.box=element_blank(),
            panel.grid = element_blank(),
            #legend.margin=margin(0,0,0,-0.15,unit="in"),
            #plot.margin = margin(0.01,0.02,0,0,unit="in"),
            strip.background = element_blank(),
      )
    
    p<-rasterize(p,layers="Point",res=900,dev="cairo_png")
  
    return(p)
})
names(allplts) <- names(samps)

### save each individually to arrange with Visiums in AI
mapply(X=allplts,Y=names(allplts),SIMPLIFY=FALSE,FUN=function(X,Y){
  pdf(paste0("manuscript_plots/Supplemental/SF-XeniumVisium_domain_sidebyside/",Y,".pdf"),width=2,height=2)
  print(X)
  dev.off()
})

## save legend
pdf("manuscript_plots/Supplemental/SF-XeniumVisium_domain_sidebyside/domainlegend.pdf",height=2,width=1.25)
do.call("grid.arrange",list(arrangeGrob(leg.tmp)))
dev.off()
```

## visium
```{r}
rm(list=ls())
gc(full=T)

mscriptsampleids <- fread("standardized_sampleids_for_plotting.txt")
hyp2 <- readRDS("spatial_HYP/processed-data/03-QC_filters/hypN10_umi210_gene126_chrm50_spotsweeped_lognorm_rotsNmirrors_072224.RDS")
bscl <- fread("spatial_HYP/processed-data/06-BayesSpace/01-bayesspace60kiter_k15-20-31_out/BSpace_k15_HARMONYlmbna_nnsvg10.txt")

setnames(bscl,c("rn","cl"))
bscl[,cl:=paste0("X",cl)]

bscl[cl %in% c("X4","X6"),dom:="ARC"]
bscl[cl %in% c("X7","X12"),dom:="VMH"]
bscl[!(dom %in% c("VMH","ARC")),dom:="Other"]

bscl <- DataFrame(bscl,row.names=bscl$rn)[colnames(hyp2),]
hyp2$dom <- bscl$dom
hyp2$dom <- factor(hyp2$dom,levels=c("VMH","ARC","Other"))

pals <- readRDS("manuscript_plot_code/domain_and_xencluster_palettes_CHECKPALNAMESBEFOREUS.RDS")
pal <- pals[[1]]

samps <- lapply(unique(hyp2$sample_id),FUN=function(x){hyp2[,hyp2$sample_id==x]})
names(samps) <- unique(hyp2$sample_id)
rm(hyp2)
gc(full=T)

allplts <- mclapply(samps,mc.preschedule = FALSE,mc.cores=4,FUN=function(s){

  p <- make_escheR(object = s)
  p <- p |> add_ground("dom",size=0.15,point_size = 0.15)

  p <- p+scale_color_manual(values=pal)+
      guides(color="none")+
      ggtitle(mscriptsampleids[sample_id==unique(s$sample_id),manuscript_id])+
      theme(axis.text.x=element_blank(),
            
            legend.title = element_text(size=9,hjust=0.5),
            legend.text=element_text(size=8),
            axis.text.y=element_blank(),
            axis.title.y=element_blank(),
            axis.title.x=element_blank(),
            axis.ticks = element_blank(),
            legend.background = element_blank(),
            plot.title=element_text(size=10,hjust=0.5),
            legend.box=element_blank(),
            panel.grid = element_blank(),
            #legend.margin=margin(0,0,0,-0.15,unit="in"),
            #plot.margin = margin(0.01,0.02,0,0,unit="in"),
            strip.background = element_blank()
      )
    
    p<-rasterize(p,layers="Point",res=900,dev="cairo_png")
  
    return(p)
})

names(allplts) <- names(samps)

### save each individually to arrange with Xeniums in AI
mapply(X=allplts,Y=names(allplts),SIMPLIFY=FALSE,FUN=function(X,Y){
  pdf(paste0("manuscript_plots/Supplemental/SF-XeniumVisium_domain_sidebyside/",Y,".pdf"),width=2,height=2)
  print(X)
  dev.off() 
})

```
