---
title: "03-Concat Feature Sets as One Supp Table"
author: "Bernard Mulvey"
date: "2024-01-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
```

```{r}
hvg10 <- readRDS("data/04-feature_selection/01-hyp2n9_HVG10pctile_sample-blocked.RDS")
hvg20 <- readRDS("data/04-feature_selection/01-hyp2n9_HVG20pctile_sample-blocked.RDS")
svg10 <- readRDS("data/04-feature_selection/01-hyp2n9_nnsvg10pctile.RDS")
svg20 <- readRDS("data/04-feature_selection/01-hyp2n9_nnsvg20pctile.RDS")

genes <- unique(c(hvg10,hvg20,svg10,svg20))
genes <- as.data.table(genes)

# get symbols
enslut <- fread("raw-data/USEFOR10X_ensg_lut_hg38_fromEns98_111123.txt")
enslut <- unique(enslut[,.(ensembl_gene_id,external_gene_name,hgnc_symbol)])

genes <- merge.data.table(genes,enslut,by.x="genes",by.y="ensembl_gene_id")
genes[,hvg10:=ifelse(genes %in% hvg10,TRUE,FALSE)]
genes[,hvg20:=ifelse(genes %in% hvg20,TRUE,FALSE)]
genes[,svg10:=ifelse(genes %in% svg10,TRUE,FALSE)]
genes[,svg20:=ifelse(genes %in% svg20,TRUE,FALSE)]

fwrite(genes,"data/Supp Tabs/Table S2a-Feature sets.txt",sep='\t',quote=F)
```
