---
title: "04-Plot ARC8-9-13 only nnSVGs"
author: "Bernard Mulvey"
date: "2023-10-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
require(colorout)
source("~/.R/calc_tau_for_cellOrTissueSpecificity_metric.R")
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")

## change write.table to output a TSV without quotes or rownames by default
library(default)
default(write.table) <- list(row.names=F,col.names=T,sep='\t',quote=F)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

```{r}
hyp2.vmh <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_061323_HarmonyBSpc-q2VMH_rowname-key.RDS")

### crop V12D07-075_B1 first -- see code/00 blah blah .rmd
coordstmp <- as.data.frame(spatialCoords(hyp2.vmh))
rownames(coordstmp) <- colnames(hyp2.vmh)
coordstmp <- as.data.table(coordstmp,keep.rownames=T)
coordstmp <- coordstmp[,diag:=pxl_col_in_fullres+pxl_row_in_fullres]
coordstmp <- coordstmp[!(rn %in% grep(rn,pattern="V12D07-075_B1",value=T)&diag>30000)]

hyp2 <- hyp2.vmh[,colnames(hyp2.vmh)%in%coordstmp$rn]
stopifnot(dim(hyp2)[2]==nrow(coordstmp))

### now cut to ARC spots (clusters 8 and 13) only
bscl <- fread("analysis/data/spe_053123/H02-clustering/03-bs_harmony_hvg1020_nnsvg1020_9-15-20-31_out/BSpace_Harmony_nnsvg10pctile_15.txt")
bscl <- as.data.frame(bscl)
rownames(bscl) <- bscl$rn
bscl <- DataFrame(bscl)
bscl <- bscl[colnames(hyp2),]
colLabels(hyp2) <- as.character(bscl$BShar_nnsvg10pctile_15)
rm(bscl)

hyp2 <- hyp2[,which(hyp2$label %in% c("8","9","13"))]
rownames(hyp2) <- rowData(hyp2)$gene_name
#cleanup before nnsvg
rm(hyp2.vmh)
```

```{r}
nnsvg_ranks <- fread("analysis/data/spe_053123/H05-bspace15-nnsvg10_ARC_clusters/06-meangeneranks_nnSVG_samplewise_n3s1.5_ARC8-9-13-spotsonly_postcropD07075B1.txt")

# subset to nnsvgs that were FDR significant (i.e. those in loaded table) in at least 4 of 8 samples
nnsvg_ranks <- nnsvg_ranks[n_naSamps<=4]
setorder(nnsvg_ranks,meanrank)
plotgenes <- nnsvg_ranks[1:100,gene_name]

i<-1
for (i in c(1:100)){
    curgene <- plotgenes[i]
    plt <- spatialLIBD::vis_grid_gene(hyp2,geneid = curgene,return_plots = T,spatial=F,point_size = 1,auto_crop = T)
    ### adjust font sizes
    plt <- lapply(plt,FUN=function(x){x+
            theme(plot.title = element_text(size = 11,hjust=0.5), strip.text = element_text(size=10), legend.text = element_text(size=10), legend.title = element_text(size=10,hjust=0.5))
            })
    pdf(paste0("plots/spe_053123/H05-bspace15-nnsvg10_ARC_clusters/04-nnSVG analysis of ARC8-9-13/",curgene,".pdf"),width=10,height=8)
    do.call("grid.arrange",plt)
    dev.off()
}

```




```
