---
title: "00-Create new SPE w V12D07-075_B1 clipped to upper l quadrant"
author: "Bernard Mulvey"
date: "2023-07-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different:
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(ggplot2)
library(gridExtra)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

find spatialcoords for this slice corresponding to LUQ
```{r}
vmh <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_061323_HarmonyBSpc-q2VMH_rowname-key.RDS")

colnames(vmh) <- colData(vmh)$key
# ^ these don't auto-propagate to int_coldata like they do for coldata
rownames(spatialCoords(vmh)) <- rownames(colData(vmh))
tmp <- vmh[,vmh$sample_id=="V12D07-075_B1"]

### get coordinates for plotting as x-y ggplot to determine approximate upper quadrant values
tmpcoord <- as.data.table(tmp@int_colData$spatialCoords,keep.rownames = T)
tmpcl <- as.data.table(colData(tmp),keep.rownames=T)[,.(rn,label)]
tmpcoord <- merge.data.table(tmpcoord,tmpcl,by="rn")

tmpcoord[label==1,col:="other"]
tmpcoord[label==2,col:="VMH"]

ggplot(tmpcoord,aes(x=pxl_col_in_fullres,y=pxl_row_in_fullres,col=paste0(col)))+geom_point(size=0.2)

### careful, the section is flipped vertically using these coordinates.
### so we want pxl row < 15,000 and pxlcol  < 15,000
### this defines an isoc. triangle with a hypot. defining the diagonal edge we want to cut along --> x /  sin(90°) = 15000 / sin(45°) = 21213
### --> therefore, any given point of interest will have row+col coord < 21213

tmpcoord2 <- tmpcoord[pxl_col_in_fullres<15000&pxl_row_in_fullres<15000&(pxl_col_in_fullres+pxl_row_in_fullres)<30000]

ggplot(tmpcoord2,aes(x=pxl_col_in_fullres,y=pxl_row_in_fullres,col=paste0(col)))+geom_point(size=0.4)


droprows <- tmpcoord[!(rn %in% tmpcoord2$rn),rn]
vmh2 <- vmh[,!(colnames(vmh) %in% droprows)]
dim(vmh2)

saveRDS(vmh2,"data/processing/hyp_umi600_gene450_chrm35_UNNORM_trimmedD07-075_B1 070123.RDS")
```
