---
title: "02-Compare human sex DE to Yao23 mouse sex DE by subclass or supertype"
author: "Bernard Mulvey"
date: "2023-08-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
require(colorout)
library(dreamlet)
library(BiocParallel)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

```{r}
### load hyp sex de and process equivalently
hyp2 <- readRDS("data/processing/hyp_umi600_gene450_chrm35_UNNORM_trimmedD07-075_B1_rotsAndMirrors.RDS")
demos <- fread("raw-data/demos.txt")

tmpcd <- as.data.table(colData(hyp2),keep.rownames=T)
tmpcd <- merge.data.table(tmpcd,demos[,.(BrNum,Sex,PMI)],by.x = "brnum",by.y="BrNum")
tmpcd <- DataFrame(tmpcd)
rownames(tmpcd) <- tmpcd$rn
tmpcd <- tmpcd[colnames(hyp2),]
colData(hyp2) <- tmpcd
colData(hyp2)$Sex <- as.factor(colData(hyp2)$Sex)

rm(tmpcd)
## append clusters
bscl <- fread("analysis/data/spe_053123/H02-clustering/03-bs_harmony_hvg1020_nnsvg1020_9-15-20-31_out/BSpace_Harmony_nnsvg10pctile_15.txt")
bscl <- bscl[rn %in% colnames(hyp2)]
setnames(bscl,2,"label")
bscl[,label:=paste("X",label,sep = "")]
bscl <- DataFrame(bscl)
rownames(bscl) <- bscl$rn
bscl <- bscl[colnames(hyp2),]
colLabels(hyp2) <- as.factor(bscl$label)

rm(bscl)
# row names as genes for ease of interpretation; drop duplicated gene names
rownames(hyp2) <- rowData(hyp2)$gene_name
dups <- as.data.table(rownames(hyp2))
dups <- dups[,.N,by="V1"]
keeps <- dups[N==1,V1]
hyp2 <- hyp2[keeps,]

rm(dups,keeps)
```



# dreamlet
```{r}
sbp <- MulticoreParam(11)

proc <- dreamlet::aggregateToPseudoBulk(hyp2,sample_id="sample_id",cluster_id = "label",BPPARAM = sbp)

## consider all genes (min.counts=1 , as was done for mouse)
dif <- dreamlet::processAssays(proc,min.cells = 10,min.count = 1,min.samples = 4,min.prop = 0.4,normalize.method = "TMM",useCountsWeights = T,BPPARAM = sbp,formula = ~Sex)

sexdif <- dreamlet::dreamlet(dif,formula = ~Sex,BPPARAM = sbp)

# find relevant coefficient name
coefNames(sexdif)
#
sexdif2 <- dreamlet::topTable(sexdif,coef="SexM",number=Inf,adjust.method ="BH")
sexdif2 <- as.data.table(sexdif2,keep.rownames=T)

setnames(sexdif2,"logFC","logFC_hum")
rm(sexdif,dif)
```

#### 10-09-23: test correlations at different spatial registration thresholds by pseudobulking all threshold-passing mouse cell types for VMH / ARC
```{r}
supreg <- fread("analysis/data/spe_053123/H06-Spatial Registration/01-ABAhyp-supertype_single-HYP-spdomains_registration_allgenes.txt")
subreg <- fread("analysis/data/spe_053123/H06-Spatial Registration/01-ABAhyp-subclass_single-HYP-spdomains_registration_allgenes.txt")

### set up yao 23 data
cellmeta <- fread("raw-data/ABA_Whole_Mouse_Brain_Yao23_HYP/cell_metadata_with_cluster_annotation.csv")
hypv2 <- zellkonverter::readH5AD("raw-data/ABA_Whole_Mouse_Brain_Yao23_HYP/WMB-10Xv2-HY-raw.h5ad")
hypv3 <- zellkonverter::readH5AD("raw-data/ABA_Whole_Mouse_Brain_Yao23_HYP/WMB-10Xv3-HY-raw.h5ad")

tmpcdv2 <- as.data.table(colData(hypv2),keep.rownames=T)
cellmeta2 <- cellmeta[cell_label %in% colnames(hypv2)]
tmpcdv2 <- merge.data.table(tmpcdv2,cellmeta2,by.x="rn",by.y="cell_label")
tmpcdv2 <- DataFrame(tmpcdv2)
rownames(tmpcdv2) <- tmpcdv2$rn
tmpcdv2 <- tmpcdv2[colnames(hypv2),]
colData(hypv2) <- tmpcdv2

tmpcdv3 <- as.data.table(colData(hypv3),keep.rownames=T)
cellmeta3 <- cellmeta[cell_label %in% colnames(hypv3)]
tmpcdv3 <- merge.data.table(tmpcdv3,cellmeta3,by.x="rn",by.y="cell_label")
tmpcdv3 <- DataFrame(tmpcdv3)
rownames(tmpcdv3) <- tmpcdv3$rn
tmpcdv3 <- tmpcdv3[colnames(hypv3),]
colData(hypv3) <- tmpcdv3

## since these are all uniformly processed for allen atlas, should be able to join them up...
bothhyp <- cbind(hypv2,hypv3)
assayNames(bothhyp) <- "counts"
rm(tmpcdv2,tmpcdv3,cellmeta2,cellmeta3,cellmeta,hypv2,hypv3)
gc(full=T)

colData(bothhyp) <- colData(bothhyp)[,c(1:3,8,10,12,15,16,20,21)]
colnames(colData(bothhyp))
bothhyp$donor_sex <- as.factor(bothhyp$donor_sex)
rownames(bothhyp) <- rowData(bothhyp)$gene_symbol
# drop genes with two or more rows
drops <- as.data.table(rownames(bothhyp))[,.N,by="V1"]
keeprows <- drops[N==1,V1]

bothhyp <- bothhyp[keeprows,]
stopifnot(identical(rownames(bothhyp),rowData(bothhyp)$gene_symbol)&nrow(bothhyp)==length(unique(rownames(bothhyp))))

rm(keeprows,drops)
gc(full=T)

### fix supercluster/subclass labels to match those from registration
# Fix variable names for compatibility
bothhyp$subclass <- gsub(bothhyp$subclass,pattern=" ",replacement="_")
bothhyp$subclass <- gsub(bothhyp$subclass,pattern="-",replacement="_")
bothhyp$subclass <- gsub(bothhyp$subclass,pattern="/",replacement="_")
bothhyp$subclass <- paste0("x",bothhyp$subclass)
bothhyp$subclass <- as.factor(bothhyp$subclass)

bothhyp$supertype <- gsub(bothhyp$supertype,pattern=" ",replacement="_")
bothhyp$supertype <- gsub(bothhyp$supertype,pattern="-",replacement="_")
bothhyp$supertype <- gsub(bothhyp$supertype,pattern="/",replacement="_")
bothhyp$supertype <- paste0("x",bothhyp$supertype)
bothhyp$supertype <- as.factor(bothhyp$supertype)
```

remove genes found on chrX/Y in either mouse (mm10) or human (hg38)
```{r}
library(biomaRt)
hgens <- useDataset(dataset="hsapiens_gene_ensembl",mart=useEnsembl(biomart="genes"))
mmens <- useDataset(dataset="mmusculus_gene_ensembl",mart=useEnsembl(biomart="genes"))

#listAttributes(hgens)
#listFilters(hgens)
#listAttributes(mmens)
#listFilters(mmens)
hgallo <- getBM(mart = hgens,attributes = "hgnc_symbol",filters = "chromosome_name",values=c("X","Y"))
hgallo <- hgallo$hgnc_symbol

msallo <- getBM(mart=mmens,attributes="mgi_symbol",filters="chromosome_name",values=c("X","Y"))
msallo <- msallo$mgi_symbol
```

```{r}
### get spatreg stats for top 25 genes
library(magrittr)

abasubreg <- readRDS("/Users/bmulvey/Desktop/KM Lab/local_hthspatial/analysis/data/spe_053123/H06-Spatial Registration/01-ABAhyp_mincells5-n5_subclass_modelingres.RDS")

abasubreg <- abasubreg$enrichment[,grep(colnames(abasubreg$enrichment),pattern="^t_stat",value=T)]
colnames(abasubreg) %<>% gsub(.,pattern="^t_stat_",replacement="")

abasupreg <- readRDS("/Users/bmulvey/Desktop/KM Lab/local_hthspatial/analysis/data/spe_053123/H06-Spatial Registration/01-ABAhyp_mincells5-n5_supertype_modelingres.RDS")

abasupreg <- abasupreg$enrichment[,grep(colnames(abasupreg$enrichment),pattern="^t_stat",value=T)]
colnames(abasupreg) %<>% gsub(.,pattern="^t_stat_",replacement="")

hypspat <- readRDS("analysis/data/spe_053123/H06-Spatial Registration/01-spatialHYP_single-spdomain_sLIBD-enrichmntmodelres.RDS")

cor_subclass_perspatial <- spatialLIBD::layer_stat_cor(stats=abasubreg,modeling_results = hypspat,model_type = "enrichment",top_n = 25)

cor_supertype_perspatial <- spatialLIBD::layer_stat_cor(stats=abasupreg,modeling_results = hypspat,model_type = "enrichment",top_n = 25)

subreg <- as.data.table(cor_subclass_perspatial,keep.rownames=T)
subreg <- melt.data.table(subreg,id.vars="rn")

supreg <- as.data.table(cor_supertype_perspatial,keep.rownames=T)
supreg <- melt.data.table(supreg,id.vars="rn")
```

```{r}

outtab <- as.data.frame(matrix(ncol=4,nrow=0))

for (i in c(1:11)){
    t <- seq(0,0.5,by=0.05)[i]
    vmha.sub <- subreg[value>t&variable=="X5",rn]
    vmha.sup <- supreg[value>t&variable=="X5",rn]
    vmhb.sub <- subreg[value>t&variable=="X6",rn]
    vmhb.sup <- supreg[value>t&variable=="X6",rn]
    arca.sub <- subreg[value>t&variable=="X8",rn]
    arca.sup <- supreg[value>t&variable=="X8",rn]
    arcb.sub <- subreg[value>t&variable=="X9",rn]
    arcb.sup <- supreg[value>t&variable=="X9",rn]
    arcc.sub <- subreg[value>t&variable=="X13",rn]
    arcc.sup <- supreg[value>t&variable=="X13",rn]
    
    bothhyp$X5 <- ifelse(bothhyp$subclass %in% vmha.sub,yes="Y",no="N")
    bothhyp$X6 <- ifelse(bothhyp$subclass %in% vmhb.sub,yes="Y",no="N")
    bothhyp$X8 <- ifelse(bothhyp$subclass %in% arca.sub,yes="Y",no="N")
    bothhyp$X9 <- ifelse(bothhyp$subclass %in% arcb.sub,yes="Y",no="N")
    bothhyp$X13 <- ifelse(bothhyp$subclass %in% arcc.sub,yes="Y",no="N")
    
    cls <- c("X5","X6","X8","X9","X13")[c(length(vmha.sub)>0,length(vmhb.sub)>0,length(arca.sub)>0,length(arcb.sub)>0,length(arcc.sub)>0)]
    sbp <- MulticoreParam(5)
    reslist.sub <- bplapply(cls,BPPARAM=sbp,FUN=function(x){
        proc <- aggregateToPseudoBulk(bothhyp,sample_id = "library_label.x",cluster_id = x)
        dif <- dreamlet::processAssays(proc,min.cells = 10,min.count = 1,min.samples = 4,min.prop = 0.4,normalize.method = "TMM",useCountsWeights = T,formula = ~donor_sex)
        subdif <- dreamlet::dreamlet(dif,formula = ~donor_sex)
        subdif2 <- dreamlet::topTable(subdif,coef="donor_sexM",number=Inf,adjust.method ="BH")
        subdif2 <- as.data.table(subdif2)
        subdif2 <- subdif2[,.(assay,ID,logFC)]
        subdif2 <- melt.data.table(subdif2,id.vars=c("assay","ID"))
        setnames(subdif2,"value","logFC_ms")
        subdif2 <- subdif2[assay=="Y"]
        subdif2[,ID:=toupper(ID)]
        
        humdif <- sexdif2[assay==x,.(ID,logFC_hum)]
        
        testdif <- merge.data.table(subdif2,humdif,by="ID",allow.cartesian=T)
        testdif <- testdif[!(ID %in% c(hgallo,toupper(msallo)))]
        cval <- cor(testdif$logFC_hum,testdif$logFC_ms,method="pearson",use="pairwise.complete.obs")
        return(cval)
    })
    names(reslist.sub) <- cls
    
    # and for supertypes
    bothhyp$X5 <- ifelse(bothhyp$supertype %in% vmha.sup,yes="Y",no="N")
    bothhyp$X6 <- ifelse(bothhyp$supertype %in% vmhb.sup,yes="Y",no="N")
    bothhyp$X8 <- ifelse(bothhyp$supertype %in% arca.sup,yes="Y",no="N")
    bothhyp$X9 <- ifelse(bothhyp$supertype %in% arcb.sup,yes="Y",no="N")
    bothhyp$X13 <- ifelse(bothhyp$supertype %in% arcc.sup,yes="Y",no="N")
    
    c("X5","X6","X8","X9","X13")[c(length(vmha.sup)>0,length(vmhb.sup)>0,length(arca.sup)>0,length(arcb.sup)>0,length(arcc.sup)>0)]  
    sbp <- MulticoreParam(5)
    reslist.sup <- bplapply(cls,BPPARAM=sbp,FUN=function(x){
        proc <- aggregateToPseudoBulk(bothhyp,sample_id = "library_label.x",cluster_id = x)
        dif <- dreamlet::processAssays(proc,min.cells = 10,min.count = 1,min.samples = 4,min.prop = 0.4,normalize.method = "TMM",useCountsWeights = T,formula = ~donor_sex)
        supdif <- dreamlet::dreamlet(dif,formula = ~donor_sex)
        supdif2 <- dreamlet::topTable(supdif,coef="donor_sexM",number=Inf,adjust.method ="BH")
        supdif2 <- as.data.table(supdif2)
        supdif2 <- supdif2[,.(assay,ID,logFC)]
        supdif2 <- melt.data.table(supdif2,id.vars=c("assay","ID"))
        setnames(supdif2,"value","logFC_ms")
        supdif2 <- supdif2[assay=="Y"]
        supdif2[,ID:=toupper(ID)]
        
        humdif <- sexdif2[assay==x,.(ID,logFC_hum)]
        
        testdif <- merge.data.table(supdif2,humdif,by="ID",allow.cartesian=T)
        testdif <- testdif[!(ID %in% c(hgallo,toupper(msallo)))]
        cval <- cor(testdif$logFC_hum,testdif$logFC_ms,method="pearson",use="pairwise.complete.obs")
        return(cval)
    })
    names(reslist.sup) <- cls
    
    st <- nrow(outtab)+1
    en <- nrow(outtab)+length(reslist.sub)+length(reslist.sup)
    hf <- nrow(outtab)+length(reslist.sub)
    schf <- nrow(outtab)+length(reslist.sub)+1
    outtab[seq(st,en,1),1] <- t
    outtab[seq(st,en,1),2] <- c(names(reslist.sub),names(reslist.sup))
    outtab[seq(st,hf,1),3] <- "subclass"
    outtab[seq(schf,en,1),3] <- "supertype"
    outtab[seq(st,en),4] <- c(unlist(reslist.sub),unlist(reslist.sup))
    rm(reslist.sub,reslist.sup,st,en,hf,schf,t)
}
rm(i,reslist.sup,reslist.sub,mmens,hgens,demos,cls,vmha.sub,vmha.sup,vmhb.sub,vmhb.sup,arca.sub,arca.sup,arcb.sub,arcb.sup,arcc.sub,arcc.sup)


outtab <- as.data.table(outtab)
setnames(outtab,c("registration_thresh_top25","spHYP_cluster","yao23_clustlevel","autosomal_pcc"))

### well this gets to a threshold of 0.35 and then stops working because...not sure exactly. but not a single spatial domain of VMH/ARC vs. the sex DE of aggregated cells that register even makes it above a pearson correlation of 0. ouch. 


```
