---
title: "05-Collate sex DE GSEA results"
author: "Bernard Mulvey"
date: "2023-10-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
require(colorout)
source("~/.R/calc_tau_for_cellOrTissueSpecificity_metric.R")
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")

## change write.table to output a TSV without quotes or rownames by default
library(default)
default(write.table) <- list(row.names=F,col.names=T,sep='\t',quote=F)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```


### AUTOSOMAL GENES ONLY
```{r}
mklist <- list()
i <- 1
for (i in c(1:30)){
    clus <- paste0("x",ceiling(i/2))
    targfile <- ifelse(2*ceiling(i/2)==i,
                       no=list.files(
                           paste0(
                           "analysis/data/spe_053123/H08-GSEA, GO etc/H08.05-Sex DEG GSEA/hyp_", clus, "_mup_fdn_lfcrank.GseaPreranked"),pattern="gsea_report_for_na_pos.*\\.tsv",full.names=T),
                       yes=list.files(
                          paste0(
                              "analysis/data/spe_053123/H08-GSEA, GO etc/H08.05-Sex DEG GSEA/hyp_", clus, "_mup_fdn_lfcrank.GseaPreranked/"),pattern="gsea_report_for_na_neg.*\\.tsv",full.names = T)
                       )

    curgse <- fread(targfile)
    curgse <- curgse[,c(1,4:11)]
    curgse[,spdomain:=clus]
    curgse[,direction:=ifelse(2*ceiling(i/2)==i,
                              no="male_up",
                              yes="female_up")]
    setnames(curgse,c(5:9),c("P.Value","FDR_qval","FWER_pval","rankAtMax","leading_edge"))
    
    # grab markers once per cluster
    if(2*ceiling(i/2)==i){
        mklist[[i]] <- fread(paste0("analysis/data/spe_053123/H08-GSEA, GO etc/H08.05-Sex DEG GSEA/hyp_",clus,"_mup_fdn_lfcrank.GseaPreranked/edb/",clus,"_collapsed.rnk"),header=F)}
    
    # join
    if (i==1){allgse <- curgse}
    else{allgse <- rbind(allgse,curgse)}
    setorder(allgse,NES)
    
    
    rm(curgse,targfile,clus)
}
rm(i)




fwrite(allgse,"analysis/data/spe_053123/H08-GSEA, GO etc/H08.05-Sex DEG GSEA/collated_dreamlet-autosom-sexDE-brnum-ranef_gsea_results.txt",sep='\t',quote=F)
```

### peep the top 10 per domain-sex, besides the 
*MANNO tags (which are so confirmatory its stupid), 
*DESCARTES (ibid), 
*DURANTE (sort of, but olfactory--which could be INTERESTING, just a lot of redundant terms coming up from those sets),
*RUBENSTEIN (non neural tissues)

```{r}
maxhitlist <- list()
i <- 1
for (i in c(1:30)){
    clus <- paste0("x",ceiling(i/2))
    cursex <- ifelse(2*ceiling(i/2)==i,no="male_up",yes="female_up")
    if(2*ceiling(i/2)==i){
        tmp <- allgse[spdomain==clus&direction==cursex&NES<0]
        tmp <- tmp[NAME %in% grep(NAME,pattern="MANNO_|DURANTE|DESCARTES|RUBENSTEIN",value=T,invert=T)]
        tmp[,NES:=NES*-1]
    }
    else{tmp <- allgse[spdomain==clus&direction==cursex&NES>0&NAME %in% grep(NAME,pattern="MANNO_|DURANTE||DESCARTES|RUBENSTEIN",value=T,invert = T)]}
    setorder(tmp,-NES)
    maxhitlist[[i]] <- unique(tmp)[c(1:10)]
    names(maxhitlist)[i] <- paste0(clus,"_",cursex)
    rm(tmp,clus,cursex)
}
```
