---
title: "04-Mouse Hypomap reg wrapper enrichment stats and registration"
author: "Bernard Mulvey"
date: "2023-08-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
library(zellkonverter)
library(magrittr)
require(colorout)
library(BiocParallel)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```


Data available thru cellxgene as a h5ad (4 GB). downloaded locally 090323 https://cellxgene.cziscience.com/collections/1d061e0e-8421-439e-88a4-36ab15d1de41


### load hypomap h5ad
```{r}
hmap <- zellkonverter::readH5AD("~/Desktop/local.h5ad")
```

Filter to abundant enough cells then prep for spatial reg
```{r}
tab <- as.data.table(table(hmap$Dataset,hmap$C185_named))
tab <- dcast(tab,V2~V1,value.var = "N")

# subset to cell subclasses or supertypes with at least 8 cells in at least 3 samples
tab[,sum:=rowSums(tab[,.SD>=8,.SDcols=c(2:ncol(tab))])]
# subsetting for # of sample•(supertypes or subclasses)
tab <- tab[sum>2]

## fastest way to subset: make unique sample-cluster ids in both datasets and filter sce to it
tab2 <- melt(tab,id.vars="V2",measure.vars=c(2:(ncol(tab)-1)))
tab2 <- tab2[value>7]
tab2[,sampclus:=paste0(variable,V2)]

hmap$sampclus <- paste0(hmap$Dataset,hmap$C185_named)


hmap2 <- hmap[,hmap$sampclus %in% unique(tab2$sampclus)]

# Fix variable names for compatibility
hmap2$C185_named <- gsub(hmap2$C185_named,pattern=" ",replacement="_")
hmap2$C185_named <- gsub(hmap2$C185_named,pattern="-",replacement="_")
hmap2$C185_named <- gsub(hmap2$C185_named,pattern=":",replacement="")
hmap2$C185_named <- as.factor(hmap2$C185_named)
hmap2$C185_named <- droplevels(hmap2$C185_named)

# rownames to (capitalized) gene symbols
rownames(hmap2) <- toupper(rowData(hmap2)$feature_name)
# drop genes with two or more rows
drops <- as.data.table(rownames(hmap2))[,.N,by="V1"]
keeprows <- drops[N==1,V1]
# okay, there are none. nice

# change raw count assay name to "counts" as expected in spatialLIBD via scuttle
assayNames(hmap2)[1] <- "counts"

rm(drops,hmap,tab,tab2,keeprows)
gc(full=T)
message("Input dataset ready. Starting spatialLIBD::registration_wrapper...")
```


```{r}
hmap185 <- registration_wrapper(hmap2,var_registration = "C185_named",var_sample_id = "Dataset",gene_ensembl = "features",gene_name = "feature_name",min_ncells = 8)


saveRDS(hmap185,"analysis/data/spe_053123/H06-Spatial Registration/04-Hypomap_mincells8-n2datasets_C185types_sLIBD-enrichmntmodelres.RDS")
```

###################################################################
They also have a 66-cluster scheme, so let's try that too.
###################################################################
### load hypomap h5ad
```{r}
rm(hmap2,hmap185)
hmap <- zellkonverter::readH5AD("~/Desktop/local.h5ad")
```

Filter to abundant enough cells then prep for spatial reg
```{r}
tab <- as.data.table(table(hmap$Dataset,hmap$C66_named))
tab <- dcast(tab,V2~V1,value.var = "N")

# subset to cell subclasses or supertypes with at least 8 cells in at least 3 DATASETS
tab[,sum:=rowSums(tab[,.SD>=8,.SDcols=c(2:ncol(tab))])]
# subsetting for # of datasets•(supertypes or subclasses)
tab <- tab[sum>2]

## fastest way to subset: make unique sample-cluster ids in both datasets and filter sce to it
tab2 <- melt(tab,id.vars="V2",measure.vars=c(2:(ncol(tab)-1)))
tab2 <- tab2[value>7]
tab2[,sampclus:=paste0(variable,V2)]

hmap$sampclus <- paste0(hmap$Dataset,hmap$C66_named)


hmap2 <- hmap[,hmap$sampclus %in% unique(tab2$sampclus)]

# Fix variable names for compatibility
hmap2$C66_named <- gsub(hmap2$C66_named,pattern=" ",replacement="_")
hmap2$C66_named <- gsub(hmap2$C66_named,pattern="-",replacement="_")
hmap2$C66_named <- gsub(hmap2$C66_named,pattern=":",replacement="")
hmap2$C66_named <- as.factor(hmap2$C66_named)
hmap2$C66_named <- droplevels(hmap2$C66_named)

# rownames to (capitalized) gene symbols
rownames(hmap2) <- toupper(rowData(hmap2)$feature_name)
# drop genes with two or more rows
drops <- as.data.table(rownames(hmap2))[,.N,by="V1"]
keeprows <- drops[N==1,V1]
# okay, there are none. nice

# change raw count assay name to "counts" as expected in spatialLIBD via scuttle
assayNames(hmap2)[1] <- "counts"

rm(drops,keeprows,hmap,tab,tab2,keeprows)
gc(full=T)
message("Input dataset ready. Starting spatialLIBD::registration_wrapper...")
```


```{r}
hmap66 <- registration_wrapper(hmap2,var_registration = "C66_named",var_sample_id = "Dataset",gene_ensembl = "features",gene_name = "feature_name",min_ncells = 8)


saveRDS(hmap66,"analysis/data/spe_053123/H06-Spatial Registration/04-Hypomap_mincells8-n2datasets_C66types_sLIBD-enrichmntmodelres.RDS")
```
