---
title: "01-Compare Hypomap Mouse Arcuate Markers and BSpace Cluster Markers"
author: "Bernard Mulvey"
date: "2023-06-23"
output: html_document
---


```{r setup, include=FALSE}
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(SpatialExperiment)
library(ggspavis)
library(scater) # addPerCellQC
require(colorout)
ColorOut()
library(BiocParallel)
library(scran)
library(parallel)
library(igraph)
library(nnSVG)
library(ggplot2)
library(colorout)
library(readxl)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

### Setup 1: hyp data with colnames to key for uniqueness; attach demographics
```{r}
hyp2 <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_061323_HarmonyBSpc-q2VMH_rowname-key.RDS")

demos <- fread("raw-data/demos.txt")

tmpcdat <- as.data.table(colData(hyp2),keep.rownames=T)
tmpcdat <- merge.data.table(tmpcdat,demos,by.x="brnum",by.y="BrNum")
tmpcdat <- as.data.frame(tmpcdat)
rownames(tmpcdat) <- tmpcdat$rn
sum(rownames(tmpcdat)==rownames(colData(hyp2)))
# fix
tmpcdat <- tmpcdat[rownames(colData(hyp2)),]
stopifnot(sum(rownames(tmpcdat)==rownames(colData(hyp2)))==ncol(hyp2))
colData(hyp2) <- DataFrame(tmpcdat)

#
rm(demos,tmpcdat)
```

### Setup 2: load bayesspace markers that were ranked ≤10 in any of [logFC.cohen, AUC, or log.fc] from all harmony'd feature-set•k combinations (4 feature sets x k(9,15,20,31))
```{r}
bspmark <- as.data.table(read_excel("local_results_ref/bayesspace markers.xlsx"))
# remove empty columns
bspmark <- bspmark[,-c("...8","...12","...16")]
```

### get arcuate markers from hypomap (mouse hypothalamus sc-seq mega-analysis)
```{r}
hypomap <- saveRDS(hypomap,"local_results_ref/hypomap_sheetlist.RDS")
### hypothalamic area predictions per cluster at 286-cluster depth
names(hypomap[[9]])

# get cluster identifier 
arcuates <- hypomap[[9]][region_name %in% grep(region_name,pattern="Arcuate",value=T),cluster_id]

# get markers for arcuate clusters
names(hypomap[[6]])
arcuate.markers <- hypomap[[6]][cluster_id %in% arcuates]

arc.markers <- unique(arcuate.markers$gene)

# write.table(arc.markers,"local_results_ref/hypomap_arcuate_markergenes.txt",sep='\t',quote=F,row.names=F,col.names=F)
```

```{r}
bspmark.arcsum <- bspmark[gene %in% toupper(arc.markers),.N,by=c("cluster_set","cluster")]

quantile(bspmark.arcsum$N)
# top 25%ile of clusters overlapping putative mouse arcuate markers = 41+ shared markers
bspmark.arcsum <- bspmark.arcsum[N>=41]
## 78 possible clusters among the 16 bspace runs

### visually examining in "plots/H02-clustering/02-bayesspace_q9-15-20-31_HVGorSVG_spotplots/"
### ^ arcuate should be medial and/or ventral to VMH.

### hvg10pctile_31: 19 clusters with over 41 markers shared with mouse arc clusters. top hg cluster in terms of overlap is dorsolateral to vmh, so let;s scope down to k=20.

### hvg10pctile_20: 4 candidate clusters (2,3,9,14; top olap=9). cluster 9 is in places corresp to both periventricular nu and some lateral area depending on sample. cluster 2 is sparse and lateral. CLUSTER 3 SPOT ON. cluster 14 definitely ain't it. so let's step down once more to k=15.

### hvg10pctile_15 = no matches w ≥41 matched markers.

### unrelated observation: lateral hypothalamic area (tuberal part if going by ABA terms) forms a thin little stripe along the lateral border of VMH (e.g. darker purple in hvg10pctile_k20)--strongly marked by HCRT, consistent with LHA.











```

