---
title: "GeneralUse-xenARCVMH_cluster_IDs_table_plotname_column"
output: html_document
date: "2024-10-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)

## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
##

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc. seemed to need this a couple times, but otherwise havent so its here as a preventative measure. part of this is adding the line 
# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
# to Renviron.site. see e.g. top response on https://stackoverflow.com/questions/73638290/python-on-mac-is-it-safe-to-set-objc-disable-initialize-fork-safety-yes-globall 
library(parallelly)
options(parallelly.supportsMulticore.disableOn="")
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost="localhost")


## ggplot defaults
theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace("datasets")
```


### 
```{r}
## convert ARC_1..etc to more descriptive cluster IDs defined based on ARC/VMH specific cluster marker analyses
arcvmhanno <- fread("xenium_HYP/processed-data/07_Domains-subdomains_by_knnSmoothing_Banksytypes/04e_ARC_and_VMH_cluster_identities_based_on_cellgroup_1vall.txt")

arcvmhannoext <- copy(arcvmhanno)
## simplify these by removing VMH/ARC and underscores; asterisk-ize so the gene names  can be italiczed in ggplot elements; remove vmh and arc from the names but add a temporary column here so we know they're VMH and ARC for mapping onto the de result sets
arcvmhanno[,subclus_domain:=gsub(subclus_annot,pattern="^(VMH)_.*$",replacement="\\1")]
arcvmhanno[,subclus_annot:=gsub(subclus_annot,pattern="VMH_",replacement="")]

arcvmhanno[subclus_domain!="VMH",subclus_domain:=gsub(subclus_annot,pattern="^(ARC)_.*$",replacement="\\1")]
arcvmhanno[,subclus_annot:=gsub(subclus_annot,pattern="ARC_",replacement="")]

arcvmhanno[,subclus_annot:=gsub(subclus_annot,pattern="_",replacement=" ")]
arcvmhanno[,subclus_annot:=gsub(subclus_annot,pattern="-Mixed",replacement=" Mixed")]
arcvmhanno[subclus_annot=="Lateral-Border",subclus_annot:="xVMH Lateral Border"]

arcvmhanno[subclus_annot=="CRHR2",subclus_annot:="*CRHR2*"]
arcvmhanno[subclus_annot=="LAMP5",subclus_annot:="*LAMP5*"]

arcvmhanno[subclus_annot=="AGRP",subclus_annot:="*AGRP*"]
arcvmhanno[subclus_annot=="TAC3-ESR1",subclus_annot:="*TAC3*-*ESR1*"]
arcvmhanno[subclus_annot=="POMC-Oligo Mixed",subclus_annot:="*POMC*-Oligo"]
arcvmhanno[subclus_annot=="SLC17A7-Glia Mixed",subclus_annot:="*SLC17A7*-Glia Mixed"]
arcvmhanno[subclus_annot=="GAL-TRH-GHRH",subclus_annot:="*GAL*-*TRH*-*GHRH*"]

## append plot name column and save
arcvmhannoext <- merge.data.table(arcvmhannoext,arcvmhanno,by="bjm_annot")
setnames(arcvmhannoext,c("subclus_annot.x","subclus_annot.y"),c("dom.clus","plotclusname"))

fwrite(arcvmhannoext,"manuscript_plot_code/xARCxVMH_cluster_detailedlabs_andplotformatnames.txt",sep='\t',quote=F,row.names=F)
```
