---
title: "MultipleFigs-write_visiumdomain_and_Xenium_VMHARC_celltype_colorpalettes"
output: html_document
date: "2024-09-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())
```

```{r}
pals <- list()
# domain boundary and visium spot color pal
pal <- c("#8c63cf","#5dd959","#A9A7A9")
names(pal) <- c("VMH","ARC","Other")

# cell type palettes
vmhpal <- c("#8c63cf", "darkgray", "#6A0D53", "#AD260D")
names(vmhpal) <- c("*SLC17A6*-*CRHR2*","VMH-Glia Mixed","*FEZF1*-*LAMP5*-*NRGN*","*HCRT*-*SLC6A3*-*TAC1*")

arcpal <- c("#5dd959","#296656","#09979B","#A997AB","#D0B")
names(arcpal) <-  c("*AGRP*","*POMC*-Oligo Mixed","*GAL*-*TRH*-*GHRH*","*SLC17A7*-Glia Mixed","*TAC3*-*AR*-*ESR1*")

pals[[1]] <- pal
pals[[2]] <- vmhpal
pals[[3]] <- arcpal

names(pals) <- c("Domains","XenVMH","XenARC")
```

## xenium cell GROUPs
```{r}
xenpal <- c("#8c63cf","#5dd959" , "#F59B26", "#D193FE","#FB479F","#E9DF00DF" ,"#A9A7A9","#00B3FD","#3D4047","#FF0DF7","#AD260D")
names(xenpal) <- c("VMH (4)",
                   "ARC (5)",
                   "Oligo (4)",
                   "PeriVN (Excitatory) (1)",
                   "Other GABAergic Neurons (2)",
                   "Astro (2)",
                   "Tanycytes, Portal Vasc. (4)",
                   "Vascular and Peripheral Immune (5)",
                   "SON (2)",
                   "Non-SON AVP+OXT+ (1)",
                   "Microglia (3)")
pals[["xen_cellgroups"]] <- xenpal
```

save
```{r}
saveRDS(pals,"manuscript_plot_code/domain_and_xencluster_palettes_CHECKPALNAMESBEFOREUS.RDS")
```

## visium biological cluster labels (14 clusters):
### also save the prior palette for quick loadup
```{r}
fullpal <- c("#8c63cf", "#169482" ,"#5dd959" , "#6A0D53","#F70022", "#F59B26", "#D1CA1C", "#551CFD", "#D193FE", "#3D4047", "#AD260D","#FF0DF7","#00B3FD","#FB479F")
# the fifteenth color is not represented in our figure 1 sample, which doesn't have one of the domains; since fig 1 is the only place we're using this palette just make that 15th color label whatever
names(fullpal) <- c("VMH.1","ARC.1","ARC.2","VMH.2","OT.1","OT.2","OT.3","GABA.1","PeriVN","SON","Vascular","Astro","Portal Vasc.","GABA.2")
saveRDS(fullpal,"manuscript_plot_code/14color_palette.RDS")
```


