---
title: "07-Sex DEG hypergeometric tests for GWAS gene sets"
author: "Bernard Mulvey"
date: "2024-01-13"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
require(colorout)
source("~/.R/calc_tau_for_cellOrTissueSpecificity_metric.R")
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(hypeR)


theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

```{r}
degs <- fread("data/09-Sex DE/01b-dreamlet-ranfx_nnsvg10-HmnylmbNA-BS-15-singleClusts.txt")

un <- fread("raw-data/Genesets from GWAS pubs, TWAS, and disgenet/nonredundant_union_set_genesymbols.txt")

i <- 1
for (i in c(1:30)){
    if (i<16){
        dom <- paste0("X",i)
        domname <- paste0(dom,"_MaleUp")
    }
    else{
        d <- i-15
        dom <- paste0("X",d)
        domname <- paste0(dom,"_FemUp")
    }
    
    curde <- degs[assay==dom]
    
    if (i<16){
        cursig <- curde[adj.P.Val<0.05&logFC>0,gene_name]
    }
    else {
        cursig <- curde[adj.P.Val<0.05&logFC<0,gene_name]
    }
    
    j<-1
    tmplists <- list()
    
    for (j in c(1:length(unique(un$dx)))){
        curdx <- unique(un$dx)[j]
        # subset disease genes to shared genes with the DE analysis
        curdxset <- un[dx==curdx&symbol %in% unique(curde$gene_name),symbol]
        tmplists[[j]] <- curdxset
}
names(tmplists) <- unique(un$dx)
tmpres <- hypeR::hypeR(signature=cursig,genesets=tmplists,background = nrow(curde)-length(cursig),test = "hypergeometric")
tmpres2 <- as.data.table(tmpres$data)
tmpres2[,spdomain_sex:=domname]

if(i==1){resdat <- copy(tmpres2)}
else{resdat <- rbind(resdat,tmpres2)}
rm(tmpres2,tmpres,tmplists,curdx,cursig,curde)
}

i<-1
for (i in c(1:4)){
    reslist[[i]][,genesource:=names(dissets)[i]]
    curres <- reslist[[i]]
    if(i==1){
        allres <- copy(curres)
    }
    else{
        allres <- rbind(allres,curres)
    }
}

fwrite(resdat,"data/11-GSEA/07-hypergeometric enrichment for FDR-sig sex DEGs per k15 cluster in neuropsych GWAS-TWAS-litmined union sets.txt",sep="\t",quote=F)
```

```{r}


```
