---
title: "01-plot domain-specific nnSVG overlaps with primary cilium curated gene sets
  (SCGSv2)"
author: "Bernard Mulvey"
date: "2024-02-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")

## change write.table to output a TSV without quotes or rownames by default
library(default)
default(write.table) <- list(row.names=F,col.names=T,sep='\t',quote=F)

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc
library(parallelly)
options(parallelly.supportsMulticore.disableOn="")
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost="localhost")

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```


### similar for nnSVG genes: plot bins of top n svgs and cumulative # of genes in the SCGSv2 gene sets
```{r}
# get all gene ids in the original SPE
hyp2 <- readRDS("data/03-QC_filters/hypN9_umi275_gene166_chrm50_lognorm_111723.RDS")

hyp2g <- rownames(hyp2)
rm(hyp2)
gc(full=T)
###
# get SCGSv2 genes and also make a union set
scgs <- fread("data/11-GSEA/10a-SCGSv2 first and second order genes.txt")
setnames(scgs,c("ens","gene","classif"))

# make a list object of identifiers per  gene set
# we can map these back to the msigdb table later for reference purposes by their list name (gs_name)...
sets <- split(scgs$ens,scgs$classif)
sets[[3]] <- scgs$ens
names(sets)[3] <- "all"
###

# get domain nnSVG results and subset to genes nomsig in ≥3 samples
arcsvg <- fread("data/08-Nucleus-specific SVGs/02b-ARC nnSVG nomsig genes and ranks per sample.txt")
vmhsvg <- fread("data/08-Nucleus-specific SVGs/01b-VMH nnSVG nomsig genes and ranks per sample.txt")

setorderv(arcsvg,"meanrank")
setorderv(vmhsvg,"meanrank")

arcsvg <- arcsvg[nsigsamps>2]
vmhsvg <- vmhsvg[nsigsamps>2]
#

# test each set in each regions SVGs

res <- list(list(),list(),list())
names(res) <- names(sets)

i <- 1
for (i in c(1:2)){
    if(i==1){cursvg <- copy(arcsvg)
        svgname <- "arc"}

    else{cursvg <- copy(vmhsvg)
        svgname <- "vmh"}
    
    j<-1
    for (j in c(1:3)){
        curset <- sets[[j]]
        cursetname <- names(sets)[j]
        
        k <- 1
        for (k in c(1:floor(nrow(cursvg)/10))){
            curin <- nrow(cursvg[c(1:(k*10))][gene_id %in% curset])
            if(k==1){nin <- curin}
            else{nin <- c(nin,curin)}
            
            
        }
        ol <- as.data.table(cbind(seq(10,10*floor(nrow(cursvg)/10),10),nin))
        addnl <- as.data.frame(matrix(nrow=1,ncol=2))
        colnames(addnl) <- colnames(ol)
        addnl[1,] <- c(0,0)
        ol <- as.data.table(rbind(addnl,ol,use.names=F))
        setnames(ol,c("bin","n"))
        
        ol[,reg:=svgname]
        
        res[[j]][[i]] <- ol
        names(ol[[j]])[i] <- svgname
            
        rm(ol,curin,nin,k,curset,cursetname)
    }
    rm(cursvg,svgname,j)
}


# one plot per gene set
i<-1
plts <- list()
for (i in c(1:3)){
    pltdat <- rbindlist(res[[i]])
    plts[[length(plts)+1]] <- ggplot(pltdat,aes(x=bin,y=n,col=reg)) +
            geom_line(linewidth=1.5) + 
            ggtitle(paste0("SCGSv2 ",names(res)[i], " order genes"))+
            xlab(paste0("Top n mean-ranked SVGs"))+
            ylab("Cumulative # of SVGs\n in SCGSv2 gene set")+
            ylim(0,length(sets[[i]]))+
            geom_hline(yintercept = sum(sets[[i]] %in% hyp2g),linetype="dashed",color="red")+
            theme(title = element_text(size=10,hjust=0.5),axis.text=element_text(size=8),axis.title=element_text(size=9))
}

do.call("grid.arrange",c(plts,nrow=2))
```
