---
title: "04-Pseudopseudobulk Spatial Reps by Cluster before final lib size normalization"
author: "Bernard Mulvey"
date: "2023-06-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(ggspavis)
library(scater)
library(scran)
library(edgeR)
library(jaffelab)
library(PCAtools) # findElbowPoint

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```


### Load SPE with vmh already annotated and set up
```{r}
hyp2.vmh <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_061323_HarmonyBSpc-q2VMH_rowname-key.RDS")

# change/ensure colnames/colData's rownames == colData()$keys
colnames(hyp2.vmh) <- colData(hyp2.vmh)$key

## add demographics
demos <- fread("raw-data/demos.txt")
tmpcd <- as.data.table(colData(hyp2.vmh),keep.rownames=T)
tmpcd <- merge.data.table(tmpcd,demos,by.x="brnum",by.y="BrNum")
tmpcd <- as.data.frame(tmpcd)
rownames(tmpcd) <- tmpcd$rn
tmpcd$rn <- NULL
tmpcd <- tmpcd[colnames(hyp2.vmh),]


colData(hyp2.vmh) <- DataFrame(tmpcd) 
stopifnot(identical(colnames(hyp2.vmh),rownames(colData(hyp2.vmh))))
rm(tmpcd)
```

Comparative Approach #2: Pseudobulk spots for a given cluster by donor, rather than sample --> single input pseudobulk sample per donor, with read depth difference offset by edgeR library size factors.
```{r}
### 8 samples across 6 donors (brnum)


### calculate sex DE results for each DONOR by pseudobulking by brain number
# gets tripped up trying to aggregate colData() cols across spots from more than one sample for some reason. disable this.
hyp2.pseu <- aggregateAcrossCells(hyp2.vmh,
                   DataFrame(is.vmh=hyp2.vmh$BSp_q2_consensus_vmh,
                             sample=hyp2.vmh$brnum),coldata.merge=F)
    

hyp2.pseu$is.vmh <- factor(hyp2.pseu$is.vmh)

# find a good expression cutoff for UNCOLLAPSED data using edgeR::filterByExpr . we'll do this by filtering on samplewise pseudobulks, and then keep the corresponding rows in our donor-bulked object.
hyp2.pseu.samp <- aggregateAcrossCells(hyp2.vmh,
                   DataFrame(is.vmh=hyp2.vmh$BSp_q2_consensus_vmh,
                             sample=hyp2.vmh$sample_id),coldata.merge=F)

rowData(hyp2.pseu.samp)$high_expr <- filterByExpr(hyp2.pseu.samp)
rowData(hyp2.pseu.samp)$high_expr_cl <- filterByExpr(hyp2.pseu.samp, group = hyp2.pseu.samp$is.vmh)
rowData(hyp2.pseu.samp)$high_expr_sample <- filterByExpr(hyp2.pseu.samp, group = hyp2.pseu.samp$sample)

rowData(hyp2.pseu.samp)$high_expr_clorsam <-     rowSums(cbind(rowData(hyp2.pseu.samp)$high_expr_sample,rowData(hyp2.pseu.samp)$high_expr_cl))

hyp2.pseu.samp <- hyp2.pseu.samp[rowData(hyp2.pseu.samp)$high_expr_clorsam>=1]

# subset to rows that would pass filtering on the samplewise basis
hyp2.pseu <- hyp2.pseu[rownames(hyp2.pseu) %in% rownames(hyp2.pseu.samp)]
# sanity check
stopifnot(nrow(hyp2.pseu)==nrow(hyp2.pseu.samp))
# remove temporary object
rm(hyp2.pseu.samp)

### norm factors will take care of the higher counts in the pseudobulked spatial reps    
hyp2.pseu2 <- edgeR::cpm(edgeR::calcNormFactors(hyp2.pseu), log = TRUE, prior.count = 0.1)

    #### fix dimnames, which rigtmpcdht now are changed to "sample1, sample2...":
    # colnames(hyp2.pseu)
colnames(hyp2.pseu2) <- paste0(hyp2.pseu$sample_id,"_",hyp2.pseu$is.vmh)
colnames(hyp2.pseu) <- paste0(hyp2.pseu$sample_id,"_",hyp2.pseu$is.vmh)
    
## store norm counts on spe
logcounts(hyp2.pseu) <- hyp2.pseu2

## double check
stopifnot(rownames(hyp2.pseu)==rownames(hyp2.vmh)[which(rownames(hyp2.vmh) %in% rownames(hyp2.pseu))])

## dump unneeded objs
rm(hyp2.pseu2)

## make sure variables of interest for DE modeling are present and are factors. we need to add sex back now
tmpcd <- as.data.table(colData(hyp2.pseu),keep.rownames=T)
sourcedat <- unique(as.data.table(colData(hyp2.vmh))[,.(brnum,Sex)])
tmpcd <- merge.data.table(tmpcd,sourcedat,by.x="sample",by.y="brnum")
tmpcd <- as.data.frame(tmpcd)
rownames(tmpcd) <- tmpcd$rn
tmpcd <- tmpcd[colnames(hyp2.pseu),]
colData(hyp2.pseu) <- DataFrame(tmpcd)
rm(tmpcd)

colData(hyp2.pseu)$Sex <- factor(colData(hyp2.pseu)$Sex)
colData(hyp2.pseu)$is.vmh <- factor(colData(hyp2.pseu)$is.vmh)

    
## de analyze
deres <- pseudoBulkDGE(
    hyp2.pseu,
    col.data = colData(hyp2.pseu),
    label = hyp2.pseu$is.vmh,
    design = ~Sex,
    coef="SexM",
    row.data = rowData(hyp2.pseu),
    method = "voom",
    qualities = TRUE,
    robust = TRUE
    )

deres.tab <- as.data.table(deres[[1]])
deres.tab[,group:="other"]
deres.tab <- as.data.table(rbind(deres.tab,as.data.table(deres[[2]]),fill=T))
deres.tab[is.na(group),group:="VMH"]

write.table(deres.tab,"analysis/data/H04-2cluster-consensus-VMH/Comparative DE approaches/Pseudobulking per donor/sex DE results by cluster, as table.txt",sep='\t',quote=F,row.names=F,col.names=T)

saveRDS(deres,"analysis/data/H04-2cluster-consensus-VMH/Comparative DE approaches/Pseudobulking per donor/sex DE output.RDS")

View(deres.tab[group=="other"&adj.P.Val<0.1])
## again, two autosomal sex DE genes at FDR<0.1 : TAC1 (3/4 leave-one-out approaches), PWP2 (4/4 leave-one-out approaches)
```

Now, repeat the whole kit and kaboodle excluding the male sample that has some very lackluster clustering, etc going on.
```{r}
hyp2.vmh <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_061323_HarmonyBSpc-q2VMH_rowname-key.RDS")

# change/ensure colnames/colData's rownames == colData()$keys
colnames(hyp2.vmh) <- colData(hyp2.vmh)$key

## add demographics
demos <- fread("raw-data/demos.txt")
tmpcd <- as.data.table(colData(hyp2.vmh),keep.rownames=T)
tmpcd <- merge.data.table(tmpcd,demos,by.x="brnum",by.y="BrNum")
tmpcd <- as.data.frame(tmpcd)
rownames(tmpcd) <- tmpcd$rn
tmpcd$rn <- NULL
tmpcd <- tmpcd[colnames(hyp2.vmh),]


colData(hyp2.vmh) <- DataFrame(tmpcd) 
stopifnot(identical(colnames(hyp2.vmh),rownames(colData(hyp2.vmh))))
rm(tmpcd)

# remove iffy sample
hyp2.vmh <- hyp2.vmh[,which(hyp2.vmh$sample_id!="V12D07-075_B1")]

### Comparative Approach #2 redux: Pseudobulk spots for a given cluster by donor, rather than sample --> single input pseudobulk sample per donor, with read depth difference offset by edgeR library size factors. Nothing different to be done here relative to before.

### 8 samples across 5 donors (brnum)


### calculate sex DE results for each DONOR by pseudobulking by brain number
# gets tripped up trying to aggregate colData() cols across spots from more than one sample for some reason. disable this.
hyp2.pseu <- aggregateAcrossCells(hyp2.vmh,
                   DataFrame(is.vmh=hyp2.vmh$BSp_q2_consensus_vmh,
                             sample=hyp2.vmh$brnum),coldata.merge=F)
    

hyp2.pseu$is.vmh <- factor(hyp2.pseu$is.vmh)

# find a good expression cutoff for UNCOLLAPSED data using edgeR::filterByExpr . we'll do this by filtering on samplewise pseudobulks, and then keep the corresponding rows in our donor-bulked object.
hyp2.pseu.samp <- aggregateAcrossCells(hyp2.vmh,
                   DataFrame(is.vmh=hyp2.vmh$BSp_q2_consensus_vmh,
                             sample=hyp2.vmh$sample_id),coldata.merge=F)

rowData(hyp2.pseu.samp)$high_expr <- filterByExpr(hyp2.pseu.samp)
rowData(hyp2.pseu.samp)$high_expr_cl <- filterByExpr(hyp2.pseu.samp, group = hyp2.pseu.samp$is.vmh)
rowData(hyp2.pseu.samp)$high_expr_sample <- filterByExpr(hyp2.pseu.samp, group = hyp2.pseu.samp$sample)

rowData(hyp2.pseu.samp)$high_expr_clorsam <-     rowSums(cbind(rowData(hyp2.pseu.samp)$high_expr_sample,rowData(hyp2.pseu.samp)$high_expr_cl))

hyp2.pseu.samp <- hyp2.pseu.samp[rowData(hyp2.pseu.samp)$high_expr_clorsam>=1]

# subset to rows that would pass filtering on the samplewise basis
hyp2.pseu <- hyp2.pseu[rownames(hyp2.pseu) %in% rownames(hyp2.pseu.samp)]
# sanity check
stopifnot(nrow(hyp2.pseu)==nrow(hyp2.pseu.samp))
# remove temporary object
rm(hyp2.pseu.samp)

### norm factors will take care of the higher counts in the pseudobulked spatial reps    
hyp2.pseu2 <- edgeR::cpm(edgeR::calcNormFactors(hyp2.pseu), log = TRUE, prior.count = 0.1)

    #### fix dimnames, which rigtmpcdht now are changed to "sample1, sample2...":
    # colnames(hyp2.pseu)
colnames(hyp2.pseu2) <- paste0(hyp2.pseu$sample_id,"_",hyp2.pseu$is.vmh)
colnames(hyp2.pseu) <- paste0(hyp2.pseu$sample_id,"_",hyp2.pseu$is.vmh)
    
## store norm counts on spe
logcounts(hyp2.pseu) <- hyp2.pseu2

## double check
stopifnot(rownames(hyp2.pseu)==rownames(hyp2.vmh)[which(rownames(hyp2.vmh) %in% rownames(hyp2.pseu))])

## dump unneeded objs
rm(hyp2.pseu2)

## make sure variables of interest for DE modeling are present and are factors. we need to add sex back now
tmpcd <- as.data.table(colData(hyp2.pseu),keep.rownames=T)
sourcedat <- unique(as.data.table(colData(hyp2.vmh))[,.(brnum,Sex)])
tmpcd <- merge.data.table(tmpcd,sourcedat,by.x="sample",by.y="brnum")
tmpcd <- as.data.frame(tmpcd)
rownames(tmpcd) <- tmpcd$rn
tmpcd <- tmpcd[colnames(hyp2.pseu),]
colData(hyp2.pseu) <- DataFrame(tmpcd)
rm(tmpcd)

colData(hyp2.pseu)$Sex <- factor(colData(hyp2.pseu)$Sex)
colData(hyp2.pseu)$is.vmh <- factor(colData(hyp2.pseu)$is.vmh)

    
## de analyze
deres <- pseudoBulkDGE(
    hyp2.pseu,
    col.data = colData(hyp2.pseu),
    label = hyp2.pseu$is.vmh,
    design = ~Sex,
    coef="SexM",
    row.data = rowData(hyp2.pseu),
    method = "voom",
    qualities = TRUE,
    robust = TRUE
    )

deres.tab <- as.data.table(deres[[1]])
deres.tab[,group:="other"]
deres.tab <- as.data.table(rbind(deres.tab,as.data.table(deres[[2]]),fill=T))
deres.tab[is.na(group),group:="VMH"]

write.table(deres.tab,"analysis/data/H04-2cluster-consensus-VMH/Comparative DE approaches/Pseudobulking per donor/sex DE results by cluster, as table without male V12D07-075B1.txt",sep='\t',quote=F,row.names=F,col.names=T)

saveRDS(deres,"analysis/data/H04-2cluster-consensus-VMH/Comparative DE approaches/Pseudobulking per donor/sex DE output without male V12D07-075B1.RDS")

View(deres.tab[group=="other"&adj.P.Val<0.1])
## again, two autosomal sex DE genes at FDR<0.1 : TAC1 (3/4 leave-one-out approaches), PWP2 (4/4 leave-one-out approaches)
```
