---
title: "03a-Plot ARC3type-VMH"
output: html_document
date: "2024-07-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(ggrastr)
library(ggtext) # for newlines in titles

## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
##

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc. seemed to need this a couple times, but otherwise havent so its here as a preventative measure.
library(parallelly)
options(parallelly.supportsMulticore.disableOn="")
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost="localhost")

## ggplot defaults
theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```


read in tables of VMH/ARC probabilities per cell determined by 2 step KNN smoothing with the three core ARC cell types considered alone
```{r}
arcvmh3 <- fread("processed-data/07_Domains-subdomains_by_knnSmoothing_Banksytypes/03a-Alt_2stepKNN-ARCVMH_ARC-no-X19-no-X23.txt")
```

## conveniently, we don't even need to read in the SFE to plot from these, since we have X, Y and KNN prediction outputs.
```{r}
threshes <- seq(0.0,1,by=0.1)
### make combinations of thresholds
threshtab <- expand.grid(threshes,threshes)
threshtab <- as.data.table(threshtab)
setnames(threshtab,c("ARCthresh","VMHthresh"))
## parallelize using SOCK with snowparam, which requires us to manually specify contents to clone to each worker. this avoids colliding changes to the source data.tables by spawning totally siloed processes

bplapply(1:nrow(threshtab),BPPARAM=SnowParam(11,type = "SOCK"),BPOPTIONS = bpoptions(exportglobals = T,packages = c("data.table","ggplot2","ggrastr","ggtext","gridExtra"),exports = c("threshtab","arcvmh3")),FUN=function(t){
    ## make a copy of the data.table since the in-place modifications will collide across multicoreparam threads and error out
    arcvmh3 <- copy(arcvmh3)
    thra <- threshtab[t,ARCthresh]
    thrv <- threshtab[t,VMHthresh]
    
    ## assign based on current thresholds
    arcvmh3[,newcol:=ifelse(VMHpred_thresh1_0.2_smooth2.k200>thrv,yes="VMH",no="other")]
    arcvmh3[,newcol2:=ifelse(ARCpred_thresh1_0.1_smooth2.k500>thra,yes="ARC",no="other")]
    ## resolve dual labels
    arcvmh3[,newcol3:="other"]
    arcvmh3[newcol=="VMH",newcol3:="VMH"]
    arcvmh3[newcol2=="ARC",newcol3:="ARC"]
    arcvmh3[newcol=="VMH"&newcol2=="ARC",newcol3:=ifelse(VMHpred_thresh1_0.2_smooth2.k200>ARCpred_thresh1_0.1_smooth2.k500,yes="VMH",no="ARC")]
    ##
    
    dualassignname <- paste0("VMH_",thrv,"_ARC3type_",thra)
    setnames(arcvmh3,"newcol3",dualassignname)
    
    dompal <- c("#890090","#22dd00","#888888")
    
    names(dompal) <- c("ARC","VMH","other")
    
    ## iterate over samples -> list of vmh plots per thresh -> gridExtra that
    plts <- lapply(unique(arcvmh3$sample_id),function(s){
        xl <- min(arcvmh3[sample_id==s,xcoord])
        xh <- max(arcvmh3[sample_id==s,xcoord])
        yl <- min(arcvmh3[sample_id==s,ycoord])
        yh <- max(arcvmh3[sample_id==s,ycoord])
        plt <- ggplot(arcvmh3[sample_id==s], aes(x=xcoord, y=ycoord, color=.data[[dualassignname]])) +
            rasterize(geom_point(size=0.575)) + 
            scale_color_manual(values = dompal) +
            ggtitle(paste0(s," ",dualassignname))+
            theme_minimal()+
            theme(title = element_markdown(size=20,hjust=0.5))+
            xlim(xl,xh)+
            ylim(yl,yh)
        return(plt)
    })
    png(paste0("plots/07_Domains-subdomains_by_knnSmoothing_Banksytypes/03a-ARC-VMH_domains_3arcCelltypes_by_thresh/03a-VMH_k200_grthn_",thrv,"_ARC3type_k500_grthn_",thra,".png"),width=4000,height=4000)
    do.call("grid.arrange",c(plts,ncol=4))
    dev.off()
    
    
})
```

### refine these in the range of 0.1-0.3 (VMH) and 0.5-0.7 (ARC)
```{r}
arct <- seq(0.2,0.4,by=0.025)
vmht <- seq(0.1,0.3,by=0.025) 


threshtab <- expand.grid(arct,vmht)
threshtab <- as.data.table(threshtab)

setnames(threshtab,c("ARCthresh","VMHthresh"))

## drop pairs redundant with previous plots (exact tenths for both)
threshtab <- threshtab[!(ARCthresh %in% c(0.5,0.6,0.7)&VMHthresh %in% c(0.1,0.2,0.3))]


bplapply(1:nrow(threshtab),BPPARAM=SnowParam(11,type = "SOCK"),BPOPTIONS = bpoptions(exportglobals = T,packages = c("data.table","ggplot2","ggrastr","ggtext","gridExtra"),exports = c("threshtab","arcvmh3")),FUN=function(t){
    ## make a copy of the data.table since the in-place modifications will collide across multicoreparam threads and error out
    arcvmh3 <- copy(arcvmh3)
    thra <- threshtab[t,ARCthresh]
    thrv <- threshtab[t,VMHthresh]
    
    ## assign based on current thresholds
    arcvmh3[,newcol:=ifelse(VMHpred_thresh1_0.2_smooth2.k200>thrv,yes="VMH",no="other")]
    arcvmh3[,newcol2:=ifelse(ARCpred_thresh1_0.1_smooth2.k500>thra,yes="ARC",no="other")]
    ## resolve dual labels
    arcvmh3[,newcol3:="other"]
    arcvmh3[newcol=="VMH",newcol3:="VMH"]
    arcvmh3[newcol2=="ARC",newcol3:="ARC"]
    arcvmh3[newcol=="VMH"&newcol2=="ARC",newcol3:=ifelse(VMHpred_thresh1_0.2_smooth2.k200>ARCpred_thresh1_0.1_smooth2.k500,yes="VMH",no="ARC")]
    ##
    
    dualassignname <- paste0("VMH_",thrv,"_ARC3type_",thra)
    setnames(arcvmh3,"newcol3",dualassignname)
    
    dompal <- c("#890090","#22dd00","#888888")
    
    names(dompal) <- c("ARC","VMH","other")
    
    ## iterate over samples -> list of vmh plots per thresh -> gridExtra that
    plts <- lapply(unique(arcvmh3$sample_id),function(s){
        xl <- min(arcvmh3[sample_id==s,xcoord])
        xh <- max(arcvmh3[sample_id==s,xcoord])
        yl <- min(arcvmh3[sample_id==s,ycoord])
        yh <- max(arcvmh3[sample_id==s,ycoord])
        plt <- ggplot(arcvmh3[sample_id==s], aes(x=xcoord, y=ycoord, color=.data[[dualassignname]])) +
            rasterize(geom_point(size=0.575)) + 
            scale_color_manual(values = dompal) +
            ggtitle(paste0(s," ",dualassignname))+
            theme_minimal()+
            theme(title = element_markdown(size=20,hjust=0.5))+
            xlim(xl,xh)+
            ylim(yl,yh)
        return(plt)
    })
    png(paste0("plots/07_Domains-subdomains_by_knnSmoothing_Banksytypes/03a-ARC-VMH_domains_3arcCelltypes_by_thresh/03a-Hone-in_VMH_k200_grthn_",thrv,"_ARC3type_k500_grthn_",thra,".png"),width=4000,height=4000)
    do.call("grid.arrange",c(plts,ncol=4))
    dev.off()
    
    
})
```

## reproducibility info
```{r}
sessionInfo()
sessioninfo::session_info()
```
