---
title: "03-PRECAST markers"
author: "Bernard Mulvey"
date: "2023-06-13"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(ggplot2)
library(data.table)
library(Biostrings)
library(gridExtra)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(ggspavis)
library(scater) # addPerCellQC
library(BiocParallel)
library(scran)
library(parallel)
# library(scCustomize)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

load required files
```{r}
hyp2 <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_053123.RDS")
colnames(hyp2) <- colData(hyp2)$key
rownames(hyp2) <- rowData(hyp2)$gene_name


pcsts <- readRDS("analysis/data/H02-clustering/04c-PRECAST_clusters_hvg1020_nnsvg1020_k9-15-20-31.RDS")
### drop those with clearly evident batch fx occuring by spotplots: all k31, and SVG10 k9 which is not very clean in terms of assignments.

pcsts <- pcsts[grep(names(pcsts),pattern="k31|svg10_k9",invert=T)]
```

```{r}
bpparam <- MulticoreParam(workers=6)
register(bpparam)
pc.markers <- bplapply(pcsts,BPPARAM=bpparam,FUN=function(x){
    y <- as.data.frame(x)
    rownames(y) <- y$rn
    # safeguard against reordered rows
    if((sum(rownames(colData(hyp2))==rownames(y)))!=ncol(hyp2)){
        y <- y[rownames(colData(hyp2)),]
    }
    # row names as gene symbols for sanity
    colLabels(hyp2) <- factor(y$label)
    rm(y)
    gc(full=T)
    
    multistat <- scoreMarkers(hyp2,colLabels(hyp2),full.stats=T)
})
names(pc.markers) <- names(pcsts)

## cut to top 2500 for any rank
pc.markers2 <- bplapply(pc.markers,BPPARAM = bpparam, FUN=function(x){
    y <- lapply(x,FUN=function(x){
        x <- as.data.table(x,keep.rownames=T)
        x[rank.logFC.cohen<=2500|rank.AUC<=2500|rank.logFC.detected<=2500]
    })
})

saveRDS(pc.markers2,"analysis/data/H03-marker_genes/PRECAST_HVG1020-SVG1020_q9-15-20_scoremarkers_out.RDS")

```

### Extract top 10 rank gene(s) (genes with FDR = minimum FDR for cluster) per cluster per cluster set into plaintext tabular format
```{r}
### only core stats here
keepnames <- grep(names(pc.markers2[[1]][[1]]),pattern="full",value=T,invert=T)
# colname rn will be created in each iter of the loop below 

i<-1
for (i in c(1:length(pc.markers2))){
    k<-1
    for (k in c(1:length(pc.markers2[[i]]))){
        tmp <- as.data.frame(pc.markers2[[i]][[k]])
        tmp <- as.data.table(tmp,keep.rownames=T)
        tmp <- tmp[,..keepnames]
        tmp <- tmp[rank.logFC.cohen<=10|rank.AUC<=10|rank.logFC.detected<=10]
        tmp[,cluster_set:=names(pc.markers2)[i]]
        tmp[,cluster:=names(pc.markers2[[i]])[k]]
        setnames(tmp,"rn","gene")
        if(i==1&k==1){
            pc.markers.plt <- tmp
        }
        else{
            pc.markers.plt <- rbind(pc.markers.plt,tmp)
        }
        rm(tmp)
    }
    rm(k)
}
rm(i)

write.table(pc.markers.plt,"local_results_ref/topRanks_markers_hvg1020-svg1020-PRECAST_q9-15-20.txt",sep='\t',quote=F,row.names=F,col.names=T)
```
