---
title: "02-BSpace hvg, svg q9-15-20-31 clusterings marker genes"
author: "Bernie Mulvey"
date: "2023-06-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(ggplot2)
library(data.table)
library(Biostrings)
library(gridExtra)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(ggspavis)
library(scater) # addPerCellQC
library(BiocParallel)
library(scran)
library(parallel)
library(spatialLIBD)
# library(scCustomize)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

load required files
```{r}
# spe w lognormed counts, THEN cropped bad sample
hyp2 <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_D07-075_B1 crop 070223.RDS")
colnames(hyp2) <- colData(hyp2)$key
rownames(hyp2) <- rowData(hyp2)$gene_name

# drop repeat instances of gene names
drops <- as.data.table(rownames(hyp2))[,.N,by="V1"]
keeprows <- drops[N==1,V1]
hyp2 <- hyp2[rownames(hyp2) %in% keeprows,]
rm(drops,keeprows)

bscl <- list.files("analysis/data/spe_053123/H02-clustering/03-bs_harmony_hvg1020_nnsvg1020_9-15-20-31_out",pattern=".txt",full.names = T)

bscls <- lapply(bscl,FUN=fread)
names(bscls) <- gsub(bscl,pattern="^.*9-15-20-31_out\\/BSpace_Harmony_(.*)\\.txt$",replacement="\\1")
```

## Use spatialLIBD registration_wrapper, extract just the "enrichment" part of the results, save as a list object per clustering set


```{r}
bs.markers <- list()
i<-1
for (i in c(11:16)){
    x <- bscls[[i]]
    y <- x[rn %in% colnames(hyp2)]
    y <- DataFrame(x)
    rownames(y) <- y$rn
    colnames(y)[2] <- "cl"
    y <- y[colnames(hyp2),]
    y$cl <- paste0("X",y$cl)
    colLabels(hyp2) <- as.factor(y$cl)
    
    ### filter out sample-cluster pairs that won't pass inclusion in slibd
    tab <- as.data.table(table(hyp2$sample_id,hyp2$label))
    tab <- dcast(tab,V2~V1,value.var = "N")
    # subset to clusters with at least 10 cells in at least 3 samples
    tab[,sum:=rowSums(tab[,.SD>=10,.SDcols=c(2:ncol(tab))])]
    # subsetting contd: for >=3 samples meeting the criterion
    tab <- tab[sum>2]
    ## fastest way to subset: make unique sample-cluster ids in both datasets and filter sce to it 
    tab2 <- melt(tab,id.vars="V2",measure.vars=c(2:(ncol(tab)-1)))
    tab2 <- tab2[value>=10]
    tab2[,sampclus:=paste0(variable,V2)]
    
    hyp2$sampclus <- paste0(hyp2$sample_id,hyp2$label)
    hyp2.2 <- hyp2[,hyp2$sampclus %in% unique(tab2$sampclus)]
    
    hyp2.2$label <- droplevels(hyp2.2$label)
    
    bs.markers[[i]] <- spatialLIBD::registration_wrapper(hyp2.2,var_registration = "label",var_sample_id = "sample_id",gene_ensembl = "gene_id",gene_name = "gene_name",min_ncells = 10)
    rm(hyp2.2)
}

bs.markers <- lapply(bs.markers,FUN=function(x){
    return(as.data.table(x[["enrichment"]],keep.rownames=T))
})

names(bs.markers) <- names(bscls)


saveRDS(bs.markers,"analysis/data/spe_053123/H03-marker_genes/04-BSpace_HVG1020-SVG1020_q9-15-20-31_sLIBD-regwrapper-enrichment-res.RDS")

```
