---
title: "02-Spatial Registration of Allen Mouse Whole Brain Yao23 HYP Subclasses and
  Supertypes to HYP"
author: "Bernard Mulvey"
date: "2023-08-12"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
require(colorout)
library(magrittr)
library(job)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

```{r}
job({hyp2 <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_D07-075_B1 crop 070223.RDS")
    job::export(hyp2)})

bscl <- fread("analysis/data/spe_053123/H02-clustering/03-bs_harmony_hvg1020_nnsvg1020_9-15-20-31_out/BSpace_Harmony_nnsvg10pctile_15.txt")

bscl <- bscl[rn %in% colnames(hyp2)]
setnames(bscl,2,"clust")
bscl <- DataFrame(bscl)
rownames(bscl) <- bscl$rn
bscl <- bscl[colnames(hyp2),]
colLabels(hyp2) <- as.factor(paste0("X",bscl$clust))

### set rownames to gene symbols for compatibility with single cell from different species (different ENS gene IDs)
rownames(hyp2) <- rowData(hyp2)$gene_name

hyp_model_res <- registration_wrapper(hyp2,var_registration = "label",var_sample_id = "sample_id",gene_ensembl = "gene_name",gene_name = "gene_name")

### and with collapsed VMH, ARC clusters
hyp2$label <- as.character(hyp2$label)
hyp2$label[which(hyp2$label %in% c("X5","X6"))] <- "VMH"
hyp2$label[which(hyp2$label %in% c("X8","X13"))] <- "ARC"
hyp2$label <- as.factor(hyp2$label)

hyp_model_res_collapsed <- registration_wrapper(hyp2,var_registration = "label",var_sample_id = "sample_id",gene_ensembl = "gene_name",gene_name = "gene_name")
```

### load and analyze subclass registration stats from mouse: SUBCLASS vs INDIVidual spatial domains

```{r}
mshyp_subclass <- readRDS("analysis/data/spe_053123/H06-Spatial Registration/ABAhyp_mincells5-n5_subclass_modelingres.RDS")

registration_stats_subclass <- mshyp_subclass$enrichment[,grep(colnames(mshyp_subclass$enrichment),pattern="^t_stat",value=T)]
colnames(registration_stats_subclass) %<>% gsub(.,pattern="^t_stat_",replacement="")

cor_subclass_perspatial <- spatialLIBD::layer_stat_cor(stats=registration_stats_subclass,modeling_results = hyp_model_res,model_type = "enrichment")
# layer_stat_cor_plot(cor_subclass,max(cor_subclass))
# dev.off()
# render this is in a parseable way
cor_subclass2 <- as.data.table(cor_subclass_perspatial,keep.rownames=T)
cor_subclass2 <- melt(cor_subclass2,id.vars="rn")
write.table(cor_subclass2,"analysis/data/spe_053123/H06-Spatial Registration/01-ABAhyp-subclass_single-HYP-spdomains.txt",sep='\t',quote=F,row.names=F,col.names=T)
# for plotting script: ggplot(cor_subclass_jts2,aes(x=rn,y=variable,fill=value))+geom_tile()+theme(axis.text.x = element_text(angle=90,size=11,hjust=1))+scale_fill_viridis_c()
```

Mouse subclass to JOINT VMH (X5,X6) and ARC (X8,X13) domains 
```{r}
cor_subclass_joints <- spatialLIBD::layer_stat_cor(stats=registration_stats_subclass,modeling_results = hyp_model_res_collapsed,model_type = "enrichment")

cor_subclass_jts2 <- as.data.table(cor_subclass_joints,keep.rownames=T)
cor_subclass_jts2 <- melt(cor_subclass_jts2,id.vars="rn")
write.table(cor_subclass_jts2,"analysis/data/spe_053123/H06-Spatial Registration/01-ABAhyp-subclass_collapsed-VMH-ARC-spdomains.txt",sep='\t',quote=F,row.names=F,col.names=T)


```
