---
title: "03-reg wrapper enrichment stats for Hu21 infant and organoid ARC"
author: "Bernard Mulvey"
date: "2023-08-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
library(zellkonverter)
library(magrittr)
require(colorout)
library(BiocParallel)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```


Data shared per corresp author by my request. Not sure what these files will look like.

### ah, seurat objects

### load counts
```{r}
load("raw-data/ARC_infant_and_organoid_human_Hu21/HuHypo.ARCNeurons.Metadata.RData")
arcmeta <- HuHypo.ARCNeurons.Metadata
rm(HuHypo.ARCNeurons.Metadata)

load("raw-data/ARC_infant_and_organoid_human_Hu21/HuHypo.Metadata.RData")
hypometa <- HuHypo.Metadata
rm(HuHypo.Metadata)

### are these just subsets of the same data? 
sum(rownames(arcmeta) %in% rownames(hypometa))
### yes, evidently the infant dataset (given the "patientID" column)
rm(arcmeta)

hypodat <- readRDS("raw-data/ARC_infant_and_organoid_human_Hu21/HuHypo.rds")

### convert to SCE
hypodat <- as.SingleCellExperiment(hypodat)
## add metadata
hypometa <- DataFrame(hypometa)
hypometa <- hypometa[colnames(hypodat),]

colData(hypodat) <- hypometa
```

Filter to abundant enough cells then prep for spatial reg
```{r}
tab <- as.data.table(table(hypodat$PatientID,hypodat$AllClusters))
tab <- dcast(tab,V2~V1,value.var = "N")

# subset to cell subclasses or supertypes with at least 8 cells in at least 3 samples
tab[,sum:=rowSums(tab[,.SD>=8,.SDcols=c(2:ncol(tab))])]
# subsetting for # of sample•(supertypes or subclasses)
tab <- tab[sum>2]

## fastest way to subset: make unique sample-cluster ids in both datasets and filter sce to it
tab2 <- melt(tab,id.vars="V2",measure.vars=c(2:7))
tab2 <- tab2[value>7]
tab2[,sampclus:=paste0(variable,V2)]

hypodat$sampclus <- paste0(hypodat$PatientID,hypodat$AllClusters)


hypodat2 <- hypodat[,hypodat$sampclus %in% unique(tab2$sampclus)]

# Fix variable names for compatibility
hypodat2$AllClusters <- gsub(hypodat2$AllClusters,pattern=" ",replacement="_")
hypodat2$AllClusters <- gsub(hypodat2$AllClusters,pattern="-",replacement="_")
hypodat2$AllClusters <- as.factor(hypodat2$AllClusters)

# rownames in this data are already gene symbols so no changes there.

# drop genes with two or more rows
drops <- as.data.table(rownames(hypodat))[,.N,by="V1"]
keeprows <- drops[N==1,V1]
# okay, there are none. nice

# oo, there's no rowdata at all, just make a couple columns of gene symbols to be safe

newdat <- cbind(rownames(hypodat2),rownames(hypodat2))
newdat <- DataFrame(newdat)
colnames(newdat) <- c("holdercola","holdercolb")
rownames(newdat) <- newdat$holdercola
newdat <- newdat[rownames(hypodat2),]
rowData(hypodat2) <- newdat

rm(drops,hypometa,tab,tab2,keeprows)
gc(full=T)
message("Input dataset ready. Starting spatialLIBD::registration_wrapper...")
```


```{r}
infanthyp <- registration_wrapper(hypodat2,var_registration = "AllClusters",var_sample_id = "PatientID",gene_ensembl = "holdercola",gene_name = "holdercola",min_ncells = 8)


saveRDS(infanthyp,"analysis/data/spe_053123/H06-Spatial Registration/03-Hu21-infant-HYP_mincells8-n3_allclusters_sLIBD-enrichmntmodelres.RDS")
```

Aha, they used transfer labeling to assign each cluster to an ARC/nonarc neuron or other hypothalamic cell type status. so let's also register those.

```{r}
hypodat2$arcallclust <- paste0(hypodat2$ArcuateTransfer,hypodat2$AllClusters)
hypodat2$arcallclust <- as.factor(hypodat2$arcallclust)

tab <- as.data.table(table(hypodat2$PatientID,hypodat2$arcallclust))
tab <- dcast(tab,V2~V1,value.var = "N")

# subset to cell subclasses or supertypes with at least 8 cells in at least 3 samples
tab[,sum:=rowSums(tab[,.SD>=8,.SDcols=c(2:ncol(tab))])]
# subsetting for # of sample•(supertypes or subclasses)
tab <- tab[sum>2]

## fastest way to subset: make unique sample-cluster ids in both datasets and filter sce to it
tab2 <- melt(tab,id.vars="V2",measure.vars=c(2:7))
tab2 <- tab2[value>7]
tab2[,sampclus:=paste0(variable,V2)]

hypodat2$samparcclus <- paste0(hypodat2$PatientID,hypodat2$arcallclust)
hypodat3 <- hypodat2[,hypodat2$samparcclus %in% unique(tab2$sampclus)]
## drop unused levels
hypodat3$arcallclust <- droplevels(hypodat3$arcallclust)

## ^ each cluster is separated now into whether transfer labeling identified it as arcuate or othery
infanthyp.arcnonarc <- registration_wrapper(hypodat3,var_registration = "arcallclust",var_sample_id = "PatientID",gene_ensembl = "holdercola",gene_name = "holdercola",min_ncells = 8)

saveRDS(infanthyp.arcnonarc,"analysis/data/spe_053123/H06-Spatial Registration/03-Hu21-infant-HYP_mincells8-n3_arcneuron-transferlabel-by-allclusters_sLIBD-enrichmntmodelres.RDS")


```
