---
title: "02-Plot cluster jaccards of BayesSpace q2 on hvg1020 svg1020"
author: "Bernard Mulvey"
date: "2023-06-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different

knitr::opts_knit$set(root.dir = here::here())
library(ggplot2)
library(data.table)
library(Biostrings)
library(gridExtra)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(ggspavis)
library(scater)
library(BiocParallel)
library(scran)
library(parallel)
library(Polychrome)
library(pheatmap)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```


Load req'd data
```{r}
hyp2 <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_053123.RDS") 

# change colnames/colData's rownames to keys
colnames(hyp2) <- colData(hyp2)$key
#

q2s <- list.files("analysis/data/H02-clustering/03b-BSpace_Harmony_q2",pattern=".txt",full.names = T)
q2s <- grep(q2s,pattern="png",value=T,invert=T)

q2list <- lapply(q2s,FUN=function(x){
    x <- fread(x)
    y <- as.data.frame(x)
    rownames(y) <- y$rn
    if(sum(rownames(y)==colnames(hyp2))!=ncol(hyp2)){
        y <- y[colnames(hyp2),]
    }
    y
})
names(q2list) <- gsub(q2s,pattern="^.*(bspace_k2.*)\\.txt$",replacement="\\1")
rm(q2s)

```

### set names of each table of labels to be a unique one so we can bind them all together
```{r}
i <-1
for (i in c(1:4)){
    colnames(q2list[[i]])[2] <- paste0(names(q2list)[i],"_label")
    as.data.table(q2list[[i]])
}

i<-1
for (i in c(1,3,4)){
    if (i==1){
        q2jacs <- merge.data.table(q2list[[i]],q2list[[(i+1)]],by="rn")
    }
    else{
        q2jacs <- merge.data.table(q2jacs,q2list[[i]],by="rn")
    }
}

jac_h1020 <- bluster::linkClustersMatrix(q2jacs$bspace_k2_hvg10pctile_label,q2jacs$bspace_k2_hvg20pctile_label)
# first argument is reflected in rows, second in columns
rownames(jac_h1020) <- paste0("k2_hvg10_",rownames(jac_h1020))
colnames(jac_h1020) <- paste0("k2_hvg20_",colnames(jac_h1020))

jac_h10s10 <- bluster::linkClustersMatrix(q2jacs$bspace_k2_hvg10pctile_label,q2jacs$bspace_k2_nnsvg10pctile_label)
# first argument is reflected in rows, second in columns
rownames(jac_h10s10) <- paste0("k2_hvg10_",rownames(jac_h10s10))
colnames(jac_h10s10) <- paste0("k2_nnsvg10_",colnames(jac_h10s10))

jac_h10s20 <- bluster::linkClustersMatrix(q2jacs$bspace_k2_hvg10pctile_label,q2jacs$bspace_k2_nnsvg20pctile_label)
# first argument is reflected in rows, second in columns
rownames(jac_h10s20) <- paste0("k2_hvg10_",rownames(jac_h10s20))
colnames(jac_h10s20) <- paste0("k2_nnsvg20_",colnames(jac_h10s20))

jac_h20s10 <- bluster::linkClustersMatrix(q2jacs$bspace_k2_hvg20pctile_label,q2jacs$bspace_k2_nnsvg10pctile_label)
# first argument is reflected in rows, second in columns
rownames(jac_h20s10) <- paste0("k2_hvg20_",rownames(jac_h20s10))
colnames(jac_h20s10) <- paste0("k2_nnsvg10_",colnames(jac_h20s10))

jac_h20s20 <- bluster::linkClustersMatrix(q2jacs$bspace_k2_hvg20pctile_label,q2jacs$bspace_k2_nnsvg20pctile_label)
# first argument is reflected in rows, second in columns
rownames(jac_h20s20) <- paste0("k2_hvg20_",rownames(jac_h20s20))
colnames(jac_h20s20) <- paste0("k2_nnsvg20_",colnames(jac_h20s20))
```


```{r}
### plots
pdf("plots/H04-2cluster-consensus-VMH/01-bayesspace_q2_HVGorSVG_jaccards/hvg10_hvg20.pdf",width=7,height=7)
    pheatmap(jac_h1020,cluster_cols=F,cluster_rows=F)
    dev.off()
    
pdf("plots/H04-2cluster-consensus-VMH/01-bayesspace_q2_HVGorSVG_jaccards/hvg10_svg10.pdf",width=7,height=7)
    pheatmap(jac_h10s10,cluster_cols=F,cluster_rows=F)
    dev.off()
    
pdf("plots/H04-2cluster-consensus-VMH/01-bayesspace_q2_HVGorSVG_jaccards/hvg10_svg20.pdf",width=7,height=7)
    pheatmap(jac_h10s20,cluster_cols=F,cluster_rows=F)
    dev.off()
    
pdf("plots/H04-2cluster-consensus-VMH/01-bayesspace_q2_HVGorSVG_jaccards/hvg20_svg10.pdf",width=7,height=7)
    pheatmap(jac_h20s10,cluster_cols=F,cluster_rows=F)
    dev.off()
    
pdf("plots/H04-2cluster-consensus-VMH/01-bayesspace_q2_HVGorSVG_jaccards/hvg20_svg20.pdf",width=7,height=7)
    pheatmap(jac_h20s20,cluster_cols=F,cluster_rows=F)
    dev.off()
```
