---
title: "06-Collate Marker, Sex DE GSEA (5k permutation) results"
author: "Bernard Mulvey"
date: "2023-10-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
require(colorout)
source("~/.R/calc_tau_for_cellOrTissueSpecificity_metric.R")
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")

## change write.table to output a TSV without quotes or rownames by default
library(default)
default(write.table) <- list(row.names=F,col.names=T,sep='\t',quote=F)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

```{r}
i <- 1
for (i in c(1:30)){
    clus <- paste0(ceiling(i/2))
    targfile <- ifelse(2*ceiling(i/2)==i,
                       no=list.files(
                           paste0(
                           "analysis/data/spe_053123/H08-GSEA, GO etc/H06-Domain marker, sex DEG GSEA w 5k permutations thru genepattern org/genepattern_gsea_results/sex", clus),pattern="gsea_report_for_na_pos.*\\.tsv",full.names=T),
                       yes=list.files(
                          paste0(
                              "analysis/data/spe_053123/H08-GSEA, GO etc/H06-Domain marker, sex DEG GSEA w 5k permutations thru genepattern org/genepattern_gsea_results/sex", clus),pattern="gsea_report_for_na_neg.*\\.tsv",full.names = T)
                       )

    curgse <- fread(targfile)
    curgse <- curgse[,c(1,4:11)]
    curgse[,spdomain:=paste0("X",clus)]
    curgse[,direction:=ifelse(2*ceiling(i/2)==i,
                              no="male_up",
                              yes="female_up")]
    setnames(curgse,c(5:9),c("P.Value","FDR_qval","FWER_pval","rankAtMax","leading_edge"))
    
    # join
    if (i==1){sexgse <- curgse}
    else{sexgse <- rbind(sexgse,curgse)}
    setorder(sexgse,NES)
    
    rm(curgse,targfile,clus)
}
rm(i)




fwrite(sexgse,"analysis/data/spe_053123/H08-GSEA, GO etc/H06-Domain marker, sex DEG GSEA w 5k permutations thru genepattern org/collated_dreamlet-autosom-sexDE-brnum-ranef_gsea5k_results.txt",sep='\t',quote=F)
```

```{r}
i <- 1
for (i in c(1:15)){
    clus <- paste0(i)
    targfile <- list.files(paste0("analysis/data/spe_053123/H08-GSEA, GO etc/H06-Domain marker, sex DEG GSEA w 5k permutations thru genepattern org/genepattern_gsea_results/mk", clus),pattern="gsea_report_for_na_pos.*\\.tsv",full.names=T)
    
    curgse <- fread(targfile)
    curgse <- curgse[,c(1,4:11)]
    setnames(curgse,c(5:9),c("P.Value","FDR_qval","FWER_pval","rankAtMax","leading_edge"))
    
    curgse[,spdomain:=paste0("X",clus)]
    
    # join
    if (i==1){mkgse <- curgse}
    else{mkgse <- rbind(mkgse,curgse)}
    setorder(mkgse,NES)
    
    rm(curgse,targfile,clus)
}
rm(i)

fwrite(mkgse,"analysis/data/spe_053123/H08-GSEA, GO etc/H06-Domain marker, sex DEG GSEA w 5k permutations thru genepattern org/collated_markers-slibd-enrichmentLFCranked_gsea5k_results.txt",sep='\t',quote=F)
```

### explore domains of interest
```{r}
sexgse <- sexgse[spdomain %in% paste0("X",c(5,6,8,9,13))]
sexlist <- list()
i<-1
for (i in c(1:(2*length(unique(sexgse$spdomain))))){
    clus <- unique(sexgse$spdomain)[ceiling(i/2)]
    getdir <- ifelse(2*ceiling(i/2)==i,no="male_up",yes="female_up")
    tmp <- sexgse[spdomain==clus&direction==getdir&P.Value<0.05]
    
    if(2*ceiling(i/2)==i){
        tmp[,NES:=NES*-1]
    }
    sexlist[[length(sexlist)+1]] <- tmp
    names(sexlist)[length(sexlist)] <- paste0(clus,getdir)
    rm(clus,getdir,tmp)
}

coregse <- mkgse[spdomain %in% paste0("X",c(5,6,8,9,13))]
mklist <- list()
i<-1
for (i in c(1:length(unique(coregse$spdomain)))){
    clus <- unique(coregse$spdomain)[i]
    tmp <- coregse[spdomain==clus&P.Value<0.05&NES>0]
    
    mklist[[length(mklist)+1]] <- tmp
    names(mklist)[length(mklist)] <- clus
    rm(clus,tmp)
}




```
