---
title: "0X-GWAS Gene Set Enrichments Draft Code"
author: "Bernard Mulvey"
date: "2023-08-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
require(colorout)
source("~/.R/calc_tau_for_cellOrTissueSpecificity_metric.R")
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(hypeR)


theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

```{r}
cands <- fread("~/Desktop/pilotset.txt")

dx <- unique(cands$dx)
candsets <- lapply(dx,FUN=function(x){
    return(unique(cands[dx==x,symbol]))
})
names(candsets) <- dx
intest <- degs[assay=="x5"]
intest2 <- intest[assay=="x5"&logFC>0&adj.P.Val<0.1&ID %in% candsets[[6]]]
test <- hypeR()


i <- 1
for (i in c(1:30)){
    if (i<16){
        dom <- paste0("x",i)
        domname <- paste0(dom,"_MaleUp")
    }
    else{
        d <- i-15
        dom <- paste0("x",d)
        domname <- paste0(dom,"_FemUp")
    }
    
    curde <- degs[assay==dom]

    if (i<16){
        cursig <- curde[P.Value<0.01&logFC>0,ID]
    }
    else {
        cursig <- curde[P.Value<0.01&logFC<0,ID]
    }
    
    if(length(cursig)==0){
        next(i)
    }
    
    j<-1
    tmplists <- list()
    
    for (j in c(1:6)){
        curdx <- candsets[[j]]
        curdx <- curdx[which(curdx %in% curde$ID)]
        tmplists[[j]] <- curdx
    }
    names(tmplists) <- names(candsets)
    tmpres <- hypeR::hypeR(signature=cursig,genesets=tmplists,background = nrow(curde)-length(cursig),test = "hypergeometric")
    tmpres2 <- as.data.table(tmpres$data)
    tmpres2[,spdomain_sex:=domname]
    
    if(i==1){resdat <- copy(tmpres2)}
    else{resdat <- rbind(resdat,tmpres2)}
    rm(tmpres2,tmpres,tmplists,curdx,cursig,curde)
}
```
