---
title: "Pseudobulk DE of Arc Clusters 8 vs 13"
author: "Bernard Mulvey"
date: "2023-07-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(ggspavis)
library(scater)
library(scran)
library(edgeR)
library(jaffelab)
library(PCAtools) # findElbowPoint

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

Load SPE, set spot names to coldata$key, add bayesspsace nnsvg10 k=15 labels. Crop V12D07-075-B1 down to the portion containing ISH-verified VMH. (This contains some spots of ARC clusters as well).
```{r}
hyp2 <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_053123.RDS")

colnames(hyp2) <- colData(hyp2)$key

bscl <- fread("analysis/data/spe_053123/H02-clustering/03-bs_harmony_hvg1020_nnsvg1020_9-15-20-31_out/BSpace_Harmony_nnsvg10pctile_15.txt")
bscl <- as.data.frame(bscl)
rownames(bscl) <- bscl$rn

colLabels(hyp2) <- as.factor(bscl$BShar_nnsvg10pctile_15)

### crop V12D07-075-B1 as previously
coordstmp <- as.data.frame(spatialCoords(hyp2))
rownames(coordstmp) <- colnames(hyp2)
coordstmp <- as.data.table(coordstmp,keep.rownames=T)
coordstmp <- coordstmp[,diag:=pxl_col_in_fullres+pxl_row_in_fullres]
coordstmp <- coordstmp[!(rn %in% grep(rn,pattern="V12D07-075_B1",value=T)&diag>30000)]

hyp2 <- hyp2[,colnames(hyp2)%in%coordstmp$rn]
stopifnot(dim(hyp2)[2]==nrow(coordstmp))

rm(bscl,coordstmp)

## add demographics for sample sexes
demos <- fread("raw-data/demos.txt")
tmpcd <- as.data.table(colData(hyp2),keep.rownames=T)
tmpcd <- merge.data.table(tmpcd,demos,by.x="brnum",by.y="BrNum")
tmpcd <- as.data.frame(tmpcd)
rownames(tmpcd) <- tmpcd$rn
tmpcd <- tmpcd[colnames(hyp2),]
colData(hyp2) <- DataFrame(tmpcd) 
rm(tmpcd,demos)
# load chromosome info for genes for filtering by X/Y later. (queried rownames of hyp2 in biomart human genes v 109 for this.)
chrs <- fread("raw-data/ENSG_chromosomes.txt")
allg <- as.data.table(rowData(hyp2),keep.rownames=T)
allg <- merge.data.table(allg,chrs,by.x="rn",by.y="gene_id",all.x=T)
allg <- as.data.frame(allg)
rownames(allg) <- allg$rn
allg <- DataFrame(allg)
### CRITICAL TO REORDER HERE OR GENES SOMEHOW GET MIS-LABELED LATER (easy test for this is examining DDX3Y expression spotplot in hyp2 now vs after)
allg <- allg[rownames(hyp2),]
rowData(hyp2) <- allg
### spot checks confirm gene-chr pairs are correct. chrY genes are absent in female samples up to this point.
rm(chrs,allg)
```

Going off https://github.com/LieberInstitute/spatial_DG_lifespan/blob/main/code/Pseudobulk/create_manual_annotated_pseudobulk_spe.R and https://github.com/LieberInstitute/spatial_DG_lifespan/blob/main/code/Pseudobulk/DE_pseudobulk.R

ARC clusters= #8, #13. Also run DE pseudobulking across the two clusters.
```{r}
## iterate over individual clusters and combination.
hyp2a <- hyp2[,which(hyp2$label %in% c(8,13))]
hyp2a$label <- as.numeric(hyp2a$label)
hyp2a$label <- as.factor(hyp2a$label)
hyp2_pbulk <- aggregateAcrossCells(hyp2a,
                       DataFrame(cl=hyp2a$label,
                                 sample=hyp2a$sample_id))
    
    # hyp2_pbulk$is.vmh <- factor(hyp2_pbulk$is.vmh)
    
    # find a good expression cutoff using edgeR::filterByExpr
    rowData(hyp2_pbulk)$high_expr <- filterByExpr(hyp2_pbulk)
    rowData(hyp2_pbulk)$high_expr_cl <- filterByExpr(hyp2_pbulk, group = hyp2_pbulk$label)
    rowData(hyp2_pbulk)$high_expr_sample <- filterByExpr(hyp2_pbulk, group = hyp2_pbulk$sample)
    
    rowData(hyp2_pbulk)$high_expr_clorsam <- rowSums(cbind(rowData(hyp2_pbulk)$high_expr_sample,rowData(hyp2_pbulk)$high_expr_cl))
    
    # summary(rowData(hyp2_pbulk)$high_expr)
    # summary(rowData(hyp2_pbulk)$high_expr_sample)
    # summary(rowData(hyp2_pbulk)$high_expr_cl)
    # summary(rowData(hyp2_pbulk)$high_expr_clorsam>=1)
    
    hyp2_pbulk2 <- hyp2_pbulk[rowData(hyp2_pbulk)$high_expr_clorsam>=1]
    
    ## Store the log normalized counts on the spe object
    hyp2_pbulk3 <- edgeR::cpm(edgeR::calcNormFactors(hyp2_pbulk2), log = TRUE, prior.count = 0.1)
    
    stopifnot(rownames(hyp2_pbulk3)==rownames(hyp2)[which(rownames(hyp2) %in% rownames(hyp2_pbulk3))])
    
    colnames(hyp2_pbulk3) <- paste0(hyp2_pbulk2$sample_id,"_",hyp2_pbulk2$label)
    
    colnames(hyp2_pbulk2) <- paste0(hyp2_pbulk2$sample_id,"_",hyp2_pbulk2$label)
    
    ## now actually store norm counts on spe
    logcounts(hyp2_pbulk2) <- hyp2_pbulk3
    
    # make sure variables of interest are factors

# coef = 2 = cluster13 vs. 8; + lfc == cl13 > 8, no dupCor correction
deres <- pseudoBulkDGE(
    hyp2_pbulk2,
    col.data = colData(hyp2_pbulk2),
    design = ~label,
    coef=2,
    row.data = rowData(hyp2_pbulk2),
    method = "voom",
    qualities = TRUE,
    robust = TRUE,
    label=hyp2_pbulk2$in_tissue
)

deres <- as.data.table(deres)
## try dupcor here but be weary that p values were inflated like mad before doing this for VMH
mat_formula <- eval(str2expression(paste("~0+label")))
#^clipped from above since no covars: #, "+", paste(covars, collapse = " + "))))

# Matrix for a regression-like model
mod <- model.matrix(mat_formula, data = colData(hyp2_pbulk2))

# logcount matrix was created above (hyp2_pbulk3)

# Compute correlation
corfit <- duplicateCorrelation(hyp2_pbulk3, mod, block = hyp2_pbulk2$sample_id)

####cl13vs8 DEGs
m <- model.matrix(mat_formula,colData(hyp2_pbulk2))

czech <- eBayes(
        lmFit(
            hyp2_pbulk2@assays@data@listData$logcounts,
            design = m,
            block = hyp2_pbulk2$sample_id,
            correlation = corfit$consensus.correlation,
            
        ))

czechres <- topTable(czech,coef=2,number=nrow(hyp2_pbulk2),adjust.method = "BH")
### and again with the inflated p values.
### but let's save and plot-check the ones from dupcor-less run above (deres) --> plotting script
write.table(deres,"analysis/data/spe_053123/H05-bspace15-nnsvg10_ARC_clusters/pseudobulk_ARC13-vs-ARC8_NOdupcor.txt",sep='\t',quote=F,row.names=F,col.names=T)
``` 
