---
title: "01-Leave spatial reps out analyses"
author: "Bernard Mulvey"
date: "2023-06-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different:
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(ggplot2)
library(gridExtra)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```


Visualize LFC correlations
```{r}
lvout.DEres <- readRDS("analysis/data/H04-2cluster-consensus-VMH/Comparative DE approaches/One SpRep per donor/singleSpReps_VMHsexDE_reslist_named-by-excluded-samples.RDS")
i <- 2
for (i in c(2:length(lvout.DEres))){
    if (i==2){
    setnames(lvout.DEres[[i-1]],c("logFC","adj.P.Val","P.Value"),paste0(c("logFC","adj.P.Val","P.Value"),"_",i-1))
    setnames(lvout.DEres[[i]],c("logFC","adj.P.Val","P.Value"),paste0(c("logFC","adj.P.Val","P.Value"),"_",i))
    fetchnamesA <- c("group_name","gene_id",paste0(c("logFC","adj.P.Val","P.Value"),"_",i-1))
    fetchnamesB <- c("group_name","gene_id",paste0(c("logFC","adj.P.Val","P.Value"),"_",i))
    lvout.pltdat <- merge.data.table(lvout.DEres[[i-1]][,..fetchnamesA],lvout.DEres[[i]][,..fetchnamesB],by=c("group_name","gene_id"))
    rm(fetchnamesA)
    }
    else{
        setnames(lvout.DEres[[i]],c("logFC","adj.P.Val","P.Value"),paste0(c("logFC","adj.P.Val","P.Value"),"_",i))
        fetchnamesB <- c("group_name","gene_id",paste0(c("logFC","adj.P.Val","P.Value"),"_",i))
        lvout.pltdat <- merge.data.table(lvout.pltdat,lvout.DEres[[i]][,..fetchnamesB],by=c("group_name","gene_id"),all.x=T,all.y=T)
    }
}
rm(i,fetchnamesA,fetchnamesB)

### add gene names
lvout.pltdat <- merge.data.table(lvout.pltdat,as.data.table(rowData(hyp2.vmh))[,.(gene_id,gene_name)],by="gene_id")


fetchnames <- grep(names(lvout.pltdat),pattern="logFC",value=T)
lvout.cormat <- as.data.frame(lvout.pltdat[group_name=="VMH",..fetchnames])

panel.cor <- function(x, y, digits = 3, prefix = "", cex.cor, ...)
{
    usr <- par("usr"); on.exit(par(usr))
    par(usr = c(0, 1, 0, 1))
    r <- abs(cor(x, y,use="pairwise.complete.obs",method = "pearson"))
    txt <- format(c(r, 0.123456789), digits = digits)[1]
    txt <- paste0(prefix, txt)
    if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)
    text(0.5, 0.5, txt, cex = cex.cor * r)
}

png("plots/H04-2cluster-consensus-VMH/05-Comparative DE Approaches for Spatial Reps/01-Leave Out Spatial Reps per Donor/logFC Pearson correls twixt diff reps out, all genes.png",width=800,height=800)
pairs(lvout.cormat,upper.panel = panel.cor)
dev.off()

### repeat, but now excluding chrY genes and XIST, which are going to be bonkersly huge LFCs (all ≥7 in logFC_1)
lvout.cormat <- as.data.frame(lvout.pltdat[group_name=="VMH"&!(gene_name %in% lvout.pltdat[abs(logFC_1)>7,gene_name])&gene_name!="XIST",..fetchnames])

png("plots/H04-2cluster-consensus-VMH/05-Comparative DE Approaches for Spatial Reps/01-Leave Out Spatial Reps per Donor/logFC Pearson correls twixt diff reps out, nonXY genes.png",width=800,height=800)
pairs(lvout.cormat,upper.panel = panel.cor)
dev.off()
```

### Volcanos
```{r}
library(gridExtra)

plts <- list()
tmp <- lvout.DEres
tmp <- lapply(tmp,FUN=function(x){
    setnames(x,c(grep(names(x),pattern="logFC",value=T),grep(names(x),pattern="P.Value",value=T)),c("logFC","P.Value"))
})
i<-1
for (i in c(1:length(tmp))){
    plts[[i]] <- ggplot(tmp[[i]],aes(y=-log10(P.Value),x=logFC))+
        geom_point()+
        ggtitle(names(lvout.DEres)[i])+
        theme(plot.title=element_text(size=11,hjust=0.5),axis.title=element_text(size=10),axis.text = element_text(size=9))
}
rm(tmp,i)

png("plots/H04-2cluster-consensus-VMH/05-Comparative DE Approaches for Spatial Reps/01-Leave Out Spatial Reps per Donor/Volcanos.png",width=800,height=900)
do.call("grid.arrange",c(plts))
dev.off()

```
