---
title: "01-Harmony HVG Walkclusters"
author: "Bernie Mulvey"
date: "2023-05-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(ggplot2)
library(data.table)
library(Biostrings)
library(gridExtra)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(ggspavis)
library(scater) # addPerCellQC
# library(nnSVG)
library(BiocParallel)
library(scran)
library(parallel)
# library(scCustomize)
# library(fasthplus)
# library(STexampleData)
library(harmony)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```



## Top 10, 20% svgs with SNNgraph k=5,10,15
```{r}
# list obj with SGEs of harmony-corrected embeddings for top 10, top 20%ile HVGs
# pcas <- readRDS("analysis/data/H01-feature_selection/SPEs_sampleBlock-hvgs-10or20pctile_brnumBlock-Harmony-PCA-UMAP.RDS")

bpparam <- MulticoreParam(workers=2)
register(bpparam)

h.glist5 <- bplapply(pcas,BPPARAM=bpparam,FUN=function(x){
  scran::buildSNNGraph(x,k=5,use.dimred="HARMONY")
})
g_walk5 <- bplapply(h.glist5,igraph::cluster_walktrap,BPPARAM = bpparam)
# outputs are vectors of length(colData((spe)) with the cluster assignment:
walkclusts5 <- lapply(g_walk5,FUN=function(x){x$membership})
rm(g_walk5, h.glist5)
gc(full=T)


h.glist10 <- bplapply(pcas,BPPARAM=bpparam,FUN=function(x){
  scran::buildSNNGraph(x,k=10,use.dimred="HARMONY")
})
g_walk10 <- bplapply(h.glist10,igraph::cluster_walktrap,BPPARAM = bpparam)
walkclusts10 <- lapply(g_walk10,FUN=function(x){x$membership})
rm(g_walk10, h.glist10)
gc(full=T)


h.glist15 <- bplapply(pcas,BPPARAM=bpparam,FUN=function(x){
  scran::buildSNNGraph(x,k=15,use.dimred="HARMONY")
})
g_walk15 <- bplapply(h.glist15,igraph::cluster_walktrap,BPPARAM = bpparam)
walkclusts15 <- lapply(g_walk15,FUN=function(x){x$membership})
rm(g_walk15, h.glist15)
gc(full=T)

#

walkclusts.hvg <- list(walkclusts5[[1]],walkclusts5[[2]],walkclusts10[[1]],walkclusts10[[2]],walkclusts15[[1]],walkclusts15[[2]])

names(walkclusts.hvg) <- c("hvg10_SNNk5","hvg20_SNNk5","hvg10_SNNk10","hvg20_SNNk10","hvg10_SNNk15","hvg20_SNNk15")

# saveRDS(walkclusts.hvg,"analysis/data/H02-clustering/sampleBlock-hvg10-20_harmonyBrnumBlock-walktrap-SNNk5-10-15.RDS")

rm(walkclusts10,walkclusts5,walkclusts15)

```
