---
title: "H02-Fasthplus for walktrap clustering"
author: "Bernie Mulvey"
date: "2023-06-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(ggplot2)
library(data.table)
library(Biostrings)
library(gridExtra)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(ggspavis)
library(scater) # addPerCellQC
# library(nnSVG)
library(BiocParallel)
library(scran)
library(parallel)
# library(scCustomize)
library(fasthplus)
# library(STexampleData)
library(harmony)
library(igraph)
library(segmented)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

```{r}
# list obj with SGEs of harmony-corrected embeddings for top 10, top 20%ile HVGs
pcas <- readRDS("analysis/data/H01-feature_selection/SPEs_sampleBlock-hvgs-10or20pctile_brnumBlock-Harmony-PCA-UMAP.RDS")
```


HVG10/HVG20, snngraph k=5, cut_at 4-47.
```{r}
bpparam <- MulticoreParam(workers=2)
register(bpparam)

h.glist5 <- bplapply(pcas,BPPARAM=bpparam,BPOPTIONS = bpoptions(RNGseed = 42),FUN=function(x){
  scran::buildSNNGraph(x,k=5,use.dimred="HARMONY")
})
g_walk5 <- bplapply(h.glist5,igraph::cluster_walktrap,BPPARAM = bpparam,BPOPTIONS = bpoptions(RNGseed = 42))
names(g_walk5) <- c("hvg10_harmony_snnk5","hvg20_harmony_snnk5")
# feed g_walk thru a bplapply to cut_at min 4 max 47 (largest # of clusters detected with SNN k=5 or k=10 and HVG 10 or 20%ile) thru bpmapply

ks <- as.list(seq(4,47,1))
names(ks) <- c(4:47)

bpparam <- MulticoreParam(workers=10)
register(bpparam)

walkclusts5.hvg10.4_47 <- bplapply(X=ks,BPOPTIONS = bpoptions(RNGseed = 42),BPPARAM=bpparam,FUN=function(X){
    cut_at(communities = g_walk5[[1]],no = X)
})

walkclusts5.hvg20.4_47 <- bplapply(X=ks,BPOPTIONS = bpoptions(RNGseed = 42),BPPARAM=bpparam,FUN=function(X){
    cut_at(communities = g_walk5[[2]],no = X)
})

walkclusts5.4_47 <- list(walkclusts5.hvg10.4_47,walkclusts5.hvg20.4_47)
names(walkclusts5.4_47) <- c("walK5.hvg10.cut4_47","walK5.hvg20.cut4_47")
rm(g_walk5, h.glist5, walkclusts5.hvg10.4_47,walkclusts5.hvg20.4_47)
gc(full=T)
# saveRDS(walkclusts5.4_47,"analysis/data/H02-clustering/sampleBlock-hvg10-20_harmonyBrnumBlock-walktrap-SNNk5_cutAt4-47.RDS")
```

HVG10/HVG20, snngraph k=10, cut_at 4-47.
```{r}
bpparam <- MulticoreParam(workers=2)
register(bpparam)

h.glist10 <- bplapply(pcas,BPPARAM=bpparam,BPOPTIONS = bpoptions(RNGseed = 42),FUN=function(x){
  scran::buildSNNGraph(x,k=10,use.dimred="HARMONY")
})

g_walk10 <- bplapply(h.glist10,igraph::cluster_walktrap,BPPARAM = bpparam,BPOPTIONS = bpoptions(RNGseed = 42))

names(g_walk10) <- c("hvg10_harmony_snnk10","hvg20_harmony_snnk10")

# feed g_walk thru a bplapply to cut_at min 4 max 47 (largest # of clusters detected with SNN k=5 or k=10 and HVG 10 or 20%ile) thru bpmapply

ks <- as.list(seq(4,47,1))
names(ks) <- c(4:47)

bpparam <- MulticoreParam(workers=10)
register(bpparam)

walkclusts10.hvg10.4_47 <- bplapply(X=ks,BPOPTIONS = bpoptions(RNGseed = 42),BPPARAM=bpparam,FUN=function(X){
    cut_at(communities = g_walk10[[1]],no = X)
})


walkclusts10.hvg20.4_47 <- bplapply(X=ks,BPOPTIONS = bpoptions(RNGseed = 42),BPPARAM=bpparam,FUN=function(X){
    cut_at(communities = g_walk10[[2]],no = X)
})

walkclusts10.4_47 <- list(walkclusts10.hvg10.4_47,walkclusts10.hvg20.4_47)
names(walkclusts10.4_47) <- c("walK10.hvg10.cut4_47","walK10.hvg20.cut4_47")

rm(g_walk10, h.glist10, walkclusts10.hvg10.4_47,walkclusts10.hvg20.4_47)
gc(full=T)

saveRDS(walkclusts10.4_47,"analysis/data/H02-clustering/sampleBlock-hvg10-20_harmonyBrnumBlock-walktrap-SNNk10_cutAt4-47.RDS")
```

Fasthplus, adapted from dlPFC 2022-23 code
```{r}
walkclusts5 <- readRDS("analysis/data/H02-clustering/sampleBlock-hvg10-20_harmonyBrnumBlock-walktrap-SNNk5_cutAt4-47.RDS")
walkclusts10 <- readRDS("analysis/data/H02-clustering/sampleBlock-hvg10-20_harmonyBrnumBlock-walktrap-SNNk10_cutAt4-47.RDS")

names(walkclusts5[[1]]) <- paste0(names(walkclusts5)[1],"_",names(walkclusts5[[1]]))
names(walkclusts5[[2]]) <- paste0(names(walkclusts5)[2],"_",names(walkclusts5[[2]]))
names(walkclusts10[[1]]) <- paste0(names(walkclusts10)[1],"_",names(walkclusts10[[1]]))
names(walkclusts10[[2]]) <- paste0(names(walkclusts10)[2],"_",names(walkclusts10[[2]]))

# concat all clustering calls for a given HARMONY dimred (hvg 10%ile or 20%ile)
allwalk.hvg10 <- c(walkclusts5[[1]],walkclusts10[[1]])
allwalk.hvg20 <- c(walkclusts5[[2]],walkclusts10[[2]])
# check names from above carried over:
names(allwalk.hvg10)


#### from dlpfc code:
# hpb estimate. t = pre-bootstrap sample size, D = reduced dimensions matrix, L = cluster labels, r = number of bootstrap iterations
  
# helper function:
find_t <- function(L, proportion = 0.05) {
    initial_t <- floor(length(L) * proportion)
    smallest_cluster_size <- min(table(L))
    n_labels <- length(unique(L))
    ifelse(smallest_cluster_size > (initial_t / n_labels), initial_t, smallest_cluster_size * n_labels)
}
#### 
bpparam <- MulticoreParam(workers=6)
register(bpparam)
  
fhres.hvg10 <- bplapply(X=allwalk.hvg10,BPPARAM=bpparam,BPOPTIONS=bpoptions(RNGseed=42),function(X){
    hyp2.tmp <- pcas[[1]] # hyp spe with HVG10 HARMONY dimred
    colLabels(hyp2.tmp) <- factor(X)
    initial_t <- find_t(L = colData(hyp2.tmp)$label, proportion = 0.01)
    cluster_prop <- table(colData(hyp2.tmp)$label) / ncol(X)
    bad_clusters <- which(cluster_prop < 0.01)
    if (length(bad_clusters) > 0) {
        message("For k: ", Y, " we are dropping small clusters: ", paste(names(bad_clusters), collapse = ", "))
        hyp2.tmp <- hyp2.tmp[, !(levels(colData(hyp2.tmp)[["label"]]) %in% as.character(names(bad_clusters)))]
        updated_t <- find_t(colData(hyp2.tmp)[["label"]], 0.01)
        message("initial t: ", initial_t, "; updated t: ", updated_t)
    }
    else{
        updated_t <- initial_t
    }
    set.seed(42)
    hpb(D = reducedDims(hyp2.tmp)$HARMONY, L = colData(hyp2.tmp)$label, t = updated_t, r = 100)
})

fhres.hvg20 <- bplapply(X=allwalk.hvg20,BPPARAM=bpparam,BPOPTIONS=bpoptions(RNGseed=42),function(X){
    hyp2.tmp <- pcas[[2]] # hyp spe with HVG0 HARMONY dimred
    colLabels(hyp2.tmp) <- factor(X)
    initial_t <- find_t(L = colData(hyp2.tmp)$label, proportion = 0.01)
    cluster_prop <- table(colData(hyp2.tmp)$label) / ncol(X)
    bad_clusters <- which(cluster_prop < 0.01)
      if (length(bad_clusters) > 0) {
          message("For k: ", Y, " we are dropping small clusters: ", paste(names(bad_clusters), collapse = ", "))
          hyp2.tmp <- hyp2.tmp[, !(levels(colData(hyp2.tmp)[["label"]]) %in% as.character(names(bad_clusters)))]
          updated_t <- find_t(colData(hyp2.tmp)[["label"]], 0.01)
          message("initial t: ", initial_t, "; updated t: ", updated_t)
      }
      else{
        updated_t <- initial_t
      }
    set.seed(42)
    hpb(D = reducedDims(hyp2.tmp)$HARMONY, L = colData(hyp2.tmp)$label, t = updated_t, r = 100)
})

saveRDS(fhres.hvg10,"local_results_ref/fhres.hvg10.RDS")
saveRDS(fhres.hvg20,"local_results_ref/fhres.hvg20.RDS")

### tabulate
fhrestab <- cbind(names(fhres.hvg10),unlist(fhres.hvg10))
fhrestab <- rbind(fhrestab,cbind(names(fhres.hvg20),unlist(fhres.hvg20)))
fhrestab <- as.data.table(fhrestab)
names(fhrestab) <- c("cluster_set_k","hpb")

write.table(fhrestab,"analysis/data/H02-clustering/fasth_graph-based-hvg10-20_k4-47_results.txt",sep='\t',quote=F,row.names=F,col.names=T)
```

find optimal k(s)
```{r}
fhrestab[,clust_cond:=gsub(x=cluster_set_k,pattern="wal(K.*hvg.*)\\.cut.*$",replacement="\\1")]
fhrestab[,k:=as.numeric(gsub(x=cluster_set_k,pattern="walK.*\\.hvg.*cut.*_.*_(.*)$",replacement="\\1"))]
fhrestab[,hpb:=as.numeric(hpb)]

fhresinflec <- as.data.frame(matrix(nrow=4,ncol=4))
colnames(fhresinflec) <- c("clust_cond","seg_psi_est","seg2_psi1_est","seg2_psi2_est")
i<-1
for (i in c(1:length(unique(fhrestab$clust_cond)))){
    ks <- c(4:47)
    tmp <- fhrestab[clust_cond==unique(fhrestab$clust_cond)[i]]
    fhresinflec[i,1] <- unique(fhrestab$clust_cond)[i]
    ### https://github.com/LieberInstitute/spatialDLPFC/blob/main/code/analysis/06_fasthplus/02_segmented_inflection_point.R 
    f2 <- lm(hpb ~ k, data=tmp)
    
    seg <- segmented(f2,
        seg.Z = ~ks,
        npsi = 1
    )
    
    seg2 <- segmented(f2,
        seg.Z = ~ks,
        npsi = 2
    )
    # get Est. psi vals
    fhresinflec[i,2] <- seg$psi[1,2]
    fhresinflec[i,3] <- seg2$psi[1,2]
    fhresinflec[i,4] <- seg2$psi[2,2]

}

write.table(fhresinflec,"analysis/data/H02-clustering/fasth_graph-based-hvg10-20_k4-47_psivalests.txt")
```
