---
title: "02-Harmony HVG Walkclusters"
author: "Bernie Mulvey"
date: "2023-05-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(ggplot2)
library(data.table)
library(Biostrings)
library(gridExtra)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(ggspavis)
library(scater) # addPerCellQC
# library(nnSVG)
library(BiocParallel)
library(scran)
library(parallel)
# library(scCustomize)
# library(fasthplus)
# library(STexampleData)
library(harmony)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```



## Top 10, 20% svgs, top 10% 20% nnsvgs with SNNgraph and cut_att k=9,15,20,31 per fasthplus results
## we can extract the HVG result for these k values using the saved RDS objects with walktrap cluster assignments for every k 4 thru 47, so just run on the nnsvgs
```{r}
# list obj with SGEs of harmony-corrected embeddings for top 10, top 20%ile HVGs
pcas <- readRDS("analysis/data/H01-feature_selection/SPEs_sampleBlock-hvgs-10or20pctile_nnsvg10or20pctile_Harmony-PCA-UMAP.RDS")
# subset to nnsvg PCAs for memory
pcas <- pcas[c(3:4)]

ks <- list(9,15,20,31)
names(ks) <- c("cut9","cut15","cut20","cut31")

# 2 feature sets (nnsvg 10%ile, 20%ile)
bpparam <- MulticoreParam(workers=2)
register(bpparam)

h.glist5 <- bplapply(X=pcas,BPPARAM=bpparam,BPOPTIONS=bpoptions(RNGseed = 42),FUN=function(x){
  scran::buildSNNGraph(x,k=5,use.dimred="HARMONY")
})

g_walk5 <- bplapply(X=h.glist5,FUN=igraph::cluster_walktrap,BPOPTIONS=bpoptions(RNGseed = 42),BPPARAM = bpparam)
# outputs are vectors of length(colData((spe)) with the cluster assignment:

# 4 cut_ats by 2 feature sets (nnsvg 10%ile, 20%ile)
bpparam <- MulticoreParam(workers=4)
register(bpparam)

walkclusts5 <- list()
i<-1

for (i in c(1:2)){
    tmp <- bplapply(X=ks,BPPARAM = bpparam,BPOPTIONS=bpoptions(RNGseed=42),FUN=function(X){
    cut_at(communities = g_walk5[[i]],no = X)})
    walkclusts5[c((length(walkclusts5)+1):(length(walkclusts5)+length(ks)))] <- tmp
}

names(walkclusts5) <- c(paste0(names(g_walk5)[1],"_",names(ks)),paste0(names(g_walk5)[2],"_",names(ks)))

# ^ sanity check: cluster assignments in this list are cut 9,15,20,31,9,15..
lapply(walkclusts5,FUN = function(x){length(unique(x))})
# ok we good

rm(g_walk5, h.glist5)
gc(full=T)

#### snn graph k=10
bpparam <- MulticoreParam(workers=2)
register(bpparam)
h.glist10 <- bplapply(pcas,BPPARAM=bpparam,BPOPTIONS=bpoptions(RNGseed=42),FUN=function(x){
  scran::buildSNNGraph(x,k=10,use.dimred="HARMONY")
})
g_walk10 <- bplapply(h.glist10,igraph::cluster_walktrap,BPPARAM = bpparam,BPOPTIONS=bpoptions(RNGseed=42))

# 4 cut_ats by 2 feature sets (nnsvg 10%ile, 20%ile)
bpparam <- MulticoreParam(workers=4)
register(bpparam)

walkclusts10 <- list()
i<-1

for (i in c(1:2)){
    tmp <- bplapply(X=ks,BPPARAM = bpparam,BPOPTIONS=bpoptions(RNGseed=42),FUN=function(X){
    cut_at(communities = g_walk10[[i]],no = X)})
    walkclusts10[c((length(walkclusts10)+1):(length(walkclusts10)+length(ks)))] <- tmp
}
rm(i,tmp)

names(walkclusts10) <- c(paste0(names(g_walk10)[1],"_",names(ks)),paste0(names(g_walk10)[2],"_",names(ks)))
# ^ sanity check: cluster assignments in this list are cut 9,15,20,31,9,15..
lapply(walkclusts10,FUN = function(x){length(unique(x))})
# ok we good

rm(g_walk10, h.glist10)
gc(full=T)
```


Add clustering assignments from Harmony'd HVGs with samplewise blocking in both
```{r}
hvgwalks5 <- readRDS("analysis/data/H02-clustering/sampleBlock-hvg10-20_harmonyBrnumBlock-walktrap-SNNk5_cutAt4-47.RDS")
hvgwalks10 <- readRDS("analysis/data/H02-clustering/sampleBlock-hvg10-20_harmonyBrnumBlock-walktrap-SNNk10_cutAt4-47.RDS")

hvgwalks5 <- c(hvgwalks5[[1]][c("9","15","20","31")],hvgwalks5[[2]][c("9","15","20","31")])
names(hvgwalks5) <- c(paste0("walK5_hvg10_",names(ks)),paste0("walK5_hvg20_",names(ks)))

hvgwalks10 <- c(hvgwalks10[[1]][c("9","15","20","31")],hvgwalks10[[2]][c("9","15","20","31")])
names(hvgwalks10) <- c(paste0("walK10_hvg10_",names(ks)),paste0("walK10_hvg20_",names(ks)))

allwalks <- list()
allwalks[c(1:8)] <- hvgwalks5
names(allwalks)[c(1:8)] <- names(hvgwalks5)

allwalks[c(9:16)] <- hvgwalks10
names(allwalks)[c(9:16)] <- names(hvgwalks10)

allwalks[c(17:24)] <- walkclusts5
names(allwalks)[c(17:24)] <- paste0("walK5_",names(walkclusts5))

allwalks[c(25:32)] <- walkclusts10
names(allwalks)[c(25:32)] <- paste0("walK10_",names(walkclusts10))

saveRDS(allwalks,"analysis/data/H02-clustering/walktraps_snn5.10_HVG1020-OR-SVG-1020_cut9.15.20.31.RDS")

```
