---
title: "01c-Join JHPCE k25k30 walktrap to local k10-20"
author: "Bernie Mulvey"
date: "2023-05-29"
output: html_document
---

```{r setup, include=FALSE}
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(SpatialExperiment)
library(ggspavis)
library(scater) # addPerCellQC
library(BiocParallel)
library(scran)
library(parallel)
# library(nnSVG)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

### post-JHPCE walktrap of k25, k30: concat back into cluster assignments list obj

```{r}
walktraps <- readRDS("analysis/data/02-clustering/01b-7featureset_k10-30by5s_walktrap_clusters_NOcovars_k10-20only.RDS")

jhpcewts <- list.files("analysis/data/02-clustering/01c-walktrap_k25_k30/")

featorder <- names(walktraps[[1]]) 
k25 <- list()
k30 <- list()
i<-1
for (i in c(1:length(jhpcewts))){
    j <- ifelse(i>7,yes=i-7,no=i)
    curk <- ifelse(i<8,yes="k25",no="k30")
    currds <- grep(jhpcewts,pattern=featorder[j],value = T)
    currds <- grep(currds,pattern=curk,value=T)
    currds <- ifelse(j<3,yes=grep(currds,pattern="nnsvg",invert = T,value=T),no=grep(currds,pattern="nnsvg",value=T))
    cur <- readRDS(paste0("analysis/data/02-clustering/01c-walktrap_k25_k30/",currds))
    if (i<=7){
        k25[[j]] <- cur
    }
    else{
        k30[[j]] <- cur
    }
    rm(j,curk,currds)
}
names(k25) <- featorder
names(k30) <- featorder

# make sure mixed matches (with hvg and nnsvg strings in name) listed out correctly
stopifnot(sum(k25[[5]] == readRDS("analysis/data/02-clustering/01c-walktrap_k25_k30/k25_nnsvg2k_hvg10pct_walktrap_clusters_nocovar.RDS"))==length(k25[[5]]))

stopifnot(sum(k30[[6]] == readRDS("analysis/data/02-clustering/01c-walktrap_k25_k30/k30_nnsvg3k_hvg20pct_walktrap_clusters_nocovar.RDS"))==length(k30[[6]]))
# k cool
rm(cur,featorder,i,jhpcewts)

walktraps[[4]] <- k25
walktraps[[5]] <- k30

names(walktraps)[4:5] <- c("k25","k30")
# saveRDS(walktraps,"analysis/data/02-clustering/01c-7featureset_k10-30by5s_walktrap_clusters_NOcovars.RDS")
rm(k25,k30)
```
