---
title: "Untitled"
author: "Bernard Mulvey"
date: "2023-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
require(colorout)
source("~/.R/calc_tau_for_cellOrTissueSpecificity_metric.R")
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")

## change write.table to output a TSV without quotes or rownames by default
library(default)
default(write.table) <- list(row.names=F,col.names=T,sep='\t',quote=F)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

```{r}

cllut <- fread("~/Desktop/KM Lab/local_hthspatial/EDA and Preliminary Dataset/ref/herb23_ARC-VMH_clusids.txt")
de <- fread("~/Desktop/KM Lab/local_hthspatial/EDA and Preliminary Dataset/ref/herb23_H369_clusVsAll-de.txt")


vmh <- de[`H369 clusters` %in% cllut$H369_VMH]


hypmk <- readRDS("~/Desktop/KM Lab/local_hthspatial/EDA and Preliminary Dataset/data/spe_053123/H03-marker_genes/04-BSpace_HVG1020-SVG1020_q9-15-20-31_sLIBD-regwrapper-enrichment-res.RDS")


hypmk <- as.data.table(hypmk[[9]])

restab <- as.data.frame(matrix(nrow=15*length(unique(de$`H369_VMH`)),ncol=8))
colnames(restab) <- c("spclus","herbclus","nspmk","nherbmk","inboth","sponly","herbonly","neither")

k<-1
i<-1
for (i in c(1:15)){
  j <- 1
  curfdr <- paste0("fdr_X",i)
  curlfc <- paste0("logFC_X",i)
  curdat <- copy(hypmk)[,c("gene",..curfdr,..curlfc)]
  for (j in c(1:length(unique(vmh$`H369 clusters`)))){
    restab[k,1] <- paste0("X",i)
    restab[k,2] <- unique(vmh$`H369 clusters`)[j]
    mkuniverse <- unique(curdat[gene %in% vmh$gene,gene])
    curdat <- curdat[gene %in% mkuniverse,]
    restab[k,3] <- nrow(curdat[get(curlfc)>0&get(curfdr)<0.05])
    restab[k,4] <- nrow(vmh[`H369 clusters`==restab[k,2]])
    restab[k,5] <- nrow(curdat[get(curlfc)>0&get(curfdr)<0.05&gene %in% vmh[`H369 clusters`==restab[k,2],gene]])
    restab[k,6] <- nrow(curdat[get(curlfc)>0&get(curfdr)<0.05&!(gene %in% vmh[`H369 clusters`==restab[k,2],gene])&gene %in% mkuniverse])
    restab[k,7] <- nrow(vmh[`H369 clusters`==restab[k,2]&!(gene %in% curdat[get(curlfc)>0&get(curfdr)<0.05&gene %in% mkuniverse,gene])])
    restab[k,8] <- length(mkuniverse)-restab[k,7]-restab[k,6]-restab[k,5]
    k <- k+1
  }
  
}
restab <- as.data.table(restab)
restab[,fish:=apply(.SD,MARGIN = 1,FUN=function(x){fisher.test(matrix(c(x[1],x[2],x[3],x[4]),ncol=2))$p.value}),.SDcols=c(5:8)]
restab[,est:=apply(.SD,MARGIN = 1,FUN=function(x){fisher.test(matrix(c(x[1],x[2],x[3],x[4]),ncol=2))$estimate}),.SDcols=c(5:8)]
### FDR adjust per spatial domain tested
restab[,fdr:=p.adjust(fish,method="BH"),by="spclus"]
restab[fdr<0.05&est>1,.N,by="spclus"]
```
   spclus  N
1:     X1  2 # !?
2:     X5  6
3:     X6 14

### same for arcuate
```{r}
arc <- de[`H369 clusters` %in% cllut$H369_ARC]


arcres <- as.data.frame(matrix(nrow=15*length(unique(cllut$`H369_ARC`)),ncol=8))
colnames(arcres) <- c("spclus","herbclus","nspmk","nherbmk","inboth","sponly","herbonly","neither")

k<-1
i<-1
for (i in c(1:15)){
  j <- 1
  curfdr <- paste0("fdr_X",i)
  curlfc <- paste0("logFC_X",i)
  curdat <- copy(hypmk)[,c("gene",..curfdr,..curlfc)]
  for (j in c(1:length(unique(arc$`H369 clusters`)))){
    arcres[k,1] <- paste0("X",i)
    arcres[k,2] <- unique(arc$`H369 clusters`)[j]
    mkuniverse <- unique(curdat[gene %in% arc$gene,gene])
    curdat <- curdat[gene %in% mkuniverse,]
    arcres[k,3] <- nrow(curdat[get(curlfc)>0&get(curfdr)<0.05])
    arcres[k,4] <- nrow(arc[`H369 clusters`==arcres[k,2]])
    arcres[k,5] <- nrow(curdat[get(curlfc)>0&get(curfdr)<0.05&gene %in% arc[`H369 clusters`==arcres[k,2],gene]])
    arcres[k,6] <- nrow(curdat[get(curlfc)>0&get(curfdr)<0.05&!(gene %in% arc[`H369 clusters`==arcres[k,2],gene])&gene %in% mkuniverse])
    arcres[k,7] <- nrow(arc[`H369 clusters`==arcres[k,2]&!(gene %in% curdat[get(curlfc)>0&get(curfdr)<0.05&gene %in% mkuniverse,gene])])
    arcres[k,8] <- length(mkuniverse)-arcres[k,7]-arcres[k,6]-arcres[k,5]
    k <- k+1
  }
  
}
arcres <- as.data.table(arcres)
arcres[,fish:=apply(.SD,MARGIN = 1,FUN=function(x){fisher.test(matrix(c(x[1],x[2],x[3],x[4]),ncol=2))$p.value}),.SDcols=c(5:8)]
arcres[,est:=apply(.SD,MARGIN = 1,FUN=function(x){fisher.test(matrix(c(x[1],x[2],x[3],x[4]),ncol=2))$estimate}),.SDcols=c(5:8)]
### FDR adjust per spatial domain tested
arcres[,fdr:=p.adjust(fish,method="BH"),by="spclus"]
arcres[fdr<0.05&est>1,.N,by="spclus"]
```
   spclus  N
1:     X1  4
2:     X4  1
3:     X8 18
4:    X13 10