---
title: "02_lognorm_and_split_to_samplewise"
output: html_document
date: "2024-06-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(SpatialFeatureExperiment)
library(spatialLIBD)
library(scran)
library(scater)

## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
##

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc. seemed to need this a couple times, but otherwise havent so its here as a preventative measure.
library(parallelly)
options(parallelly.supportsMulticore.disableOn="")
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost="localhost")

## ggplot defaults
theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

## count normalization
```{r}
hypx <- readRDS("processed-data/03_make_SPE-SFE/01_sfe_raw.RDS")

# calculate library factors and normalize counts
hypx <- computeLibraryFactors(hypx)
hypx <- logNormCounts(hypx)

# banksy uses SPEs split into a list per sample. make one and save
hypx.bysamp <- lapply(unique(hypx$Sample),function(x){
  hypx.sub <- hypx[,hypx$Sample==x]
  return(hypx.sub)
})
names(hypx.bysamp) <- unique(hypx$Sample)

saveRDS(hypx.bysamp,"processed-data/04_general_QC_and_normalization/02_sfe_lognorm_bysamp.RDS")
```
