---
title: "03-Marker Gene Supp Tab Making"
author: "Bernard Mulvey"
date: "2024-02-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(SpatialExperiment)
library(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")

## change write.table to output a TSV without quotes or rownames by default
library(default)
default(write.table) <- list(row.names=F,col.names=T,sep='\t',quote=F)
```

Load up the spatialLIBD results and write out
```{r}
slibdmk <- readRDS("data/07-Marker_genes/01b-BSpace_allruns_spatialLIBD-regwrap-enrichment_full.RDS")

slibdmk <- slibdmk[names(slibdmk) %in% grep(names(slibdmk),pattern="HARMONYlmbna_nnsvg10_60kiter",value=T)]

slmn <- names(slibdmk)
mapply(x=slibdmk,y=slmn,FUN=function(x,y){
    fwrite(x,paste0("local_supptab_assembly/Marker Analysis",y,".txt"),sep="\t",quote=F)
})

```

## export one-to-one comparisons of ARC and VMH from each
```{r}
### get gene info to merge using the SPE
hyp2 <- readRDS("data/03-QC_filters/hypN9_umi275_gene166_chrm50_lognorm_111723.RDS")

genedat <- as.data.table(rowData(hyp2))
rm(hyp2)
gc(full=T)

### load pairwise results
comparatives <- readRDS("data/07-Marker_genes/02-nnsvg10_HRM-lmbna_bspace_VMHandARC-clustPair-diffmarkers.RDS")


### since these were run only with the two clusters of interest as input, we only need the first output (there's outputs for cluster A vs cluster B and B vs A from each, which are equivalent as depleted in A must then == enriched in B)
comparewrangle <- list()
comparewrangle[[1]] <- as.data.table(comparatives[[1]][[1]],keep.rownames=T)
comparewrangle[[2]] <- as.data.table(comparatives[[2]][[1]],keep.rownames=T)
comparewrangle[[3]] <- as.data.table(comparatives[[3]][[1]],keep.rownames=T)
names(comparewrangle) <- names(comparatives)[1:3]

j <- 4
for (j in c(4:6)){
    i<-1
    for (i in c(1:length(comparatives[[j]]))){
        comparewrangle[[length(comparewrangle)+1]] <-
            as.data.table(comparatives[[j]][[i]][[1]],keep.rownames=T)
        names(comparewrangle)[length(comparewrangle)] <-
            names(comparatives[[j]])[i]
    }
}

### add gene info
comparewrangle <- lapply(comparewrangle,FUN=function(x){
  x <- merge.data.table(genedat[,.(gene_id,gene_name)],x,by.x="gene_id",by.y="rn")
  return(x)
})

mapply(x=comparewrangle,y=names(comparewrangle),FUN=function(x,y){
    fwrite(x,paste0("local_supptab_assembly/Sup Tab-VMHorARC pairwise Marker Analyses",y,".txt"),sep="\t",quote=F)
})


```
