---
title: "03-Spotplot k2 VMH genes enriched by pseudobulk DE"
author: "Bernard Mulvey"
date: "2023-06-22"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(ggplot2)
library(data.table)
library(Biostrings)
library(gridExtra)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(scater)
library(ggspavis)
library(SpatialExperiment)
library(Polychrome)
library(spatialLIBD)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

### Data loadup
```{r}
hyp2.vmh <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_061323_HarmonyBSpc-q2VMH_rowname-key.RDS")

colnames(hyp2.vmh) <- colData(hyp2.vmh)$key
rownames(hyp2.vmh) <- rowData(hyp2.vmh)$gene_name

vmhde <- fread("analysis/data/spe_053123/H04-2cluster-consensus-VMH/Comparative DE approaches/Without adjustments or exclusions/pseudobulk-VMH-other-DE.txt")
vmhde.sexcov <- fread("analysis/data/spe_053123/H04-2cluster-consensus-VMH/Comparative DE approaches/Without adjustments or exclusions/pseudobulk-VMH-other-DE_sexcovaried.txt")

```

### extract significant (FDR<10e-7) VMH-enriched DEGs (logFC>0), and let's drop chrY genes at least
```{r}
vmhdegs <- unique(c(
    vmhde[logFC>0&adj.P.Val<(10e-7)&!(gene_name %in% c("ZFY","UTY","PRKY","DDX3Y","TTTY14","NLGN4Y","EIF1AY","TMSB4Y","USP9Y","PCDH11Y","RPS4Y1","KDM5D")),gene_name],
    vmhde.sexcov[logFC>0&adj.P.Val<(10e-7)&!(gene_name %in% c("ZFY","UTY","PRKY","DDX3Y","TTTY14","NLGN4Y","EIF1AY","TMSB4Y","USP9Y","PCDH11Y","RPS4Y1","KDM5D")),gene_name]
    ))

hyp2.plt <- hyp2.vmh

i <- 1
for (i in c(1:length(vmhdegs))){
    curgene <- vmhdegs[i]
    plt <- spatialLIBD::vis_grid_gene(hyp2.plt,geneid = curgene,return_plots = T,spatial=F,point_size = 1,auto_crop = T)
    ### adjust font sizes
    plt <- lapply(plt,FUN=function(x){x+
            theme(plot.title = element_text(size = 11,hjust=0.5), strip.text = element_text(size=10), legend.text = element_text(size=10), legend.title = element_text(size=10,hjust=0.5))
            })
    pdf(paste0("plots/spe_053123/H04-2cluster-consensus-VMH/03a-VMH_upreg_spotplots/",curgene,".pdf"),width=10,height=8)
    do.call("grid.arrange",plt)
    dev.off()
}

rm(i,curgene,hyp2.plt,plt)
gc(full=T)
```


### Volcano plot for VMH and other
```{r}
pdf("plots/H04-2cluster-consensus-VMH/03-VMH Enrichment volcano.pdf",height=7,width=7)
ggplot(vmhde,aes(y=-log10(adj.P.Val),x=logFC))+
    geom_point()+
    geom_hline(yintercept = -log10(0.05),col="red",alpha=0.7)+
    geom_text(aes(x=3.25,y=-log10(0.125),label="FDR<0.1"))+
    ylab("-log10 (FDR)")+
    xlab("logFC (VMH(+) vs. Other(-))")+
    ylim(0,8)
dev.off()
    



```



### Alternate approach/plots 03b: ### AFTER post-cropping D07075B1 (data, plots spe053123 -> H04-03b); only plot svgs not previously identified in above run. Only plot genes not identified in above set.
```{r}
hyp2 <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_061323_HarmonyBSpc-q2VMH_rowname-key.RDS")

### crop V12D07-075_B1 first -- see code/00 blah blah .rmd
coordstmp <- as.data.frame(spatialCoords(hyp2))
rownames(coordstmp) <- colnames(hyp2)
coordstmp <- as.data.table(coordstmp,keep.rownames=T)
coordstmp <- coordstmp[,diag:=pxl_col_in_fullres+pxl_row_in_fullres]
coordstmp <- coordstmp[!(rn %in% grep(rn,pattern="V12D07-075_B1",value=T)&diag>30000)]

hyp2 <- hyp2[,colnames(hyp2)%in%coordstmp$rn]
stopifnot(dim(hyp2)[2]==nrow(coordstmp))

### set rownames to gene name
rownames(hyp2) <- rowData(hyp2)$gene_name
hyp2.plt <- hyp2

rm(hyp2,coordstmp)
### get VMH pseudobulk DEGs to plot
vmhdegs <- fread("analysis/data/spe_053123/H04-2cluster-consensus-VMH/pseudobulk_CROPPED-VMH-other-DE.txt")

### extract significant (FDR<10e-7, logFC>0 and let's drop chrY genes at least)
vmhde <- vmhdegs[group_name=="VMH"&logFC>0&adj.P.Val<10e-7&!(gene_name %in% c("ZFY","UTY","PRKY","DDX3Y","TTTY14","NLGN4Y","EIF1AY","TMSB4Y","USP9Y","PCDH11Y","RPS4Y1","KDM5D")),gene_name]

prevplot <- list.files("plots/spe_053123/H04-2cluster-consensus-VMH/03a-VMH_upreg_spotplots",pattern = ".pdf")
prevplot <- gsub(prevplot,pattern=".pdf",replacement="")

### novelties here
vmhdegs <- vmhde[!(vmhde %in% prevplot)]

# plot
i <- 1
for (i in c(1:length(vmhdegs))){
    curgene <- vmhdegs[i]
    plt <- spatialLIBD::vis_grid_gene(hyp2.plt,geneid = curgene,return_plots = T,spatial=F,point_size = 1,auto_crop = T)
    ### adjust font sizes
    plt <- lapply(plt,FUN=function(x){x+
            theme(plot.title = element_text(size = 11,hjust=0.5), strip.text = element_text(size=10), legend.text = element_text(size=10), legend.title = element_text(size=10,hjust=0.5))
            })
    pdf(paste0("plots/spe_053123/H04-2cluster-consensus-VMH/03b-VMH_upreg_spotplots_postcrop/",curgene,".pdf"),width=10,height=8)
    do.call("grid.arrange",plt)
    dev.off()
}


```
