---
title: "01-plot k10-30 walktrap clusters on UMAP, PCA, spots"
author: "Bernie Mulvey"
date: "2023-05-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(ggplot2)
library(data.table)
library(Biostrings)
library(gridExtra)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(SpatialExperiment)
library(ggspavis)
library(scater) # addPerCellQC
# library(nnSVG)
library(BiocParallel)
library(scran)
library(parallel)
library(Polychrome)
# library(fasthplus)
library(scCustomize)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

# load required objs
```{r}
walktraps <- readRDS("analysis/data/H02-clustering/sampleBlock-hvg10-20_harmonyBrnumBlock-walktrap-SNNk5-10-15.RDS")

hyp2 <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_053123.RDS")

hyp2.hvgs.list <- list()
hyp2.hvgs.list[[1]] <- readRDS("analysis/data/H01-feature_selection/HVG10pctile_sample-blocked.RDS")
hyp2.hvgs.list[[2]] <- readRDS("analysis/data/H01-feature_selection/HVG20pctile_sample-blocked.RDS")

pcas <- readRDS("analysis/data/H01-feature_selection/SPEs_sampleBlock-hvgs-10or20pctile_brnumBlock-Harmony-PCA-UMAP.RDS")

```


## plot cluster assignments onto spatial spots
```{r}
hyp2.tmp <- hyp2
plts <- list()
k<-1

for (k in c(1:length(walktraps))){
    colLabels(hyp2.tmp) <- factor(walktraps[[k]])
    # the much simpler call to polychrome is not resulting in any actual colors assigned to the plots for some reason. but this roundabout way works. something's gone real wonky with my ggspavis installation.
plts[[length(plts)+1]] <- ggspavis::plotSpots(hyp2.tmp, annotate = "label",palette = DiscretePalette_scCustomize(num_colors = 2 + length(unique(colData(
          hyp2.tmp
      )$label)), palette = "varibow")[3:(length(unique(colData(hyp2.tmp)$label)) + 2)]
  )+
ggtitle(paste0("harmony_walktrap_",names(walktraps)[k]))
}
  
  
rm(k)

png("plots/H02-clustering/01-harmonywalktrap_clusts_spotplots.png",height=3000,width=4000)
do.call("grid.arrange",c(plts,nrow=3))
dev.off()


rm(plts)

```

### ...and onto Harmony PCA...
```{r}
hyp2.tmp <- hyp2
plts <- list()
k<-1
i<-1
for (i in c(1:length(pcas))){
    if (i==1){ks <- c(1,3,5)
    k<-1}
    else{ks <- c(2,4,6)
    k<-2}
    for (k in ks){
        colLabels(hyp2.tmp) <- walktraps[[k]]
        # ^ making this a factor downstream since d.t. will coerce back to numeric
        pltdat <- cbind(reducedDims(pcas[[i]])$HARMONY[,c(1,2)],colData(hyp2.tmp)$label)
        pltdat <- as.data.table(pltdat)
        setnames(pltdat,c("HARMONY_Dim1","HARMONY_Dim2","label"))
        pltdat[,label:=factor(label)]
  plts[[length(plts)+1]] <- 
      ggplot(pltdat,aes(x=HARMONY_Dim1,y=HARMONY_Dim2,col=label))+
         geom_point()+
                 scale_color_discrete(DiscretePalette_scCustomize(num_colors = 2 + length(unique(colData(
              hyp2.tmp
          )$label)), palette = "varibow")[3:(length(unique(colData(hyp2.tmp)$label)) + 2)])+
        ggtitle(paste0(names(pcas)[i],"_walktrap_",names(walktraps)[k]))
    }
}
  
  
rm(i,k)

png("plots/H02-clustering/01-walktrap_clusts_HarmonyPCA.png",height=3000,width=4000)
do.call("grid.arrange",c(plts,nrow=3))
dev.off()


rm(plts)

```

### ..and umap
```{r}
hyp2.tmp <- hyp2
plts <- list()
i<-1

plts <- list()
k<-1
i<-1
for (i in c(1:length(pcas))){
    if (i==1){ks <- c(1,3,5)
    k<-1}
    else{ks <- c(2,4,6)
    k<-2}
    for (k in ks){
        colLabels(hyp2.tmp) <- walktraps[[k]]
        # ^ making this a factor downstream since d.t. will coerce back to numeric
        pltdat <- cbind(reducedDims(pcas[[i]])$HARMONY_UMAP[,c(1,2)],colData(hyp2.tmp)$label)
        pltdat <- as.data.table(pltdat)
        setnames(pltdat,c("HARMONY_Dim1","HARMONY_Dim2","label"))
        pltdat[,label:=factor(label)]
  plts[[length(plts)+1]] <- 
      ggplot(pltdat,aes(x=HARMONY_Dim1,y=HARMONY_Dim2,col=label))+
         geom_point()+
                 scale_color_discrete(DiscretePalette_scCustomize(num_colors = 2 + length(unique(colData(
              hyp2.tmp
          )$label)), palette = "varibow")[3:(length(unique(colData(hyp2.tmp)$label)) + 2)])+
        ggtitle(paste0(names(pcas)[i],"_walktrap_",names(walktraps)[k]))
    }
}
  
  
rm(i,k)
  

png("plots/H02-clustering/01-walktrap_clusts_HarmonyUMAP.png",height=3000,width=4000)
do.call("grid.arrange",c(plts,nrow=3))
dev.off()


rm(plts)

## clean up
rm(i,k,x,hyp2.tmp,plts,ks,pltdat)
```
