---
title: "02-Spotplot Cluster Assignments"
author: "Bernard Mulvey"
date: "2023-11-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
require(colorout)
source("~/.R/calc_tau_for_cellOrTissueSpecificity_metric.R")
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")

## change write.table to output a TSV without quotes or rownames by default
library(default)
default(write.table) <- list(row.names=F,col.names=T,sep='\t',quote=F)

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc
library(parallelly)
options(parallelly.supportsMulticore.disableOn="")
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost="localhost")

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```

### load data, gather bayesspace cluster assignments.
```{r}
hyp2 <- readRDS("data/04-feature_selection/02-hypfiltered_nnsvg10-pca-umap-harmonydefault-harmonylambdanull-mnn30.RDS")

### set colnames(hyp2) to key for unique rownames etc; these are the rownames used with the bayesspace cluster results
stopifnot(colnames(hyp2)==hyp2$key)

bs_clusts <- list.files("data/05-clustering/01-bayesspace_k9-15-20-31_out",pattern=".txt")
```

helper function to extract a legend and pipe back to a diff plot: from https://statisticsglobe.com/add-common-legend-to-combined-ggplot2-plots-in-r/#example-2-add-shared-legend-to-ggplot2-plots-using-gridextra-package 
```{r}
extract_legend <- function(my_ggp) {
  step1 <- ggplot_gtable(ggplot_build(my_ggp))
  step2 <- which(sapply(step1$grobs, function(x) x$name) == "guide-box")
  step3 <- step1$grobs[[step2]]
  return(step3)
}
```

spotplots
```{r}
i <- 1
for (i in c(1:length(bs_clusts))) {
    curclusts <-
        fread(
            bs_clusts[i]
        )
    
    curclusts <- as.data.frame(curclusts)
    curclusts[,2] <- paste0("X",curclusts[,2])
    rownames(curclusts) <- curclusts$rn
    
    if (sum(rownames(curclusts) == rownames(colData(hyp2))) != nrow(colData(hyp2))) {
        curclusts <- curclusts[rownames(colData(hyp2)),]
    }
    
    colLabels(hyp2) <- factor(curclusts[, 2],levels=paste0("X",c(1:length(unique(curclusts[,2])))))
    pal <- palette36.colors(n = length(unique(curclusts[, 2])))
    # next line is needed for consistency in color-cluster assignments between libdspatial and the generated legend below
    names(pal) <- c(1:length(unique(hyp2$label)))
    
    ## create a unified legend spanning all possible cluster values (regardless of presence in a given sample)
    leg.tmp <- ggplot(as.data.table(colData(hyp2))[,.(label,array_row,array_col)],aes(x=array_row,y=array_col,col=label))+geom_point()+
        scale_color_manual(values=as.character(pal))+theme(
                    legend.text = element_text(size = 10),
                    legend.title = element_text(size = 10, hjust = 0.5),
                    legend.spacing.y = unit(0, "cm"),
                    legend.spacing.x = unit(0.1, "cm"))
    leg.tmp2 <- extract_legend(leg.tmp)
    dev.off()
    ### make spotplots
    plt <-
        spatialLIBD::vis_grid_clus(
            hyp2,
            clustervar = "label",
            pdf_file = NULL,
            colors = pal,
            spatial = F,
            auto_crop = T,
            return_plots = T,
            point_size = 2,
            sort_clust = F
        )
    
    ### adjust font sizes, drop individual plot legends
    plt <- lapply(
        plt,
        FUN = function(x) {
            x +
                theme(
                    plot.title = element_text(size = 11, hjust = 0.5),
                    strip.text = element_text(size = 10),
                )+
                guides(fill="none")
        }
    )
    
    # save
    pdf(
        paste0(
            "plots/06-BayesSpace/02-Cluster spotplots/",
            gsub(bs_clusts[i], pattern = "^.*_out/(.*)\\.txt$", replacement = "\\1"),
            ".pdf"
        ),
        width = 20,
        height = 16
    )
    ### arrangeGrob() on the spotplot list --> 3 x 3 of plots from that list only, constituting the "first column" of the parent; leg.tmp2 is an additional thing being plotted in the second column of the parent. width of the plot grid is set to 10, width of the second column (legend only) set to 2.
    do.call("grid.arrange",list(arrangeGrob(grobs=plt,ncol=3,nrow=3),leg.tmp2,ncol=2,widths=c(18,2)))
    dev.off()
    
    # clean up before next iteration as failsafe
    rm(plt, curclusts,leg.tmp,leg.tmp2)
}

```
