---
title: Plot known and novel markers of arc clusters and markers differentiating the
  two ARC spatial clusters
author: "Bernard Mulvey"
date: "2023-07-10"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(data.table)
library(Biostrings)
library(gridExtra)
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
library(scater)
library(ggspavis)
library(SpatialExperiment)
library(Polychrome)
library(spatialLIBD)
library(parallel)
library(BiocParallel)
```

### load up, modify for easier plotting and unique colnames, and post-clustering-crop V12D07075B1 to ISH-verified VMH area (which still contains ARC clusters)
```{r}
hyp2 <- readRDS("data/processing/hyp_umi600_gene450_chrm35_lognorm_053123.RDS")
colnames(hyp2) <- colData(hyp2)$key
rownames(hyp2) <- rowData(hyp2)$gene_name

### crop down
coordstmp <- as.data.frame(spatialCoords(hyp2))
rownames(coordstmp) <- colnames(hyp2)
coordstmp <- as.data.table(coordstmp,keep.rownames=T)
coordstmp <- coordstmp[,diag:=pxl_col_in_fullres+pxl_row_in_fullres]
coordstmp <- coordstmp[!(rn %in% grep(rn,pattern="V12D07-075_B1",value=T)&diag>30000)]

hyp2 <- hyp2[,colnames(hyp2)%in%coordstmp$rn]
stopifnot(dim(hyp2)[2]==nrow(coordstmp))

rm(coordstmp)
### load DE results for ARC vs. rest, stored as data.tables; subset to ARC-centric results (tables 1, 3, 5)
arcde <- readRDS("analysis/data/spe_053123/H05-bspace15-nnsvg10_ARC_clusters/ARC_pseudobulk_sexDE_noSpRep-adjs_V12D07075B1-cropped.RDS")

arcde <- arcde[c(1,3,5)]
# drop sex chr genes for plotting
arcde <- lapply(arcde,FUN=function(x){
    x[!(chr %in% c("chrX","chrY"))]
})

## add cluster assignments from nnsvg10_bayesspace k=15
bscl <- fread("analysis/data/spe_053123/H02-clustering/03-bs_harmony_hvg1020_nnsvg1020_9-15-20-31_out/BSpace_Harmony_nnsvg10pctile_15.txt")
bscl <- as.data.frame(bscl)
rownames(bscl) <- bscl$rn
bscl <- DataFrame(bscl)
bscl <- bscl[colnames(hyp2),]
colLabels(hyp2) <- as.factor(bscl$BShar_nnsvg10pctile_15)
rm(bscl)
```

```{r}
fetchlabel <- list(8,13,c(8,13))
i <- 1
for (i in c(1:length(arcde))){
    currun <- names(arcde)[i]
    bpp <- MulticoreParam(workers=9)
    plotgenes <- as.list(arcde[[i]][adj.P.Val<0.05,gene_name])
    hyp2.plt <- hyp2[,which(colData(hyp2)$label %in% fetchlabel[[i]])]
    bplapply(plotgenes,BPPARAM = bpp,FUN=function(x){
        
        # plot relevant clusters' spots alone
        plt <- spatialLIBD::vis_grid_gene(hyp2.plt,geneid = x,return_plots = T,spatial=F,point_size = 1,auto_crop = T)
        
        ### adjust font sizes
        plt <- lapply(plt,FUN=function(x){x+
                theme(plot.title = element_text(size = 11,hjust=0.5), strip.text = element_text(size=10), legend.text = element_text(size=10), legend.title = element_text(size=10,hjust=0.5))
            })
        
        ### render
        pdf(paste0("plots/spe_053123/H05-bspace15-nnsvg10_ARC_clusters/02-Autosomal Sex DEGs-no SpRep adjustment, postcrop V12D07075B1/",currun,"/",x,"_",currun,"-only.pdf"),width=10,height=8)
        do.call("grid.arrange",plt)
        dev.off()
        
        # plot gene in all spots
        plt <- spatialLIBD::vis_grid_gene(hyp2,geneid = x,return_plots = T,spatial=F,point_size = 1,auto_crop = T)
        
        ### adjust font sizes
        plt <- lapply(plt,FUN=function(x){x+
                theme(plot.title = element_text(size = 11,hjust=0.5), strip.text = element_text(size=10), legend.text = element_text(size=10), legend.title = element_text(size=10,hjust=0.5))
            })
        
        ### render
        pdf(paste0("plots/spe_053123/H05-bspace15-nnsvg10_ARC_clusters/02-Autosomal Sex DEGs-no SpRep adjustment, postcrop V12D07075B1/",currun,"/",x,"_allspots.pdf"),width=10,height=8)
        do.call("grid.arrange",plt)
        dev.off()
    })
    # clean up
    rm(currun,plotgenes,hyp2.plt)
}


```
