#!/bin/bash
#SBATCH --job-name=ldsc_anno_jobs.txt
#SBATCH --output=./ldsc_anno_jobs.txt_err_out/jobs_%A_%a.out
#SBATCH --error=./ldsc_anno_jobs.txt_err_out/jobs_%A_%a.err
#SBATCH --partition=shared
#SBATCH --mem-per-cpu=15G --cpus-per-task=2
#SBATCH --array=1-5%5


echo "**** Job starts ****"
date
module load ldsc
perl job_batch.pl --jfile ldsc_anno_jobs.txt --nrun 20 --n $SLURM_ARRAY_TASK_ID
echo "**** Job ends ****"
date
