#!/bin/bash
#SBATCH --job-name=ldsc_h2_jobs.txt
#SBATCH --output=./ldsc_h2_jobs.txt_err_out/jobs_%A_%a.out
#SBATCH --error=./ldsc_h2_jobs.txt_err_out/jobs_%A_%a.err
#SBATCH --partition=shared
#SBATCH --mem-per-cpu=25G --cpus-per-task=4
#SBATCH --array=1-16%16


echo "**** Job starts ****"
date
module load ldsc 
perl job_batch.pl --jfile ldsc_h2_jobs.txt --nrun 16 --n $SLURM_ARRAY_TASK_ID
echo "**** Job ends ****"
date
